/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

/**
 * @summary SendContact delivers a contact card to the external chat partner.
 */
export const providerMessageServiceSendContactBodyTypeDefault = `PROVIDER_TYPE_UNSPECIFIED`;

export const ProviderMessageServiceSendContactBody = zod
	.object({
		domain_id: zod.int().optional(),
		email: zod.string().optional(),
		external_user_id: zod.string().optional(),
		gate_id: zod.string().optional(),
		name: zod.string().optional(),
		phone_number: zod.string().optional(),
		reply_to_external_id: zod.string().optional(),
		sender_name: zod
			.string()
			.optional()
			.describe(
				'Display name of the operator (or bot) this message is from, when the channel can\nshow a per-message sender. Empty means "use the gate\'s own name".',
			),
		type: zod
			.enum([
				'PROVIDER_TYPE_UNSPECIFIED',
				'PROVIDER_TYPE_VIBER',
				'PROVIDER_TYPE_TELEGRAM_BOT',
				'PROVIDER_TYPE_TELEGRAM_APP',
				'PROVIDER_TYPE_META_APP',
				'PROVIDER_TYPE_FACEBOOK',
				'PROVIDER_TYPE_INSTAGRAM',
				'PROVIDER_TYPE_WHATSAPP',
			])
			.default(providerMessageServiceSendContactBodyTypeDefault)
			.describe(
				'/ ProviderType defines the specific provider or protocol used for messaging.',
			),
	})
	.describe('ProviderSendContactRequest sends a contact card.');

export const ProviderMessageServiceSendContactResponse = zod
	.object({
		created_at: zod.string().optional(),
		external_id: zod.string().optional(),
	})
	.describe(
		'ProviderSendMessageResponse returns the delivery status and external message ID.',
	);

/**
 * @summary SendDocument delivers file attachments to the external chat partner.
 */
export const providerMessageServiceSendDocumentBodyTypeDefault = `PROVIDER_TYPE_UNSPECIFIED`;

export const ProviderMessageServiceSendDocumentBody = zod
	.object({
		caption: zod.string().optional(),
		documents: zod
			.array(
				zod
					.object({
						id: zod.string().optional(),
						mime_type: zod.string().optional(),
						name: zod.string().optional(),
						size: zod.string().optional(),
						url: zod.string().optional(),
					})
					.describe('ProviderFile represents a generic file attachment.'),
			)
			.optional(),
		domain_id: zod.int().optional(),
		external_user_id: zod.string().optional(),
		gate_id: zod.string().optional(),
		message_id: zod
			.string()
			.optional()
			.describe(
				'Internal message context for per-recipient delivery status tracking.\n\nInternal message UUID',
			),
		reply_to_external_id: zod.string().optional(),
		sender_name: zod
			.string()
			.optional()
			.describe(
				'Display name of the operator (or bot) this message is from, when the channel can\nshow a per-message sender. Empty means "use the gate\'s own name".',
			),
		thread_id: zod.string().optional(),
		type: zod
			.enum([
				'PROVIDER_TYPE_UNSPECIFIED',
				'PROVIDER_TYPE_VIBER',
				'PROVIDER_TYPE_TELEGRAM_BOT',
				'PROVIDER_TYPE_TELEGRAM_APP',
				'PROVIDER_TYPE_META_APP',
				'PROVIDER_TYPE_FACEBOOK',
				'PROVIDER_TYPE_INSTAGRAM',
				'PROVIDER_TYPE_WHATSAPP',
			])
			.default(providerMessageServiceSendDocumentBodyTypeDefault)
			.describe(
				'/ ProviderType defines the specific provider or protocol used for messaging.',
			),
	})
	.describe(
		'ProviderSendDocumentRequest sends a document with an optional caption.',
	);

export const ProviderMessageServiceSendDocumentResponse = zod
	.object({
		created_at: zod.string().optional(),
		external_id: zod.string().optional(),
	})
	.describe(
		'ProviderSendMessageResponse returns the delivery status and external message ID.',
	);

/**
 * @summary SendImage delivers images to the external chat partner.
 */
export const providerMessageServiceSendImageBodyTypeDefault = `PROVIDER_TYPE_UNSPECIFIED`;

export const ProviderMessageServiceSendImageBody = zod
	.object({
		caption: zod.string().optional(),
		domain_id: zod.int().optional(),
		external_user_id: zod.string().optional(),
		gate_id: zod.string().optional(),
		images: zod
			.array(
				zod
					.object({
						id: zod.string().optional(),
						mime_type: zod.string().optional(),
						name: zod.string().optional(),
						size: zod.string().optional(),
						url: zod.string().optional(),
					})
					.describe('ProviderFile represents a generic file attachment.'),
			)
			.optional(),
		message_id: zod
			.string()
			.optional()
			.describe(
				'Internal message context for per-recipient delivery status tracking.\n\nInternal message UUID',
			),
		reply_to_external_id: zod.string().optional(),
		sender_name: zod
			.string()
			.optional()
			.describe(
				'Display name of the operator (or bot) this message is from, when the channel can\nshow a per-message sender. Empty means "use the gate\'s own name".',
			),
		thread_id: zod.string().optional(),
		type: zod
			.enum([
				'PROVIDER_TYPE_UNSPECIFIED',
				'PROVIDER_TYPE_VIBER',
				'PROVIDER_TYPE_TELEGRAM_BOT',
				'PROVIDER_TYPE_TELEGRAM_APP',
				'PROVIDER_TYPE_META_APP',
				'PROVIDER_TYPE_FACEBOOK',
				'PROVIDER_TYPE_INSTAGRAM',
				'PROVIDER_TYPE_WHATSAPP',
			])
			.default(providerMessageServiceSendImageBodyTypeDefault)
			.describe(
				'/ ProviderType defines the specific provider or protocol used for messaging.',
			),
	})
	.describe(
		'ProviderSendImageRequest sends an image with an optional caption.',
	);

export const ProviderMessageServiceSendImageResponse = zod
	.object({
		created_at: zod.string().optional(),
		external_id: zod.string().optional(),
	})
	.describe(
		'ProviderSendMessageResponse returns the delivery status and external message ID.',
	);

/**
 * @summary SendInteractive delivers a message with interactive UI elements (buttons, menus).
 */
export const providerMessageServiceSendInteractiveBodyInteractiveInputFieldStateDefault = `INPUT_FIELD_STATE_UNSPECIFIED`;
export const providerMessageServiceSendInteractiveBodyInteractivePlacementDefault = `MENU_PLACEMENT_UNSPECIFIED`;

export const ProviderMessageServiceSendInteractiveBody = zod
	.object({
		body: zod
			.string()
			.optional()
			.describe('Optional text body displayed above the interactive element.'),
		domain_id: zod.int().optional(),
		external_user_id: zod.string().optional(),
		gate_id: zod.string().optional(),
		interactive: zod
			.object({
				input_field_state: zod
					.enum([
						'INPUT_FIELD_STATE_UNSPECIFIED',
						'INPUT_FIELD_STATE_REGULAR',
						'INPUT_FIELD_STATE_MINIMIZED',
						'INPUT_FIELD_STATE_HIDDEN',
					])
					.default(
						providerMessageServiceSendInteractiveBodyInteractiveInputFieldStateDefault,
					)
					.describe(
						'Whether the recipient may still type while this menu is displayed.',
					),
				list_reply: zod
					.object({
						main_button_title: zod
							.string()
							.optional()
							.describe('Label of the main button that expands the list.'),
						sections: zod
							.array(
								zod
									.object({
										buttons: zod
											.array(
												zod
													.object({
														callback: zod
															.object({
																data: zod.string().optional(),
															})
															.optional()
															.describe(
																'ProviderKeyboardButtonCallback sends a backend event when clicked.',
															),
														id: zod
															.string()
															.optional()
															.describe(
																'Unique identifier returned in SendInteractiveCallback.',
															),
														label: zod
															.string()
															.optional()
															.describe('Display label on the button.'),
														request: zod
															.object({
																action: zod.string().optional(),
															})
															.optional()
															.describe(
																'ProviderKeyboardButtonRequest prompts the user for device data (location, phone, email).',
															),
														url: zod
															.object({
																url: zod.string().optional(),
															})
															.optional()
															.describe(
																'ProviderKeyboardButtonURL opens a web page when clicked.',
															),
													})
													.describe(
														'ProviderKeyboardButton is a single interactive element.',
													),
											)
											.optional(),
										section: zod.string().optional(),
									})
									.describe(
										'ProviderKeyboardRowWithSection is a titled group of buttons.',
									),
							)
							.optional(),
					})
					.optional()
					.describe(
						'ProviderKeyboardListReply is a dropdown-style menu with labeled sections.',
					),
				markup: zod
					.object({
						rows: zod
							.array(
								zod
									.object({
										buttons: zod
											.array(
												zod
													.object({
														callback: zod
															.object({
																data: zod.string().optional(),
															})
															.optional()
															.describe(
																'ProviderKeyboardButtonCallback sends a backend event when clicked.',
															),
														id: zod
															.string()
															.optional()
															.describe(
																'Unique identifier returned in SendInteractiveCallback.',
															),
														label: zod
															.string()
															.optional()
															.describe('Display label on the button.'),
														request: zod
															.object({
																action: zod.string().optional(),
															})
															.optional()
															.describe(
																'ProviderKeyboardButtonRequest prompts the user for device data (location, phone, email).',
															),
														url: zod
															.object({
																url: zod.string().optional(),
															})
															.optional()
															.describe(
																'ProviderKeyboardButtonURL opens a web page when clicked.',
															),
													})
													.describe(
														'ProviderKeyboardButton is a single interactive element.',
													),
											)
											.optional(),
									})
									.describe(
										'ProviderKeyboardRow is a horizontal row of buttons.',
									),
							)
							.optional(),
					})
					.optional()
					.describe('ProviderKeyboardMarkup is a grid of button rows.'),
				placement: zod
					.enum([
						'MENU_PLACEMENT_UNSPECIFIED',
						'MENU_PLACEMENT_INLINE',
						'MENU_PLACEMENT_PERSISTENT',
					])
					.default(
						providerMessageServiceSendInteractiveBodyInteractivePlacementDefault,
					)
					.describe(
						'Where the menu is rendered. Channels that only support one placement ignore it.',
					),
				single_use: zod
					.boolean()
					.optional()
					.describe(
						'When true the keyboard is hidden after the user interacts once.',
					),
			})
			.optional()
			.describe('Interactive payload — exactly one kind must be set.'),
		message_id: zod
			.string()
			.optional()
			.describe(
				'Internal message context for per-recipient delivery status tracking.\n\nInternal message UUID',
			),
		reply_to_external_id: zod.string().optional(),
		send_id: zod
			.string()
			.optional()
			.describe('Optional idempotency key to prevent duplicate delivery.'),
		sender_name: zod
			.string()
			.optional()
			.describe(
				'Display name of the operator (or bot) this message is from, when the channel can\nshow a per-message sender. Empty means "use the gate\'s own name".',
			),
		thread_id: zod.string().optional(),
	})
	.describe(
		'ProviderSendInteractiveRequest sends a message with interactive UI elements.',
	);

export const ProviderMessageServiceSendInteractiveResponse = zod
	.object({
		created_at: zod.string().optional(),
		external_id: zod.string().optional(),
	})
	.describe(
		'ProviderSendMessageResponse returns the delivery status and external message ID.',
	);

/**
 * @summary SendLocation delivers a geographic location to the external chat partner.
 */
export const providerMessageServiceSendLocationBodyTypeDefault = `PROVIDER_TYPE_UNSPECIFIED`;

export const ProviderMessageServiceSendLocationBody = zod
	.object({
		address: zod.string().optional(),
		domain_id: zod.int().optional(),
		external_user_id: zod.string().optional(),
		gate_id: zod.string().optional(),
		latitude: zod.number().optional(),
		longitude: zod.number().optional(),
		name: zod.string().optional(),
		reply_to_external_id: zod.string().optional(),
		sender_name: zod
			.string()
			.optional()
			.describe(
				'Display name of the operator (or bot) this message is from, when the channel can\nshow a per-message sender. Empty means "use the gate\'s own name".',
			),
		type: zod
			.enum([
				'PROVIDER_TYPE_UNSPECIFIED',
				'PROVIDER_TYPE_VIBER',
				'PROVIDER_TYPE_TELEGRAM_BOT',
				'PROVIDER_TYPE_TELEGRAM_APP',
				'PROVIDER_TYPE_META_APP',
				'PROVIDER_TYPE_FACEBOOK',
				'PROVIDER_TYPE_INSTAGRAM',
				'PROVIDER_TYPE_WHATSAPP',
			])
			.default(providerMessageServiceSendLocationBodyTypeDefault)
			.describe(
				'/ ProviderType defines the specific provider or protocol used for messaging.',
			),
	})
	.describe('ProviderSendLocationRequest sends a geographic location.');

export const ProviderMessageServiceSendLocationResponse = zod
	.object({
		created_at: zod.string().optional(),
		external_id: zod.string().optional(),
	})
	.describe(
		'ProviderSendMessageResponse returns the delivery status and external message ID.',
	);

/**
 * @summary SendReaction forwards an emoji reaction change to the external chat partner
(e.g. Telegram setMessageReaction). Best-effort and messenger-dependent:
providers without reaction support are a silent no-op. An empty emoji (with
removed=true) clears the caller's reaction on the target message.
 */
export const providerMessageServiceSendReactionBodyTypeDefault = `PROVIDER_TYPE_UNSPECIFIED`;

export const ProviderMessageServiceSendReactionBody = zod
	.object({
		domain_id: zod.int().optional(),
		emoji: zod
			.string()
			.optional()
			.describe('Emoji to set; empty when the reaction is being cleared.'),
		external_message_id: zod
			.string()
			.optional()
			.describe(
				'Platform-specific id of the message being reacted to (resolved by im-thread\nfrom its external-id mapping for the target gate).',
			),
		external_user_id: zod.string().optional(),
		gate_id: zod.string().optional(),
		message_id: zod
			.string()
			.optional()
			.describe(
				'Internal message context for logging/correlation.\n\nInternal message UUID',
			),
		removed: zod
			.boolean()
			.optional()
			.describe('True when the reaction is being removed rather than set.'),
		thread_id: zod.string().optional(),
		type: zod
			.enum([
				'PROVIDER_TYPE_UNSPECIFIED',
				'PROVIDER_TYPE_VIBER',
				'PROVIDER_TYPE_TELEGRAM_BOT',
				'PROVIDER_TYPE_TELEGRAM_APP',
				'PROVIDER_TYPE_META_APP',
				'PROVIDER_TYPE_FACEBOOK',
				'PROVIDER_TYPE_INSTAGRAM',
				'PROVIDER_TYPE_WHATSAPP',
			])
			.default(providerMessageServiceSendReactionBodyTypeDefault)
			.describe(
				'/ ProviderType defines the specific provider or protocol used for messaging.',
			),
	})
	.describe(
		'ProviderSendReactionRequest asks a provider to set or clear an emoji reaction\non a message already delivered to the external chat partner.',
	);

export const ProviderMessageServiceSendReactionResponse = zod
	.looseObject({})
	.describe(
		'ProviderSendReactionResponse is intentionally empty: reactions are\nfire-and-forget and best-effort.',
	);

/**
 * @summary SendSystemMessage delivers a system event notification to the external chat partner.
The im-providers-service resolves the gate-specific template and renders it as text
before forwarding to the underlying provider (Facebook, WhatsApp, etc.).
 */
export const ProviderMessageServiceSendSystemMessageBody = zod
	.object({
		domain_id: zod.int().optional(),
		event_type: zod
			.string()
			.optional()
			.describe(
				'System event type (e.g., "member_added", "member_removed", "transferred").\nUsed to look up the gate-specific template or fall back to the built-in default.',
			),
		external_user_id: zod
			.string()
			.optional()
			.describe("Recipient's platform-specific user identifier."),
		gate_id: zod
			.string()
			.optional()
			.describe('Internal ID of the configured gateway.'),
		message_id: zod
			.string()
			.optional()
			.describe(
				'Internal message context for per-recipient delivery status tracking.\n\nInternal message UUID',
			),
		thread_id: zod.string().optional(),
		vars: zod
			.record(zod.string(), zod.string())
			.optional()
			.describe(
				'Template variables sourced from the system message metadata.\nInjected into the template via Go text/template syntax (e.g. {{.new_member_role}}).',
			),
	})
	.describe(
		'ProviderSendSystemMessageRequest delivers a system event to the external chat partner.\nThe provider service resolves the gate-specific template and renders the final text\nusing the supplied variables before sending via the underlying provider API.',
	);

export const ProviderMessageServiceSendSystemMessageResponse = zod
	.object({
		created_at: zod.string().optional(),
		external_id: zod.string().optional(),
	})
	.describe(
		'ProviderSendMessageResponse returns the delivery status and external message ID.',
	);

/**
 * @summary SendText delivers a plain text message to the external chat partner.
 */
export const providerMessageServiceSendTextBodyTypeDefault = `PROVIDER_TYPE_UNSPECIFIED`;

export const ProviderMessageServiceSendTextBody = zod
	.object({
		domain_id: zod.int().optional(),
		external_user_id: zod.string().optional(),
		gate_id: zod.string().optional(),
		message_id: zod
			.string()
			.optional()
			.describe(
				'Internal message context for per-recipient delivery status tracking:\nthe provider service persists the provider_message_id mapping on send\nand reports MarkDelivered/MarkRead/MarkFailed receipts back to im-thread.\n\nInternal message UUID',
			),
		metadata: zod.record(zod.string(), zod.string()).optional(),
		reply_to_external_id: zod.string().optional(),
		sender_name: zod
			.string()
			.optional()
			.describe(
				'Display name of the operator (or bot) this message is from, when the channel can\nshow a per-message sender. Empty means "use the gate\'s own name".',
			),
		text: zod.string().optional(),
		thread_id: zod.string().optional(),
		type: zod
			.enum([
				'PROVIDER_TYPE_UNSPECIFIED',
				'PROVIDER_TYPE_VIBER',
				'PROVIDER_TYPE_TELEGRAM_BOT',
				'PROVIDER_TYPE_TELEGRAM_APP',
				'PROVIDER_TYPE_META_APP',
				'PROVIDER_TYPE_FACEBOOK',
				'PROVIDER_TYPE_INSTAGRAM',
				'PROVIDER_TYPE_WHATSAPP',
			])
			.default(providerMessageServiceSendTextBodyTypeDefault)
			.describe(
				'/ ProviderType defines the specific provider or protocol used for messaging.',
			),
	})
	.describe('ProviderSendTextRequest sends a simple text message.');

export const ProviderMessageServiceSendTextResponse = zod
	.object({
		created_at: zod.string().optional(),
		external_id: zod.string().optional(),
	})
	.describe(
		'ProviderSendMessageResponse returns the delivery status and external message ID.',
	);

/**
 * @summary SendTyping forwards an ephemeral "typing…" action to the external chat
partner (e.g. Telegram sendChatAction, Meta sender_action). It is
fire-and-forget and best-effort: channels whose provider does not support
typing are a silent no-op. Nothing is persisted.
 */
export const providerMessageServiceSendTypingBodyTypeDefault = `PROVIDER_TYPE_UNSPECIFIED`;

export const ProviderMessageServiceSendTypingBody = zod
	.object({
		domain_id: zod.int().optional(),
		external_user_id: zod.string().optional(),
		gate_id: zod.string().optional(),
		thread_id: zod.string().optional(),
		type: zod
			.enum([
				'PROVIDER_TYPE_UNSPECIFIED',
				'PROVIDER_TYPE_VIBER',
				'PROVIDER_TYPE_TELEGRAM_BOT',
				'PROVIDER_TYPE_TELEGRAM_APP',
				'PROVIDER_TYPE_META_APP',
				'PROVIDER_TYPE_FACEBOOK',
				'PROVIDER_TYPE_INSTAGRAM',
				'PROVIDER_TYPE_WHATSAPP',
			])
			.default(providerMessageServiceSendTypingBodyTypeDefault)
			.describe(
				'/ ProviderType defines the specific provider or protocol used for messaging.',
			),
		typing_on: zod.boolean().optional(),
	})
	.describe(
		'ProviderSendTypingRequest asks a provider to show/hide a typing indicator\nto the external chat partner.',
	);

export const ProviderMessageServiceSendTypingResponse = zod
	.looseObject({})
	.describe(
		'ProviderSendTypingResponse is intentionally empty: typing is fire-and-forget.',
	);
