/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

export const PauseTemplateServiceSearchPauseTemplateQueryParams = zod.object({
	q: zod.string().optional(),
	page: zod.int().optional(),
	size: zod.int().optional(),
	sort: zod.string().optional(),
	fields: zod.array(zod.string()).optional(),
});

export const PauseTemplateServiceSearchPauseTemplateResponse = zod.object({
	items: zod
		.array(
			zod.object({
				causes: zod
					.array(
						zod.object({
							cause: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								})
								.optional(),
							duration: zod.string().optional(),
						}),
					)
					.optional(),
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				description: zod.string().optional(),
				domain_id: zod.string().optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});

export const PauseTemplateServiceCreatePauseTemplateBody = zod.object({
	item: zod
		.object({
			causes: zod
				.array(
					zod.object({
						cause: zod
							.object({
								id: zod.string().optional(),
								name: zod.string().optional(),
							})
							.optional(),
						duration: zod.string().optional(),
					}),
				)
				.optional(),
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			description: zod.string().optional(),
			domain_id: zod.string().optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});

export const PauseTemplateServiceCreatePauseTemplateResponse = zod.object({
	item: zod
		.object({
			causes: zod
				.array(
					zod.object({
						cause: zod
							.object({
								id: zod.string().optional(),
								name: zod.string().optional(),
							})
							.optional(),
						duration: zod.string().optional(),
					}),
				)
				.optional(),
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			description: zod.string().optional(),
			domain_id: zod.string().optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});

export const PauseTemplateServiceDeletePauseTemplateParams = zod.object({
	id: zod.string(),
});

export const PauseTemplateServiceDeletePauseTemplateResponse = zod.object({
	id: zod.string().optional(),
});

export const PauseTemplateServiceReadPauseTemplateParams = zod.object({
	id: zod.string(),
});

export const PauseTemplateServiceReadPauseTemplateQueryParams = zod.object({
	fields: zod.array(zod.string()).optional(),
});

export const PauseTemplateServiceReadPauseTemplateResponse = zod.object({
	item: zod
		.object({
			causes: zod
				.array(
					zod.object({
						cause: zod
							.object({
								id: zod.string().optional(),
								name: zod.string().optional(),
							})
							.optional(),
						duration: zod.string().optional(),
					}),
				)
				.optional(),
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			description: zod.string().optional(),
			domain_id: zod.string().optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});

/**
 * @summary UpdatePauseTemplateCauseBulk updates a pause template with a list of causes.
Update existing cause, create that not exists in database and delete that not exists in the list.
 */
export const PauseTemplateServiceUpdatePauseTemplateParams = zod.object({
	'item.id': zod.string(),
});

export const PauseTemplateServiceUpdatePauseTemplateBody = zod.object({
	item: zod
		.object({
			causes: zod
				.array(
					zod.object({
						cause: zod
							.object({
								id: zod.string().optional(),
								name: zod.string().optional(),
							})
							.optional(),
						duration: zod.string().optional(),
					}),
				)
				.optional(),
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			description: zod.string().optional(),
			domain_id: zod.string().optional(),
			name: zod.string().optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});

export const PauseTemplateServiceUpdatePauseTemplateResponse = zod.object({
	item: zod
		.object({
			causes: zod
				.array(
					zod.object({
						cause: zod
							.object({
								id: zod.string().optional(),
								name: zod.string().optional(),
							})
							.optional(),
						duration: zod.string().optional(),
					}),
				)
				.optional(),
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			description: zod.string().optional(),
			domain_id: zod.string().optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});
