/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

/**
 * @summary / CreateWhatsAppGate registers a WhatsApp Business Account (WABA) gateway.
 */
export const WhatsAppServiceCreateWhatsAppGateBody = zod.object({
	bot: zod
		.object({
			iss: zod.string().optional(),
			sub: zod.string().optional(),
		})
		.optional(),
	enabled: zod.boolean().optional(),
	fb: zod
		.object({
			enabled: zod.boolean().optional(),
			meta_app_id: zod.string().optional(),
			name: zod.string().optional(),
			page_id: zod.string().optional(),
			page_token: zod.string().optional(),
			peer: zod
				.object({
					iss: zod.string().optional(),
					sub: zod.string().optional(),
				})
				.optional(),
		})
		.optional()
		.describe(
			'/ ProviderCreateFacebookGateRequest links a specific Facebook Page as a messaging gateway.',
		),
	name: zod.string().optional(),
	waba: zod
		.object({
			access_token: zod.string().optional(),
			business_id: zod.string().optional(),
			meta_app_id: zod.string().optional(),
			phone_number: zod.string().optional(),
			phone_number_id: zod.string().optional(),
		})
		.optional(),
});

export const WhatsAppServiceCreateWhatsAppGateResponse = zod.object({
	bot: zod
		.object({
			iss: zod.string().optional(),
			sub: zod.string().optional(),
		})
		.optional(),
	created_at: zod.string().optional(),
	created_by: zod.string().optional(),
	enabled: zod.boolean().optional(),
	id: zod.string().optional(),
	name: zod.string().optional(),
	type: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod.string().optional(),
	waba: zod
		.object({
			access_token: zod.string().optional(),
			access_token_expires_at: zod.string().optional(),
			business_id: zod.string().optional(),
			id: zod.string().optional(),
			meta_app_id: zod.string().optional(),
			phone_number: zod.string().optional(),
			phone_number_id: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary / DeleteWhatsAppGate removes the WhatsApp gateway integration.
 */
export const WhatsAppServiceDeleteWhatsAppGateParams = zod.object({
	id_1: zod.string(),
});

export const whatsAppServiceDeleteWhatsAppGateResponseItemStatusDefault = `PROVIDER_STATUS_UNSPECIFIED`;

export const WhatsAppServiceDeleteWhatsAppGateResponse = zod.object({
	item: zod
		.object({
			created_at: zod.string().optional(),
			id: zod.string().optional(),
			meta_app_id: zod.string().optional(),
			name: zod.string().optional(),
			phone_display: zod.string().optional(),
			phone_number_id: zod.string().optional(),
			status: zod
				.enum([
					'PROVIDER_STATUS_UNSPECIFIED',
					'PROVIDER_STATUS_ACTIVE',
					'PROVIDER_STATUS_INACTIVE',
					'PROVIDER_STATUS_ERROR',
				])
				.default(whatsAppServiceDeleteWhatsAppGateResponseItemStatusDefault)
				.describe(
					'/ ProviderStatus represents the operational state of a provider gateway.\n\n - PROVIDER_STATUS_ACTIVE: Provider is healthy and processing messages\n - PROVIDER_STATUS_INACTIVE: Manually disabled by user\n - PROVIDER_STATUS_ERROR: Connection or authentication failed',
				),
			updated_at: zod.string().optional(),
			waba_id: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary / GetWhatsAppGate retrieves configuration and status for a WhatsApp gateway.
 */
export const WhatsAppServiceGetWhatsAppGateParams = zod.object({
	id_1: zod.string(),
});

export const whatsAppServiceGetWhatsAppGateResponseItemStatusDefault = `PROVIDER_STATUS_UNSPECIFIED`;

export const WhatsAppServiceGetWhatsAppGateResponse = zod.object({
	item: zod
		.object({
			created_at: zod.string().optional(),
			id: zod.string().optional(),
			meta_app_id: zod.string().optional(),
			name: zod.string().optional(),
			phone_display: zod.string().optional(),
			phone_number_id: zod.string().optional(),
			status: zod
				.enum([
					'PROVIDER_STATUS_UNSPECIFIED',
					'PROVIDER_STATUS_ACTIVE',
					'PROVIDER_STATUS_INACTIVE',
					'PROVIDER_STATUS_ERROR',
				])
				.default(whatsAppServiceGetWhatsAppGateResponseItemStatusDefault)
				.describe(
					'/ ProviderStatus represents the operational state of a provider gateway.\n\n - PROVIDER_STATUS_ACTIVE: Provider is healthy and processing messages\n - PROVIDER_STATUS_INACTIVE: Manually disabled by user\n - PROVIDER_STATUS_ERROR: Connection or authentication failed',
				),
			updated_at: zod.string().optional(),
			waba_id: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary / UpdateWhatsAppGate updates WhatsApp-specific gateway configurations.
 */
export const WhatsAppServiceUpdateWhatsAppGateParams = zod.object({
	id_1: zod.string(),
});

export const WhatsAppServiceUpdateWhatsAppGateBody = zod
	.object({
		access_token: zod.string().optional(),
		name: zod.string().optional(),
	})
	.describe(
		'/ ProviderUpdateWhatsAppGateRequest updates WhatsApp-specific tokens or names.',
	);

export const whatsAppServiceUpdateWhatsAppGateResponseItemStatusDefault = `PROVIDER_STATUS_UNSPECIFIED`;

export const WhatsAppServiceUpdateWhatsAppGateResponse = zod
	.object({
		item: zod
			.object({
				created_at: zod.string().optional(),
				id: zod.string().optional(),
				meta_app_id: zod.string().optional(),
				name: zod.string().optional(),
				phone_display: zod.string().optional(),
				phone_number_id: zod.string().optional(),
				status: zod
					.enum([
						'PROVIDER_STATUS_UNSPECIFIED',
						'PROVIDER_STATUS_ACTIVE',
						'PROVIDER_STATUS_INACTIVE',
						'PROVIDER_STATUS_ERROR',
					])
					.default(whatsAppServiceUpdateWhatsAppGateResponseItemStatusDefault)
					.describe(
						'/ ProviderStatus represents the operational state of a provider gateway.\n\n - PROVIDER_STATUS_ACTIVE: Provider is healthy and processing messages\n - PROVIDER_STATUS_INACTIVE: Manually disabled by user\n - PROVIDER_STATUS_ERROR: Connection or authentication failed',
					),
				updated_at: zod.string().optional(),
				waba_id: zod.string().optional(),
			})
			.optional(),
	})
	.describe(
		'/ ProviderUpdateWhatsAppGateResponse returns the updated WhatsApp provider.',
	);
