/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

export const AddUserAccessTokenParams = zod.object({
	'token.user.id': zod.string().describe('identifier'),
});

export const AddUserAccessTokenQueryParams = zod.object({
	enable: zod
		.boolean()
		.optional()
		.describe(
			'ObjectId user = 1; // [required]\n string usage = 2;  // [optional] usage description\n bool enable = 3;',
		),
});

export const AddUserAccessTokenBody = zod
	.object({
		created_at: zod.string().optional(),
		created_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		deleted_at: zod.string().optional(),
		deleted_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		id: zod.string().optional(),
		token: zod.string().optional(),
		updated_at: zod.string().optional(),
		updated_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		usage: zod.string().optional(),
		user: zod
			.object({
				name: zod.string().optional(),
			})
			.optional(),
	})
	.describe(
		'processing\n------------\ntoken.user.id // [required] authorization\ntoken.usage   // [optional] short description',
	);

export const AddUserAccessTokenResponse = zod
	.object({
		created_at: zod.string().optional(),
		created_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		deleted_at: zod.string().optional(),
		deleted_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		id: zod.string().optional(),
		token: zod.string().optional(),
		updated_at: zod.string().optional(),
		updated_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		usage: zod.string().optional(),
		user: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
	})
	.describe('UserId lookup value.');

export const UpdateUserAccessToken2Params = zod.object({
	'update.user.id': zod.string().describe('identifier'),
	'update.id': zod.string().describe('tokenKey::token_key'),
});

export const UpdateUserAccessToken2QueryParams = zod.object({
	fields: zod
		.array(zod.string())
		.optional()
		.describe('[optional] PATCH implementation'),
	enable: zod.boolean().optional(),
});

export const UpdateUserAccessToken2Body = zod.object({
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	deleted_at: zod.string().optional(),
	deleted_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	token: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	usage: zod.string().optional(),
	user: zod
		.object({
			name: zod.string().optional(),
		})
		.optional(),
});

export const UpdateUserAccessToken2Response = zod
	.object({
		created_at: zod.string().optional(),
		created_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		deleted_at: zod.string().optional(),
		deleted_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		id: zod.string().optional(),
		token: zod.string().optional(),
		updated_at: zod.string().optional(),
		updated_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		usage: zod.string().optional(),
		user: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
	})
	.describe('UserId lookup value.');

export const UpdateUserAccessTokenParams = zod.object({
	'update.user.id': zod.string().describe('identifier'),
	'update.id': zod.string().describe('tokenKey::token_key'),
});

export const UpdateUserAccessTokenQueryParams = zod.object({
	fields: zod
		.array(zod.string())
		.optional()
		.describe('[optional] PATCH implementation'),
	enable: zod.boolean().optional(),
});

export const UpdateUserAccessTokenBody = zod.object({
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	deleted_at: zod.string().optional(),
	deleted_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	token: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	usage: zod.string().optional(),
	user: zod
		.object({
			name: zod.string().optional(),
		})
		.optional(),
});

export const UpdateUserAccessTokenResponse = zod
	.object({
		created_at: zod.string().optional(),
		created_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		deleted_at: zod.string().optional(),
		deleted_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		id: zod.string().optional(),
		token: zod.string().optional(),
		updated_at: zod.string().optional(),
		updated_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		usage: zod.string().optional(),
		user: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
	})
	.describe('UserId lookup value.');

export const ListUserAccessTokenParams = zod.object({
	'user.id': zod.string().describe('identifier'),
});

export const ListUserAccessTokenQueryParams = zod.object({
	'user.name': zod.string().optional().describe('display name'),
	q: zod
		.string()
		.optional()
		.describe('int32 page = 2;\nint64 size = 3;\n\n.usage ILIKE :q'),
	fields: zod
		.array(zod.string())
		.optional()
		.describe(
			'----- Search Options -------------------------\n\nselect: output (fields,...)',
		),
	sort: zod
		.array(zod.string())
		.optional()
		.describe('select: order by (fields,...)'),
	page: zod.int().optional().describe('select: offset {page}'),
	size: zod.int().optional().describe('select: limit {size}'),
});

export const ListUserAccessTokenResponse = zod.object({
	items: zod
		.array(
			zod
				.object({
					created_at: zod.string().optional(),
					created_by: zod
						.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						})
						.optional(),
					deleted_at: zod.string().optional(),
					deleted_by: zod
						.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						})
						.optional(),
					id: zod.string().optional(),
					token: zod.string().optional(),
					updated_at: zod.string().optional(),
					updated_by: zod
						.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						})
						.optional(),
					usage: zod.string().optional(),
					user: zod
						.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						})
						.optional(),
				})
				.describe('UserId lookup value.'),
		)
		.optional(),
	next: zod.boolean().optional(),
	page: zod.int().optional(),
	size: zod.string().optional(),
});

export const DeleteUserAccessTokenParams = zod.object({
	'user.id': zod.string().describe('identifier'),
	id: zod.string().describe('tokenKey::uuid'),
});

export const DeleteUserAccessTokenQueryParams = zod.object({
	'user.name': zod.string().optional().describe('display name'),
});

export const DeleteUserAccessTokenResponse = zod
	.object({
		created_at: zod.string().optional(),
		created_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		deleted_at: zod.string().optional(),
		deleted_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		id: zod.string().optional(),
		token: zod.string().optional(),
		updated_at: zod.string().optional(),
		updated_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		usage: zod.string().optional(),
		user: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
	})
	.describe('UserId lookup value.');

export const GetUserAccessTokenParams = zod.object({
	'user.id': zod.string().describe('identifier'),
	id: zod.string().describe('tokenKey::uuid'),
});

export const GetUserAccessTokenQueryParams = zod.object({
	'user.name': zod.string().optional().describe('display name'),
});

export const GetUserAccessTokenResponse = zod
	.object({
		created_at: zod.string().optional(),
		created_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		deleted_at: zod.string().optional(),
		deleted_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		id: zod.string().optional(),
		token: zod.string().optional(),
		updated_at: zod.string().optional(),
		updated_by: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		usage: zod.string().optional(),
		user: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
	})
	.describe('UserId lookup value.');
