/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

export const DeleteOAuthServiceBody = zod.object({
	id: zod.array(zod.string()).optional(),
	permanent: zod.boolean().optional(),
});

export const DeleteOAuthServiceResponse = zod.looseObject({});

export const SearchOAuthServiceQueryParams = zod.object({
	page: zod
		.int()
		.optional()
		.describe('----- Select Options -------------------------\n\ndefault: 1'),
	size: zod.int().optional().describe('default: 16'),
	fields: zod.array(zod.string()).optional().describe('attributes list'),
	sort: zod
		.array(zod.string())
		.optional()
		.describe('e.g.: "updated_at" - ASC; "!updated_at" - DESC;'),
	id: zod
		.array(zod.string())
		.optional()
		.describe(
			'----- Search Basic Filters ---------------------------\n\nselection: by unique identifier',
		),
	q: zod.string().optional().describe('term-of-search: lookup[name]'),
	name: zod
		.string()
		.optional()
		.describe("case-ignore substring match: ILIKE '*' - any; '?' - one"),
	access: zod
		.string()
		.optional()
		.describe(
			'[M]andatory[A]ccess[C]ontrol: with access mode (action) granted!',
		),
	enabled: zod
		.boolean()
		.optional()
		.describe('----- OAuthService-Specific Filters ----------------'),
});

export const SearchOAuthServiceResponse = zod.object({
	items: zod
		.array(
			zod.object({
				auth_url: zod.string().optional(),
				claims: zod
					.array(
						zod.object({
							type: zod.string().optional(),
							value: zod.string().optional(),
						}),
					)
					.optional()
					.describe('google.protobuf.Struct claims = 7;'),
				client_id: zod.string().optional(),
				client_secret: zod.string().optional(),
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				discovery_url: zod.string().optional(),
				domain: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				enabled: zod.boolean().optional(),
				id: zod.string().optional(),
				logo: zod.string().optional(),
				metadata: zod.looseObject({}).optional(),
				name: zod.string().optional(),
				scopes: zod.array(zod.string()).optional(),
				token_url: zod.string().optional(),
				type: zod.string().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				userinfo_url: zod.string().optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
	page: zod.int().optional(),
});

export const CreateOAuthServiceBody = zod.object({
	auth_url: zod.string().optional(),
	claims: zod
		.array(
			zod.object({
				type: zod.string().optional(),
				value: zod.string().optional(),
			}),
		)
		.optional()
		.describe('google.protobuf.Struct claims = 7;'),
	client_id: zod.string().optional(),
	client_secret: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	discovery_url: zod.string().optional(),
	domain: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	enabled: zod.boolean().optional(),
	id: zod.string().optional(),
	logo: zod.string().optional(),
	metadata: zod.looseObject({}).optional(),
	name: zod.string().optional(),
	scopes: zod.array(zod.string()).optional(),
	token_url: zod.string().optional(),
	type: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	userinfo_url: zod.string().optional(),
});

export const CreateOAuthServiceResponse = zod.object({
	auth_url: zod.string().optional(),
	claims: zod
		.array(
			zod.object({
				type: zod.string().optional(),
				value: zod.string().optional(),
			}),
		)
		.optional()
		.describe('google.protobuf.Struct claims = 7;'),
	client_id: zod.string().optional(),
	client_secret: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	discovery_url: zod.string().optional(),
	domain: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	enabled: zod.boolean().optional(),
	id: zod.string().optional(),
	logo: zod.string().optional(),
	metadata: zod.looseObject({}).optional(),
	name: zod.string().optional(),
	scopes: zod.array(zod.string()).optional(),
	token_url: zod.string().optional(),
	type: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	userinfo_url: zod.string().optional(),
});

export const DeleteOAuthService2Params = zod.object({
	id: zod.array(zod.string()).min(1),
});

export const DeleteOAuthService2Body = zod.object({
	permanent: zod.boolean().optional(),
});

export const DeleteOAuthService2Response = zod.looseObject({});

export const LocateOAuthServiceParams = zod.object({
	id: zod
		.array(zod.string())
		.min(1)
		.describe(
			'----- Search Basic Filters ---------------------------\n\nselection: by unique identifier',
		),
});

export const LocateOAuthServiceQueryParams = zod.object({
	page: zod
		.int()
		.optional()
		.describe('----- Select Options -------------------------\n\ndefault: 1'),
	size: zod.int().optional().describe('default: 16'),
	fields: zod.array(zod.string()).optional().describe('attributes list'),
	sort: zod
		.array(zod.string())
		.optional()
		.describe('e.g.: "updated_at" - ASC; "!updated_at" - DESC;'),
	q: zod.string().optional().describe('term-of-search: lookup[name]'),
	name: zod
		.string()
		.optional()
		.describe("case-ignore substring match: ILIKE '*' - any; '?' - one"),
	access: zod
		.string()
		.optional()
		.describe(
			'[M]andatory[A]ccess[C]ontrol: with access mode (action) granted!',
		),
	enabled: zod
		.boolean()
		.optional()
		.describe('----- OAuthService-Specific Filters ----------------'),
});

export const LocateOAuthServiceResponse = zod.object({
	auth_url: zod.string().optional(),
	claims: zod
		.array(
			zod.object({
				type: zod.string().optional(),
				value: zod.string().optional(),
			}),
		)
		.optional()
		.describe('google.protobuf.Struct claims = 7;'),
	client_id: zod.string().optional(),
	client_secret: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	discovery_url: zod.string().optional(),
	domain: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	enabled: zod.boolean().optional(),
	id: zod.string().optional(),
	logo: zod.string().optional(),
	metadata: zod.looseObject({}).optional(),
	name: zod.string().optional(),
	scopes: zod.array(zod.string()).optional(),
	token_url: zod.string().optional(),
	type: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	userinfo_url: zod.string().optional(),
});

export const UpdateOAuthService2Params = zod.object({
	id: zod.string().describe('Unique identifier of the OAuthService to update.'),
});

export const UpdateOAuthService2QueryParams = zod.object({
	fields: zod
		.array(zod.string())
		.optional()
		.describe('Fields for partial update. PATCH'),
});

export const UpdateOAuthService2Body = zod.object({
	auth_url: zod.string().optional(),
	claims: zod
		.array(
			zod.object({
				type: zod.string().optional(),
				value: zod.string().optional(),
			}),
		)
		.optional()
		.describe('google.protobuf.Struct claims = 7;'),
	client_id: zod.string().optional(),
	client_secret: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	discovery_url: zod.string().optional(),
	domain: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	enabled: zod.boolean().optional(),
	id: zod.string().optional(),
	logo: zod.string().optional(),
	metadata: zod.looseObject({}).optional(),
	name: zod.string().optional(),
	scopes: zod.array(zod.string()).optional(),
	token_url: zod.string().optional(),
	type: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	userinfo_url: zod.string().optional(),
});

export const UpdateOAuthService2Response = zod.object({
	auth_url: zod.string().optional(),
	claims: zod
		.array(
			zod.object({
				type: zod.string().optional(),
				value: zod.string().optional(),
			}),
		)
		.optional()
		.describe('google.protobuf.Struct claims = 7;'),
	client_id: zod.string().optional(),
	client_secret: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	discovery_url: zod.string().optional(),
	domain: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	enabled: zod.boolean().optional(),
	id: zod.string().optional(),
	logo: zod.string().optional(),
	metadata: zod.looseObject({}).optional(),
	name: zod.string().optional(),
	scopes: zod.array(zod.string()).optional(),
	token_url: zod.string().optional(),
	type: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	userinfo_url: zod.string().optional(),
});

export const UpdateOAuthServiceParams = zod.object({
	id: zod.string().describe('Unique identifier of the OAuthService to update.'),
});

export const UpdateOAuthServiceQueryParams = zod.object({
	fields: zod
		.array(zod.string())
		.optional()
		.describe('Fields for partial update. PATCH'),
});

export const UpdateOAuthServiceBody = zod.object({
	auth_url: zod.string().optional(),
	claims: zod
		.array(
			zod.object({
				type: zod.string().optional(),
				value: zod.string().optional(),
			}),
		)
		.optional()
		.describe('google.protobuf.Struct claims = 7;'),
	client_id: zod.string().optional(),
	client_secret: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	discovery_url: zod.string().optional(),
	domain: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	enabled: zod.boolean().optional(),
	id: zod.string().optional(),
	logo: zod.string().optional(),
	metadata: zod.looseObject({}).optional(),
	name: zod.string().optional(),
	scopes: zod.array(zod.string()).optional(),
	token_url: zod.string().optional(),
	type: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	userinfo_url: zod.string().optional(),
});

export const UpdateOAuthServiceResponse = zod.object({
	auth_url: zod.string().optional(),
	claims: zod
		.array(
			zod.object({
				type: zod.string().optional(),
				value: zod.string().optional(),
			}),
		)
		.optional()
		.describe('google.protobuf.Struct claims = 7;'),
	client_id: zod.string().optional(),
	client_secret: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	discovery_url: zod.string().optional(),
	domain: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	enabled: zod.boolean().optional(),
	id: zod.string().optional(),
	logo: zod.string().optional(),
	metadata: zod.looseObject({}).optional(),
	name: zod.string().optional(),
	scopes: zod.array(zod.string()).optional(),
	token_url: zod.string().optional(),
	type: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	userinfo_url: zod.string().optional(),
});
