/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

export const SearchImportTemplateQueryParams = zod.object({
	page: zod.int().optional(),
	size: zod.int().optional(),
	q: zod.string().optional(),
	sort: zod.string().optional(),
	fields: zod.array(zod.string()).optional(),
	id: zod.array(zod.int()).optional(),
});

export const searchImportTemplateResponseItemsItemSourceTypeDefault = `DefaultSourceType`;

export const SearchImportTemplateResponse = zod.object({
	items: zod
		.array(
			zod.object({
				parameters: zod.looseObject({}).optional(),
				description: zod.string().optional(),
				id: zod.int().optional(),
				name: zod.string().optional(),
				source: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				source_id: zod.string().optional(),
				source_type: zod
					.enum([
						'DefaultSourceType',
						'Dialer',
					])
					.default(searchImportTemplateResponseItemsItemSourceTypeDefault),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});

export const createImportTemplateBodySourceTypeDefault = `DefaultSourceType`;

export const CreateImportTemplateBody = zod
	.object({
		parameters: zod.looseObject({}),
		description: zod.string().optional(),
		name: zod.string(),
		source: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
		source_id: zod.string(),
		source_type: zod
			.enum([
				'DefaultSourceType',
				'Dialer',
			])
			.default(createImportTemplateBodySourceTypeDefault),
	})
	.describe('Create import template for CSV');

export const createImportTemplateResponseSourceTypeDefault = `DefaultSourceType`;

export const CreateImportTemplateResponse = zod.object({
	parameters: zod.looseObject({}).optional(),
	description: zod.string().optional(),
	id: zod.int().optional(),
	name: zod.string().optional(),
	source: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	source_id: zod.string().optional(),
	source_type: zod
		.enum([
			'DefaultSourceType',
			'Dialer',
		])
		.default(createImportTemplateResponseSourceTypeDefault),
});

export const DeleteImportTemplateParams = zod.object({
	id: zod.int(),
});

export const deleteImportTemplateResponseSourceTypeDefault = `DefaultSourceType`;

export const DeleteImportTemplateResponse = zod.object({
	parameters: zod.looseObject({}).optional(),
	description: zod.string().optional(),
	id: zod.int().optional(),
	name: zod.string().optional(),
	source: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	source_id: zod.string().optional(),
	source_type: zod
		.enum([
			'DefaultSourceType',
			'Dialer',
		])
		.default(deleteImportTemplateResponseSourceTypeDefault),
});

export const ReadImportTemplateParams = zod.object({
	id: zod.int(),
});

export const readImportTemplateResponseSourceTypeDefault = `DefaultSourceType`;

export const ReadImportTemplateResponse = zod.object({
	parameters: zod.looseObject({}).optional(),
	description: zod.string().optional(),
	id: zod.int().optional(),
	name: zod.string().optional(),
	source: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	source_id: zod.string().optional(),
	source_type: zod
		.enum([
			'DefaultSourceType',
			'Dialer',
		])
		.default(readImportTemplateResponseSourceTypeDefault),
});

export const PatchImportTemplateParams = zod.object({
	id: zod.int(),
});

export const PatchImportTemplateBody = zod
	.object({
		parameters: zod.looseObject({}).optional(),
		description: zod.string().optional(),
		fields: zod.array(zod.string()).optional(),
		name: zod.string().optional(),
	})
	.describe('Patch import template for CSV');

export const patchImportTemplateResponseSourceTypeDefault = `DefaultSourceType`;

export const PatchImportTemplateResponse = zod.object({
	parameters: zod.looseObject({}).optional(),
	description: zod.string().optional(),
	id: zod.int().optional(),
	name: zod.string().optional(),
	source: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	source_id: zod.string().optional(),
	source_type: zod
		.enum([
			'DefaultSourceType',
			'Dialer',
		])
		.default(patchImportTemplateResponseSourceTypeDefault),
});

export const UpdateImportTemplateParams = zod.object({
	id: zod.int(),
});

export const UpdateImportTemplateBody = zod
	.object({
		parameters: zod.looseObject({}).optional(),
		description: zod.string().optional(),
		name: zod.string(),
		source: zod
			.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			})
			.optional(),
	})
	.describe('Update import template for CSV');

export const updateImportTemplateResponseSourceTypeDefault = `DefaultSourceType`;

export const UpdateImportTemplateResponse = zod.object({
	parameters: zod.looseObject({}).optional(),
	description: zod.string().optional(),
	id: zod.int().optional(),
	name: zod.string().optional(),
	source: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	source_id: zod.string().optional(),
	source_type: zod
		.enum([
			'DefaultSourceType',
			'Dialer',
		])
		.default(updateImportTemplateResponseSourceTypeDefault),
});
