/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

/**
 * @summary Resolve returns article summaries for the given ids with RBAC applied
 */
export const ResolveBody = zod
	.object({
		ids: zod.array(zod.string()).optional().describe('Article ids to resolve.'),
		space_ids: zod
			.array(zod.string())
			.optional()
			.describe('Spaces the ids are expected in (RBAC scope).'),
	})
	.describe('ResolveRequest selects articles by id within the given spaces.');

export const resolveResponseItemsItemStateDefault = `ARTICLE_STATE_UNSPECIFIED`;
export const resolveResponseItemsItemTypeDefault = `ARTICLE_TYPE_UNSPECIFIED`;

export const ResolveResponse = zod
	.object({
		items: zod
			.array(
				zod
					.object({
						tags: zod.array(zod.string()).optional().describe('Article tags.'),
						body: zod
							.string()
							.optional()
							.describe(
								'FAQ body inlined for menu responses; empty otherwise.',
							),
						created_at: zod
							.string()
							.optional()
							.describe('CreatedAt timestamp (epoch ms).'),
						depth: zod.int().optional().describe('Hierarchy depth (1..5).'),
						id: zod
							.string()
							.optional()
							.describe('Unique identifier of the article.'),
						parent_id: zod
							.string()
							.optional()
							.describe('Parent article id; 0 for a top-level article.'),
						snippet: zod
							.string()
							.optional()
							.describe('Short text excerpt for previews and search hits.'),
						space_id: zod
							.string()
							.optional()
							.describe('Space the article belongs to.'),
						state: zod
							.enum([
								'ARTICLE_STATE_UNSPECIFIED',
								'DRAFT',
								'ACTIVE',
								'INACTIVE',
							])
							.default(resolveResponseItemsItemStateDefault)
							.describe('Lifecycle state.'),
						subject: zod
							.string()
							.optional()
							.describe('Current subject (mirrors the published version).'),
						type: zod
							.enum([
								'ARTICLE_TYPE_UNSPECIFIED',
								'ARTICLE',
								'FAQ',
							])
							.default(resolveResponseItemsItemTypeDefault)
							.describe('Article type.'),
						updated_at: zod
							.string()
							.optional()
							.describe('UpdatedAt timestamp (epoch ms).'),
					})
					.describe(
						'ArticleSummary is a lightweight read model of an article, used by list,\nsearch, resolve and menu responses (no body unless inlined for FAQ menu).',
					),
			)
			.optional()
			.describe('Resolved article summaries (RBAC filtered).'),
	})
	.describe('ResolveResponse returns the resolved article summaries.');

/**
 * @summary Search runs fast full-text search over title, tags and plaintext (no vector).
 */
export const searchRetrievalQueryTagMatchDefault = `TAG_MATCH_ALL`;

export const SearchRetrievalQueryParams = zod.object({
	query: zod.string().optional().describe('Free-text query.'),
	space_ids: zod
		.array(zod.string())
		.optional()
		.describe('Spaces to search within.'),
	tags: zod.array(zod.string()).optional().describe('Optional tag filter.'),
	tag_match: zod
		.enum([
			'TAG_MATCH_ALL',
			'TAG_MATCH_ANY',
		])
		.default(searchRetrievalQueryTagMatchDefault)
		.describe(
			'How to combine the tag filter.\n\n - TAG_MATCH_ALL: Default: match articles having ALL listed tags (AND).\n - TAG_MATCH_ANY: Match articles having ANY listed tag (OR).',
		),
	size: zod.int().optional().describe('Page size.'),
	page: zod.int().optional().describe('Page number (1-based).'),
});

export const searchRetrievalResponseItemsItemStateDefault = `ARTICLE_STATE_UNSPECIFIED`;
export const searchRetrievalResponseItemsItemTypeDefault = `ARTICLE_TYPE_UNSPECIFIED`;

export const SearchRetrievalResponse = zod
	.object({
		items: zod
			.array(
				zod
					.object({
						tags: zod.array(zod.string()).optional().describe('Article tags.'),
						body: zod
							.string()
							.optional()
							.describe(
								'FAQ body inlined for menu responses; empty otherwise.',
							),
						created_at: zod
							.string()
							.optional()
							.describe('CreatedAt timestamp (epoch ms).'),
						depth: zod.int().optional().describe('Hierarchy depth (1..5).'),
						id: zod
							.string()
							.optional()
							.describe('Unique identifier of the article.'),
						parent_id: zod
							.string()
							.optional()
							.describe('Parent article id; 0 for a top-level article.'),
						snippet: zod
							.string()
							.optional()
							.describe('Short text excerpt for previews and search hits.'),
						space_id: zod
							.string()
							.optional()
							.describe('Space the article belongs to.'),
						state: zod
							.enum([
								'ARTICLE_STATE_UNSPECIFIED',
								'DRAFT',
								'ACTIVE',
								'INACTIVE',
							])
							.default(searchRetrievalResponseItemsItemStateDefault)
							.describe('Lifecycle state.'),
						subject: zod
							.string()
							.optional()
							.describe('Current subject (mirrors the published version).'),
						type: zod
							.enum([
								'ARTICLE_TYPE_UNSPECIFIED',
								'ARTICLE',
								'FAQ',
							])
							.default(searchRetrievalResponseItemsItemTypeDefault)
							.describe('Article type.'),
						updated_at: zod
							.string()
							.optional()
							.describe('UpdatedAt timestamp (epoch ms).'),
					})
					.describe(
						'ArticleSummary is a lightweight read model of an article, used by list,\nsearch, resolve and menu responses (no body unless inlined for FAQ menu).',
					),
			)
			.optional()
			.describe('Matched article summaries.'),
		next: zod.boolean().optional().describe('Whether a next page exists.'),
	})
	.describe('SearchResponse is a page of article summaries.');

/**
 * @summary SemanticSearch runs hybrid retrieval (vector + full-text, RRF) and returns
chunks plus optional citations.
 */
export const semanticSearchBodyTagMatchDefault = `TAG_MATCH_ALL`;

export const SemanticSearchBody = zod
	.object({
		tags: zod.array(zod.string()).optional().describe('Optional tag filter.'),
		include_citations: zod
			.boolean()
			.optional()
			.describe('Whether to include structured citations.'),
		query: zod
			.string()
			.optional()
			.describe('Natural-language query (e.g. STT transcript).'),
		space_ids: zod
			.array(zod.string())
			.optional()
			.describe('Spaces to search within (bot service scope).'),
		tag_match: zod
			.enum([
				'TAG_MATCH_ALL',
				'TAG_MATCH_ANY',
			])
			.default(semanticSearchBodyTagMatchDefault)
			.describe('How to combine the tag filter.'),
		top_k: zod.int().optional().describe('Maximum number of chunks to return.'),
	})
	.describe('SemanticSearchRequest parameters for hybrid retrieval.');

export const SemanticSearchResponse = zod
	.object({
		chunks: zod
			.array(
				zod
					.object({
						article_id: zod
							.string()
							.optional()
							.describe('Article the chunk originates from.'),
						chunk_index: zod
							.int()
							.optional()
							.describe('Ordinal position of the chunk within the version.'),
						content: zod.string().optional().describe('Chunk text content.'),
						score: zod
							.number()
							.optional()
							.describe(
								'Relevance score assigned by retrieval (higher is better).',
							),
						version_id: zod
							.string()
							.optional()
							.describe('Article version the chunk was produced from.'),
					})
					.describe(
						'Chunk is a contiguous slice of an article version, the unit returned by\nsemantic search and consumed by downstream RAG.',
					),
			)
			.optional()
			.describe('Top-K ranked chunks.'),
		citations: zod
			.array(
				zod
					.object({
						article_id: zod.string().optional().describe('Source article id.'),
						snippet: zod
							.string()
							.optional()
							.describe('Quoted snippet supporting the answer.'),
						title: zod.string().optional().describe('Source article title.'),
						url: zod
							.string()
							.optional()
							.describe('Deep link to the source article.'),
					})
					.describe(
						'Citation is a structured source reference returned alongside retrieval\nresults; rendering is up to the consumer (chips, spoken, or suppressed).',
					),
			)
			.optional()
			.describe('Structured citations (empty unless requested).'),
	})
	.describe(
		'SemanticSearchResponse returns ranked chunks and optional citations.',
	);

/**
 * @summary Suggest runs hybrid retrieval with cross-encoder rerank for operator assist.
 */
export const SuggestBody = zod
	.object({
		customer_message: zod
			.string()
			.optional()
			.describe('Latest customer message used as the query.'),
		return_chunks: zod
			.boolean()
			.optional()
			.describe('When true return chunks instead of article summaries.'),
		space_ids: zod
			.array(zod.string())
			.optional()
			.describe('Spaces to search within.'),
		team_id: zod
			.string()
			.optional()
			.describe('Operator team id (team binding scope).'),
	})
	.describe('SuggestRequest parameters for operator assist.');

export const suggestResponseArticlesItemStateDefault = `ARTICLE_STATE_UNSPECIFIED`;
export const suggestResponseArticlesItemTypeDefault = `ARTICLE_TYPE_UNSPECIFIED`;

export const SuggestResponse = zod
	.object({
		articles: zod
			.array(
				zod
					.object({
						tags: zod.array(zod.string()).optional().describe('Article tags.'),
						body: zod
							.string()
							.optional()
							.describe(
								'FAQ body inlined for menu responses; empty otherwise.',
							),
						created_at: zod
							.string()
							.optional()
							.describe('CreatedAt timestamp (epoch ms).'),
						depth: zod.int().optional().describe('Hierarchy depth (1..5).'),
						id: zod
							.string()
							.optional()
							.describe('Unique identifier of the article.'),
						parent_id: zod
							.string()
							.optional()
							.describe('Parent article id; 0 for a top-level article.'),
						snippet: zod
							.string()
							.optional()
							.describe('Short text excerpt for previews and search hits.'),
						space_id: zod
							.string()
							.optional()
							.describe('Space the article belongs to.'),
						state: zod
							.enum([
								'ARTICLE_STATE_UNSPECIFIED',
								'DRAFT',
								'ACTIVE',
								'INACTIVE',
							])
							.default(suggestResponseArticlesItemStateDefault)
							.describe('Lifecycle state.'),
						subject: zod
							.string()
							.optional()
							.describe('Current subject (mirrors the published version).'),
						type: zod
							.enum([
								'ARTICLE_TYPE_UNSPECIFIED',
								'ARTICLE',
								'FAQ',
							])
							.default(suggestResponseArticlesItemTypeDefault)
							.describe('Article type.'),
						updated_at: zod
							.string()
							.optional()
							.describe('UpdatedAt timestamp (epoch ms).'),
					})
					.describe(
						'ArticleSummary is a lightweight read model of an article, used by list,\nsearch, resolve and menu responses (no body unless inlined for FAQ menu).',
					),
			)
			.optional()
			.describe('Suggested article summaries.'),
		chunks: zod
			.array(
				zod
					.object({
						article_id: zod
							.string()
							.optional()
							.describe('Article the chunk originates from.'),
						chunk_index: zod
							.int()
							.optional()
							.describe('Ordinal position of the chunk within the version.'),
						content: zod.string().optional().describe('Chunk text content.'),
						score: zod
							.number()
							.optional()
							.describe(
								'Relevance score assigned by retrieval (higher is better).',
							),
						version_id: zod
							.string()
							.optional()
							.describe('Article version the chunk was produced from.'),
					})
					.describe(
						'Chunk is a contiguous slice of an article version, the unit returned by\nsemantic search and consumed by downstream RAG.',
					),
			)
			.optional()
			.describe('Suggested chunks for draft generation.'),
	})
	.describe('SuggestResponse returns reranked suggestions.');

/**
 * @summary Menu lists child articles of a parent for bot menu buttons; FAQ children
include their body inline.
 */
export const MenuParams = zod.object({
	space_id: zod.string().describe('Space to read from.'),
});

export const MenuQueryParams = zod.object({
	parent_id: zod
		.string()
		.optional()
		.describe('Parent article id; 0 for top level.'),
	depth_limit: zod
		.int()
		.optional()
		.describe('Maximum hierarchy depth to return.'),
});

export const menuResponseItemsItemStateDefault = `ARTICLE_STATE_UNSPECIFIED`;
export const menuResponseItemsItemTypeDefault = `ARTICLE_TYPE_UNSPECIFIED`;

export const MenuResponse = zod
	.object({
		items: zod
			.array(
				zod
					.object({
						tags: zod.array(zod.string()).optional().describe('Article tags.'),
						body: zod
							.string()
							.optional()
							.describe(
								'FAQ body inlined for menu responses; empty otherwise.',
							),
						created_at: zod
							.string()
							.optional()
							.describe('CreatedAt timestamp (epoch ms).'),
						depth: zod.int().optional().describe('Hierarchy depth (1..5).'),
						id: zod
							.string()
							.optional()
							.describe('Unique identifier of the article.'),
						parent_id: zod
							.string()
							.optional()
							.describe('Parent article id; 0 for a top-level article.'),
						snippet: zod
							.string()
							.optional()
							.describe('Short text excerpt for previews and search hits.'),
						space_id: zod
							.string()
							.optional()
							.describe('Space the article belongs to.'),
						state: zod
							.enum([
								'ARTICLE_STATE_UNSPECIFIED',
								'DRAFT',
								'ACTIVE',
								'INACTIVE',
							])
							.default(menuResponseItemsItemStateDefault)
							.describe('Lifecycle state.'),
						subject: zod
							.string()
							.optional()
							.describe('Current subject (mirrors the published version).'),
						type: zod
							.enum([
								'ARTICLE_TYPE_UNSPECIFIED',
								'ARTICLE',
								'FAQ',
							])
							.default(menuResponseItemsItemTypeDefault)
							.describe('Article type.'),
						updated_at: zod
							.string()
							.optional()
							.describe('UpdatedAt timestamp (epoch ms).'),
					})
					.describe(
						'ArticleSummary is a lightweight read model of an article, used by list,\nsearch, resolve and menu responses (no body unless inlined for FAQ menu).',
					),
			)
			.optional()
			.describe('Child article summaries (FAQ children include body inline).'),
	})
	.describe('MenuResponse returns child articles for menu rendering.');
