/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

/**
 * @summary Searches messages grouped by the user's closed membership periods
within a thread. Active memberships are excluded — their
messages are available via SearchThreadMessagesHistory.
 */
export const MessageHistorySearchLeftThreadsMessagesHistoryParams = zod.object({
	thread_id: zod.string().describe('Filter by thread ID.'),
});

export const MessageHistorySearchLeftThreadsMessagesHistoryQueryParams =
	zod.object({
		fields: zod
			.array(zod.string())
			.optional()
			.describe(
				'List of message fields to be returned.\nUsed to reduce payload size.',
			),
		sender_ids: zod
			.array(zod.string())
			.optional()
			.describe('Filter messages by sender user IDs.'),
		types: zod
			.array(zod.int())
			.optional()
			.describe('Filter messages by message types.'),
		period_from: zod
			.string()
			.optional()
			.describe(
				'Inclusive lower bound on the dialog interval (Unix time, milliseconds).\nZero means unbounded.',
			),
		period_to: zod
			.string()
			.optional()
			.describe(
				'Inclusive upper bound on the dialog interval (Unix time, milliseconds).\nZero means unbounded.',
			),
		'cursor.id': zod
			.string()
			.optional()
			.describe(
				'Cursor identifier.\nMust be a valid UUID referencing an existing message.\nDefines the starting point for pagination.',
			),
		'cursor.before': zod
			.boolean()
			.optional()
			.describe(
				'Pagination direction flag.\n\ntrue  -> fetch newer messages (back before history)\nfalse -> fetch older messages (back to older history)',
			),
		size: zod
			.int()
			.optional()
			.describe('Maximum number of messages to return.'),
	});

export const messageHistorySearchLeftThreadsMessagesHistoryResponseItemsItemDeliveryStatusDefault = `MESSAGE_DELIVERY_STATUS_UNSPECIFIED`;
export const messageHistorySearchLeftThreadsMessagesHistoryResponseItemsItemForwardOriginKindDefault = `FORWARD_ORIGIN_KIND_UNSPECIFIED`;
export const messageHistorySearchLeftThreadsMessagesHistoryResponseItemsItemReactedMetadataReactedByRoleDefault = `ROLE_UNSPECIFIED`;
export const messageHistorySearchLeftThreadsMessagesHistoryResponseItemsItemReplyToSenderRoleDefault = `ROLE_UNSPECIFIED`;
export const messageHistorySearchLeftThreadsMessagesHistoryResponseItemsItemSenderRoleDefault = `ROLE_UNSPECIFIED`;
export const messageHistorySearchLeftThreadsMessagesHistoryResponseItemsItemStatusesItemStatusDefault = `MESSAGE_DELIVERY_STATUS_UNSPECIFIED`;

export const MessageHistorySearchLeftThreadsMessagesHistoryResponse = zod
	.object({
		items: zod
			.array(
				zod
					.object({
						body: zod.string().optional().describe('Message body content.'),
						contact: zod
							.object({
								email: zod.string().optional(),
								name: zod.string().optional(),
								phone: zod.string().optional(),
							})
							.optional(),
						created_at: zod
							.string()
							.optional()
							.describe(
								'Message creation timestamp (Unix time, milliseconds).',
							),
						deleted: zod
							.boolean()
							.optional()
							.describe(
								'True when the message was deleted by its author. Every content field\n(body, attachments, contact, location, interactive, metadata) is cleared,\nso clients should render a tombstone.',
							),
						deleted_at: zod
							.string()
							.optional()
							.describe(
								'Unix time in milliseconds when the message was deleted.',
							),
						delivery_status: zod
							.enum([
								'MESSAGE_DELIVERY_STATUS_UNSPECIFIED',
								'MESSAGE_DELIVERY_STATUS_SENT',
								'MESSAGE_DELIVERY_STATUS_DELIVERED',
								'MESSAGE_DELIVERY_STATUS_READ',
								'MESSAGE_DELIVERY_STATUS_FAILED',
							])
							.default(
								messageHistorySearchLeftThreadsMessagesHistoryResponseItemsItemDeliveryStatusDefault,
							)
							.describe(
								'Aggregated delivery status across recipients: FAILED when every\nrecipient failed, otherwise the minimal status among non-failed ones.\nUNSPECIFIED for messages without per-recipient tracking (historical).',
							),
						documents: zod
							.array(
								zod
									.object({
										created_at: zod
											.string()
											.optional()
											.describe(
												'Creation timestamp (Unix time, milliseconds).',
											),
										file_id: zod
											.string()
											.optional()
											.describe('File storage identifier.'),
										id: zod
											.string()
											.optional()
											.describe('Document identifier.'),
										message_id: zod
											.string()
											.optional()
											.describe(
												'Identifier of the message this document belongs to.',
											),
										mime: zod
											.string()
											.optional()
											.describe('MIME type of the document.'),
										name: zod
											.string()
											.optional()
											.describe('Original file name.'),
										size: zod
											.string()
											.optional()
											.describe('File size in bytes.'),
										url: zod
											.string()
											.optional()
											.describe(
												'Public signed URL for downloading the document.',
											),
									})
									.describe(
										'Document represents a file attachment\nassociated with a message.',
									),
							)
							.optional()
							.describe('List of document attachments.'),
						edited_at: zod
							.string()
							.optional()
							.describe(
								'Message last update timestamp (Unix time, milliseconds).',
							),
						forward_origin: zod
							.object({
								kind: zod
									.enum([
										'FORWARD_ORIGIN_KIND_UNSPECIFIED',
										'FORWARD_ORIGIN_KIND_INTERNAL',
										'FORWARD_ORIGIN_KIND_EXTERNAL_USER',
										'FORWARD_ORIGIN_KIND_EXTERNAL_HIDDEN_USER',
										'FORWARD_ORIGIN_KIND_EXTERNAL_CHAT',
									])
									.default(
										messageHistorySearchLeftThreadsMessagesHistoryResponseItemsItemForwardOriginKindDefault,
									)
									.describe(
										'ForwardOriginKind tells the client how to label a forwarded message and\nwhether the origin points at anything addressable inside Webitel.\n\n - FORWARD_ORIGIN_KIND_INTERNAL: Forwarded inside Webitel: sender_id and source_message_id are set.\n - FORWARD_ORIGIN_KIND_EXTERNAL_USER: Forwarded into the chat from an external messenger, author named.\n - FORWARD_ORIGIN_KIND_EXTERNAL_HIDDEN_USER: Same, but the author chose to hide their account, so there is no name.\n - FORWARD_ORIGIN_KIND_EXTERNAL_CHAT: Origin is an external group or channel rather than a person.',
									),
								original_sent_at: zod
									.string()
									.optional()
									.describe(
										'When the original message was sent, Unix time in milliseconds.',
									),
								sender_id: zod
									.string()
									.optional()
									.describe(
										'Contact id of the original author. Empty unless kind is INTERNAL.',
									),
								sender_name: zod
									.string()
									.optional()
									.describe(
										'Display name of the original author — the "from whom" label.',
									),
								source_message_id: zod
									.string()
									.optional()
									.describe(
										'Source message this copy was made from. Empty unless kind is INTERNAL,\nand cleared if the source is later purged.',
									),
							})
							.optional()
							.describe(
								'Set when this message is a forward. Never populated for a deleted\nmessage: the tombstone must not leak the origin name.',
							),
						id: zod.string().optional().describe('Unique message identifier.'),
						images: zod
							.array(
								zod
									.object({
										created_at: zod
											.string()
											.optional()
											.describe(
												'Creation timestamp (Unix time, milliseconds).',
											),
										file_id: zod
											.string()
											.optional()
											.describe('File storage identifier.'),
										height: zod
											.int()
											.optional()
											.describe('Image height in pixels.'),
										id: zod.string().optional().describe('Image identifier.'),
										message_id: zod
											.string()
											.optional()
											.describe(
												'Identifier of the message this message belongs to.',
											),
										mime: zod
											.string()
											.optional()
											.describe('MIME type of the image.'),
										url: zod
											.string()
											.optional()
											.describe('Public signed URL for accessing the image.'),
										width: zod
											.int()
											.optional()
											.describe('Image width in pixels.'),
									})
									.describe(
										'Image represents an image attachment\nassociated with a message.',
									),
							)
							.optional()
							.describe('List of image attachments.'),
						interactive: zod
							.object({
								documents: zod
									.object({
										documents: zod
											.array(
												zod
													.object({
														file_name: zod.string().optional(),
														id: zod.string().optional(),
														mime_type: zod.string().optional(),
														size_bytes: zod.string().optional(),
														url: zod.string().optional(),
													})
													.describe(
														'Represents `Document` message with necessary fields\nto process it into frequently used `document`\nentity in messaging systems.',
													),
											)
											.optional()
											.describe(
												'Documents to be attached to the header of interactive message.\nMax allowed documents: 10.',
											),
									})
									.optional()
									.describe('Document attachments header.'),
								images: zod
									.object({
										images: zod
											.array(
												zod
													.object({
														id: zod.string().optional(),
														link: zod.string().optional(),
														mime_type: zod.string().optional(),
														name: zod.string().optional(),
													})
													.describe(
														'Represents `Image` entity with\nnecessary fields.',
													),
											)
											.optional()
											.describe(
												'Images to be attached to the header of interactive message.\nMax allowed images: 10.',
											),
									})
									.optional()
									.describe('Images attachment header.'),
								list_reply: zod
									.object({
										main_button_title: zod
											.string()
											.optional()
											.describe(
												'Title of the main button, that on-click show up list.',
											),
										sections: zod
											.array(
												zod
													.object({
														buttons: zod
															.array(
																zod
																	.object({
																		callback: zod
																			.object({
																				data: zod
																					.string()
																					.optional()
																					.describe(
																						'Opaque data payload passed back to the server upon interaction.',
																					),
																			})
																			.optional()
																			.describe(
																				'Triggers a backend event (callback) with associated metadata.',
																			),
																		id: zod
																			.string()
																			.optional()
																			.describe(
																				'Unique idempotent identifier for the button.\nUsed by the frontend to track state and prevent duplicate interactions.',
																			),
																		label: zod
																			.string()
																			.optional()
																			.describe(
																				'The human-readable label displayed on the button.',
																			),
																		metadata: zod
																			.looseObject({})
																			.optional()
																			.describe(
																				'Extensible metadata for UI/UX styling (e.g., "color", "theme", "size").\nUsage: Allows for future-proofing without breaking schema changes.',
																			),
																		request: zod
																			.object({
																				action: zod
																					.string()
																					.optional()
																					.describe(
																						'The specific action to be performed by the client application.',
																					),
																			})
																			.optional()
																			.describe(
																				'Requests sensitive information from the client (e.g., location or contact).',
																			),
																		url: zod
																			.object({
																				url: zod
																					.string()
																					.optional()
																					.describe(
																						'Must be a valid absolute URI (e.g., https://example.com).',
																					),
																			})
																			.optional()
																			.describe(
																				'Directs the user to an external web resource.',
																			),
																	})
																	.describe(
																		'Defines a single interactive element within the keyboard.\nEach button must have a unique identifier and a specific action type.',
																	),
															)
															.optional()
															.describe(
																'Collection of buttons within this section.\nMinimum of 1 button is required to prevent empty sections.',
															),
														section: zod
															.string()
															.optional()
															.describe(
																'The header text for this section. Must be concise and descriptive.',
															),
													})
													.describe(
														'Represents a row of buttons grouped under a specific logical section header.\nUseful for creating categorized menus or structured interactive interfaces.',
													),
											)
											.optional()
											.describe('List with sections with buttons.'),
									})
									.optional()
									.describe(
										'List reply with main list button text and sections with buttons.',
									),
								markup: zod
									.object({
										rows: zod
											.array(
												zod
													.object({
														buttons: zod
															.array(
																zod
																	.object({
																		callback: zod
																			.object({
																				data: zod
																					.string()
																					.optional()
																					.describe(
																						'Opaque data payload passed back to the server upon interaction.',
																					),
																			})
																			.optional()
																			.describe(
																				'Triggers a backend event (callback) with associated metadata.',
																			),
																		id: zod
																			.string()
																			.optional()
																			.describe(
																				'Unique idempotent identifier for the button.\nUsed by the frontend to track state and prevent duplicate interactions.',
																			),
																		label: zod
																			.string()
																			.optional()
																			.describe(
																				'The human-readable label displayed on the button.',
																			),
																		metadata: zod
																			.looseObject({})
																			.optional()
																			.describe(
																				'Extensible metadata for UI/UX styling (e.g., "color", "theme", "size").\nUsage: Allows for future-proofing without breaking schema changes.',
																			),
																		request: zod
																			.object({
																				action: zod
																					.string()
																					.optional()
																					.describe(
																						'The specific action to be performed by the client application.',
																					),
																			})
																			.optional()
																			.describe(
																				'Requests sensitive information from the client (e.g., location or contact).',
																			),
																		url: zod
																			.object({
																				url: zod
																					.string()
																					.optional()
																					.describe(
																						'Must be a valid absolute URI (e.g., https://example.com).',
																					),
																			})
																			.optional()
																			.describe(
																				'Directs the user to an external web resource.',
																			),
																	})
																	.describe(
																		'Defines a single interactive element within the keyboard.\nEach button must have a unique identifier and a specific action type.',
																	),
															)
															.optional()
															.describe(
																'Horizontal collection of buttons.\nCapped at 10 to ensure UI responsiveness and prevent overflow.',
															),
													})
													.describe(
														'A standard horizontal row of interactive buttons without a section header.',
													),
											)
											.optional()
											.describe('Rows of buttons matrix.'),
									})
									.optional()
									.describe('Markup matrix with buttons.'),
								single_use: zod
									.boolean()
									.optional()
									.describe('Force to block user keyboard.'),
							})
							.optional()
							.describe(
								'Interactive represents a rich message with UI elements.',
							),
						location: zod
							.object({
								address: zod.string().optional(),
								latitude: zod.number().optional(),
								longitude: zod.number().optional(),
								name: zod.string().optional(),
							})
							.optional(),
						metadata: zod
							.looseObject({})
							.optional()
							.describe(
								'Arbitrary message metadata.\nCan contain structured data depending on message type.',
							),
						reacted_metadata: zod
							.object({
								button_code: zod
									.string()
									.optional()
									.describe('Button identifier.'),
								callback_data: zod
									.string()
									.optional()
									.describe('Optional callback payload.'),
								in_reply_to: zod
									.string()
									.optional()
									.describe('Original message ID.'),
								reacted_at: zod
									.string()
									.optional()
									.describe(
										'Unix time in milliseconds when callback button was clicked.',
									),
								reacted_by: zod
									.object({
										contact: zod
											.object({
												app_id: zod
													.string()
													.optional()
													.describe(
														'Identifier of the specific integration app or bot.',
													),
												created_at: zod
													.string()
													.optional()
													.describe(
														'Record creation timestamp (Unix Epoch in milliseconds).',
													),
												is_bot: zod
													.boolean()
													.optional()
													.describe(
														'Represents if usere is real person or automatic script.',
													),
												iss: zod
													.string()
													.optional()
													.describe(
														'Provider-specific unique identifier (Issuer ID).',
													),
												metadata: zod
													.record(zod.string(), zod.string())
													.optional()
													.describe(
														'Additional dynamic attributes provided by the messenger.',
													),
												name: zod
													.string()
													.optional()
													.describe('Display name of the contact.'),
												sub: zod
													.string()
													.optional()
													.describe(
														'Associated internal system subject/identifier.',
													),
												type: zod
													.string()
													.optional()
													.describe(
														"Channel type (e.g., 'webchat', 'telegram').",
													),
												updated_at: zod
													.string()
													.optional()
													.describe(
														'Last record update timestamp (Unix Epoch in milliseconds).',
													),
												username: zod
													.string()
													.optional()
													.describe('Technical username or handle.'),
												vias: zod
													.array(
														zod.object({
															contact_id: zod.string().optional(),
															created_at: zod.string().optional(),
															disable: zod.boolean().optional(),
															disable_reason: zod.string().optional(),
															metadata: zod.looseObject({}).optional(),
															updated_at: zod.string().optional(),
															via: zod.string().optional(),
														}),
													)
													.optional(),
											})
											.optional()
											.describe(
												'Contact represents an external messaging identity.',
											),
										id: zod.string().optional(),
										permissions: zod
											.object({
												can_add_members: zod.boolean().optional(),
												can_change_members_permissions: zod
													.boolean()
													.optional(),
												can_change_thread_info: zod.boolean().optional(),
												can_delete_messages: zod.boolean().optional(),
												can_remove_members: zod.boolean().optional(),
												can_send_messages: zod.boolean().optional(),
												created_at: zod.string().optional(),
												id: zod.string().optional(),
												member_id: zod.string().optional(),
												updated_at: zod.string().optional(),
											})
											.optional(),
										role: zod
											.enum([
												'ROLE_UNSPECIFIED',
												'ROLE_MEMBER',
												'ROLE_ADMIN',
												'ROLE_OWNER',
												'ROLE_SUPERVISOR',
											])
											.default(
												messageHistorySearchLeftThreadsMessagesHistoryResponseItemsItemReactedMetadataReactedByRoleDefault,
											),
									})
									.optional()
									.describe('User who clicked the button.'),
							})
							.optional()
							.describe(
								'Metadata for button reaction for interactive message.',
							),
						reply_to: zod
							.object({
								attachment_kind: zod.string().optional(),
								attachment_mime: zod.string().optional(),
								attachment_name: zod.string().optional(),
								body: zod.string().optional(),
								created_at: zod.string().optional(),
								id: zod.string().optional(),
								sender: zod
									.object({
										contact: zod
											.object({
												app_id: zod
													.string()
													.optional()
													.describe(
														'Identifier of the specific integration app or bot.',
													),
												created_at: zod
													.string()
													.optional()
													.describe(
														'Record creation timestamp (Unix Epoch in milliseconds).',
													),
												is_bot: zod
													.boolean()
													.optional()
													.describe(
														'Represents if usere is real person or automatic script.',
													),
												iss: zod
													.string()
													.optional()
													.describe(
														'Provider-specific unique identifier (Issuer ID).',
													),
												metadata: zod
													.record(zod.string(), zod.string())
													.optional()
													.describe(
														'Additional dynamic attributes provided by the messenger.',
													),
												name: zod
													.string()
													.optional()
													.describe('Display name of the contact.'),
												sub: zod
													.string()
													.optional()
													.describe(
														'Associated internal system subject/identifier.',
													),
												type: zod
													.string()
													.optional()
													.describe(
														"Channel type (e.g., 'webchat', 'telegram').",
													),
												updated_at: zod
													.string()
													.optional()
													.describe(
														'Last record update timestamp (Unix Epoch in milliseconds).',
													),
												username: zod
													.string()
													.optional()
													.describe('Technical username or handle.'),
												vias: zod
													.array(
														zod.object({
															contact_id: zod.string().optional(),
															created_at: zod.string().optional(),
															disable: zod.boolean().optional(),
															disable_reason: zod.string().optional(),
															metadata: zod.looseObject({}).optional(),
															updated_at: zod.string().optional(),
															via: zod.string().optional(),
														}),
													)
													.optional(),
											})
											.optional()
											.describe(
												'Contact represents an external messaging identity.',
											),
										id: zod.string().optional(),
										permissions: zod
											.object({
												can_add_members: zod.boolean().optional(),
												can_change_members_permissions: zod
													.boolean()
													.optional(),
												can_change_thread_info: zod.boolean().optional(),
												can_delete_messages: zod.boolean().optional(),
												can_remove_members: zod.boolean().optional(),
												can_send_messages: zod.boolean().optional(),
												created_at: zod.string().optional(),
												id: zod.string().optional(),
												member_id: zod.string().optional(),
												updated_at: zod.string().optional(),
											})
											.optional(),
										role: zod
											.enum([
												'ROLE_UNSPECIFIED',
												'ROLE_MEMBER',
												'ROLE_ADMIN',
												'ROLE_OWNER',
												'ROLE_SUPERVISOR',
											])
											.default(
												messageHistorySearchLeftThreadsMessagesHistoryResponseItemsItemReplyToSenderRoleDefault,
											),
									})
									.optional()
									.describe(
										'ThreadMember represents a thread participant\nwith optional type-specific settings.',
									),
								sender_id: zod.string().optional(),
								type: zod.int().optional(),
							})
							.optional(),
						sender: zod
							.object({
								contact: zod
									.object({
										app_id: zod
											.string()
											.optional()
											.describe(
												'Identifier of the specific integration app or bot.',
											),
										created_at: zod
											.string()
											.optional()
											.describe(
												'Record creation timestamp (Unix Epoch in milliseconds).',
											),
										is_bot: zod
											.boolean()
											.optional()
											.describe(
												'Represents if usere is real person or automatic script.',
											),
										iss: zod
											.string()
											.optional()
											.describe(
												'Provider-specific unique identifier (Issuer ID).',
											),
										metadata: zod
											.record(zod.string(), zod.string())
											.optional()
											.describe(
												'Additional dynamic attributes provided by the messenger.',
											),
										name: zod
											.string()
											.optional()
											.describe('Display name of the contact.'),
										sub: zod
											.string()
											.optional()
											.describe(
												'Associated internal system subject/identifier.',
											),
										type: zod
											.string()
											.optional()
											.describe("Channel type (e.g., 'webchat', 'telegram')."),
										updated_at: zod
											.string()
											.optional()
											.describe(
												'Last record update timestamp (Unix Epoch in milliseconds).',
											),
										username: zod
											.string()
											.optional()
											.describe('Technical username or handle.'),
										vias: zod
											.array(
												zod.object({
													contact_id: zod.string().optional(),
													created_at: zod.string().optional(),
													disable: zod.boolean().optional(),
													disable_reason: zod.string().optional(),
													metadata: zod.looseObject({}).optional(),
													updated_at: zod.string().optional(),
													via: zod.string().optional(),
												}),
											)
											.optional(),
									})
									.optional()
									.describe(
										'Contact represents an external messaging identity.',
									),
								id: zod.string().optional(),
								permissions: zod
									.object({
										can_add_members: zod.boolean().optional(),
										can_change_members_permissions: zod.boolean().optional(),
										can_change_thread_info: zod.boolean().optional(),
										can_delete_messages: zod.boolean().optional(),
										can_remove_members: zod.boolean().optional(),
										can_send_messages: zod.boolean().optional(),
										created_at: zod.string().optional(),
										id: zod.string().optional(),
										member_id: zod.string().optional(),
										updated_at: zod.string().optional(),
									})
									.optional(),
								role: zod
									.enum([
										'ROLE_UNSPECIFIED',
										'ROLE_MEMBER',
										'ROLE_ADMIN',
										'ROLE_OWNER',
										'ROLE_SUPERVISOR',
									])
									.default(
										messageHistorySearchLeftThreadsMessagesHistoryResponseItemsItemSenderRoleDefault,
									),
							})
							.optional()
							.describe('Sender user aggregated information.'),
						statuses: zod
							.array(
								zod
									.object({
										delivered_at: zod
											.string()
											.optional()
											.describe(
												'Unix time in milliseconds; zero when not reached.',
											),
										error: zod
											.string()
											.optional()
											.describe(
												'JSON-encoded provider error details for FAILED.',
											),
										failed_at: zod.string().optional(),
										member_id: zod
											.string()
											.optional()
											.describe('Recipient contact id.'),
										read_at: zod.string().optional(),
										status: zod
											.enum([
												'MESSAGE_DELIVERY_STATUS_UNSPECIFIED',
												'MESSAGE_DELIVERY_STATUS_SENT',
												'MESSAGE_DELIVERY_STATUS_DELIVERED',
												'MESSAGE_DELIVERY_STATUS_READ',
												'MESSAGE_DELIVERY_STATUS_FAILED',
											])
											.default(
												messageHistorySearchLeftThreadsMessagesHistoryResponseItemsItemStatusesItemStatusDefault,
											)
											.describe(
												'MessageDeliveryStatus is a per-recipient delivery state of a message.\nTransitions are monotonic: SENT -> DELIVERED -> READ.\nFAILED is terminal but may be superseded by a later DELIVERED (retry).\n\n - MESSAGE_DELIVERY_STATUS_SENT: Accepted by the system and queued for delivery.\n - MESSAGE_DELIVERY_STATUS_DELIVERED: Reached the recipient (stream ACK, push, provider receipt, bot dispatch).\n - MESSAGE_DELIVERY_STATUS_READ: Read by the recipient. Not applicable to bots.\n - MESSAGE_DELIVERY_STATUS_FAILED: Delivery failed (provider rejected, invalid contact, channel restriction).',
											),
										via: zod
											.string()
											.optional()
											.describe('Confirmation source: ws|push|provider|bot.'),
									})
									.describe(
										'MessageRecipientStatus is a per-recipient delivery state of a message.',
									),
							)
							.optional()
							.describe('Per-recipient delivery details.'),
						system: zod
							.object({
								message_id: zod
									.string()
									.optional()
									.describe(
										'ID of message for which system messages is binded.',
									),
								metadata: zod
									.looseObject({})
									.optional()
									.describe(
										'Represents additional metadata binded into system  message.',
									),
								type: zod
									.string()
									.optional()
									.describe('Represents type of the message.'),
							})
							.optional()
							.describe('System message content.'),
						thread_id: zod
							.string()
							.optional()
							.describe('Identifier of the thread the message belongs to.'),
						type: zod.int().optional().describe('Message type identifier.'),
					})
					.describe(
						'HistoryMessage represents a single message\nin thread history.',
					),
			)
			.optional()
			.describe('List of messages matching the search criteria.'),
		next_cursor: zod
			.object({
				id: zod
					.string()
					.optional()
					.describe('Unique identifier last message where cursor stopped.'),
			})
			.optional()
			.describe(
				"Cursor that represents position to get older messages (used without 'before' param).",
			),
		prev_cursor: zod
			.object({
				id: zod
					.string()
					.optional()
					.describe('Unique identifier last message where cursor stopped.'),
			})
			.optional()
			.describe(
				"Cursor that represents position to get newest messages (used with 'before' param).",
			),
	})
	.describe(
		'SearchMessageHistoryResponse contains\nmessage history search results and pagination metadata.',
	);

/**
 * @summary Searches messages within a specific thread.
Supports cursor-based pagination and field selection.
 */
export const MessageHistorySearchThreadMessagesHistoryParams = zod.object({
	thread_id: zod.string().describe('Filter by thread IDs.'),
});

export const MessageHistorySearchThreadMessagesHistoryQueryParams = zod.object({
	fields: zod
		.array(zod.string())
		.optional()
		.describe(
			'List of message fields to be returned.\nUsed to reduce payload size.',
		),
	ids: zod
		.array(zod.string())
		.optional()
		.describe('Filter by specific message IDs.'),
	sender_ids: zod
		.array(zod.string())
		.optional()
		.describe('Filter messages by sender user IDs.'),
	types: zod
		.array(zod.int())
		.optional()
		.describe('Filter messages by message types.'),
	'cursor.id': zod
		.string()
		.optional()
		.describe(
			'Cursor identifier.\nMust be a valid UUID referencing an existing message.\nDefines the starting point for pagination.',
		),
	'cursor.before': zod
		.boolean()
		.optional()
		.describe(
			'Pagination direction flag.\n\ntrue  -> fetch newer messages (back before history)\nfalse -> fetch older messages (back to older history)',
		),
	size: zod.int().optional().describe('Maximum number of messages to return.'),
});

export const messageHistorySearchThreadMessagesHistoryResponseItemsItemDeliveryStatusDefault = `MESSAGE_DELIVERY_STATUS_UNSPECIFIED`;
export const messageHistorySearchThreadMessagesHistoryResponseItemsItemForwardOriginKindDefault = `FORWARD_ORIGIN_KIND_UNSPECIFIED`;
export const messageHistorySearchThreadMessagesHistoryResponseItemsItemReactedMetadataReactedByRoleDefault = `ROLE_UNSPECIFIED`;
export const messageHistorySearchThreadMessagesHistoryResponseItemsItemReplyToSenderRoleDefault = `ROLE_UNSPECIFIED`;
export const messageHistorySearchThreadMessagesHistoryResponseItemsItemSenderRoleDefault = `ROLE_UNSPECIFIED`;
export const messageHistorySearchThreadMessagesHistoryResponseItemsItemStatusesItemStatusDefault = `MESSAGE_DELIVERY_STATUS_UNSPECIFIED`;

export const MessageHistorySearchThreadMessagesHistoryResponse = zod
	.object({
		items: zod
			.array(
				zod
					.object({
						body: zod.string().optional().describe('Message body content.'),
						contact: zod
							.object({
								email: zod.string().optional(),
								name: zod.string().optional(),
								phone: zod.string().optional(),
							})
							.optional(),
						created_at: zod
							.string()
							.optional()
							.describe(
								'Message creation timestamp (Unix time, milliseconds).',
							),
						deleted: zod
							.boolean()
							.optional()
							.describe(
								'True when the message was deleted by its author. Every content field\n(body, attachments, contact, location, interactive, metadata) is cleared,\nso clients should render a tombstone.',
							),
						deleted_at: zod
							.string()
							.optional()
							.describe(
								'Unix time in milliseconds when the message was deleted.',
							),
						delivery_status: zod
							.enum([
								'MESSAGE_DELIVERY_STATUS_UNSPECIFIED',
								'MESSAGE_DELIVERY_STATUS_SENT',
								'MESSAGE_DELIVERY_STATUS_DELIVERED',
								'MESSAGE_DELIVERY_STATUS_READ',
								'MESSAGE_DELIVERY_STATUS_FAILED',
							])
							.default(
								messageHistorySearchThreadMessagesHistoryResponseItemsItemDeliveryStatusDefault,
							)
							.describe(
								'Aggregated delivery status across recipients: FAILED when every\nrecipient failed, otherwise the minimal status among non-failed ones.\nUNSPECIFIED for messages without per-recipient tracking (historical).',
							),
						documents: zod
							.array(
								zod
									.object({
										created_at: zod
											.string()
											.optional()
											.describe(
												'Creation timestamp (Unix time, milliseconds).',
											),
										file_id: zod
											.string()
											.optional()
											.describe('File storage identifier.'),
										id: zod
											.string()
											.optional()
											.describe('Document identifier.'),
										message_id: zod
											.string()
											.optional()
											.describe(
												'Identifier of the message this document belongs to.',
											),
										mime: zod
											.string()
											.optional()
											.describe('MIME type of the document.'),
										name: zod
											.string()
											.optional()
											.describe('Original file name.'),
										size: zod
											.string()
											.optional()
											.describe('File size in bytes.'),
										url: zod
											.string()
											.optional()
											.describe(
												'Public signed URL for downloading the document.',
											),
									})
									.describe(
										'Document represents a file attachment\nassociated with a message.',
									),
							)
							.optional()
							.describe('List of document attachments.'),
						edited_at: zod
							.string()
							.optional()
							.describe(
								'Message last update timestamp (Unix time, milliseconds).',
							),
						forward_origin: zod
							.object({
								kind: zod
									.enum([
										'FORWARD_ORIGIN_KIND_UNSPECIFIED',
										'FORWARD_ORIGIN_KIND_INTERNAL',
										'FORWARD_ORIGIN_KIND_EXTERNAL_USER',
										'FORWARD_ORIGIN_KIND_EXTERNAL_HIDDEN_USER',
										'FORWARD_ORIGIN_KIND_EXTERNAL_CHAT',
									])
									.default(
										messageHistorySearchThreadMessagesHistoryResponseItemsItemForwardOriginKindDefault,
									)
									.describe(
										'ForwardOriginKind tells the client how to label a forwarded message and\nwhether the origin points at anything addressable inside Webitel.\n\n - FORWARD_ORIGIN_KIND_INTERNAL: Forwarded inside Webitel: sender_id and source_message_id are set.\n - FORWARD_ORIGIN_KIND_EXTERNAL_USER: Forwarded into the chat from an external messenger, author named.\n - FORWARD_ORIGIN_KIND_EXTERNAL_HIDDEN_USER: Same, but the author chose to hide their account, so there is no name.\n - FORWARD_ORIGIN_KIND_EXTERNAL_CHAT: Origin is an external group or channel rather than a person.',
									),
								original_sent_at: zod
									.string()
									.optional()
									.describe(
										'When the original message was sent, Unix time in milliseconds.',
									),
								sender_id: zod
									.string()
									.optional()
									.describe(
										'Contact id of the original author. Empty unless kind is INTERNAL.',
									),
								sender_name: zod
									.string()
									.optional()
									.describe(
										'Display name of the original author — the "from whom" label.',
									),
								source_message_id: zod
									.string()
									.optional()
									.describe(
										'Source message this copy was made from. Empty unless kind is INTERNAL,\nand cleared if the source is later purged.',
									),
							})
							.optional()
							.describe(
								'Set when this message is a forward. Never populated for a deleted\nmessage: the tombstone must not leak the origin name.',
							),
						id: zod.string().optional().describe('Unique message identifier.'),
						images: zod
							.array(
								zod
									.object({
										created_at: zod
											.string()
											.optional()
											.describe(
												'Creation timestamp (Unix time, milliseconds).',
											),
										file_id: zod
											.string()
											.optional()
											.describe('File storage identifier.'),
										height: zod
											.int()
											.optional()
											.describe('Image height in pixels.'),
										id: zod.string().optional().describe('Image identifier.'),
										message_id: zod
											.string()
											.optional()
											.describe(
												'Identifier of the message this message belongs to.',
											),
										mime: zod
											.string()
											.optional()
											.describe('MIME type of the image.'),
										url: zod
											.string()
											.optional()
											.describe('Public signed URL for accessing the image.'),
										width: zod
											.int()
											.optional()
											.describe('Image width in pixels.'),
									})
									.describe(
										'Image represents an image attachment\nassociated with a message.',
									),
							)
							.optional()
							.describe('List of image attachments.'),
						interactive: zod
							.object({
								documents: zod
									.object({
										documents: zod
											.array(
												zod
													.object({
														file_name: zod.string().optional(),
														id: zod.string().optional(),
														mime_type: zod.string().optional(),
														size_bytes: zod.string().optional(),
														url: zod.string().optional(),
													})
													.describe(
														'Represents `Document` message with necessary fields\nto process it into frequently used `document`\nentity in messaging systems.',
													),
											)
											.optional()
											.describe(
												'Documents to be attached to the header of interactive message.\nMax allowed documents: 10.',
											),
									})
									.optional()
									.describe('Document attachments header.'),
								images: zod
									.object({
										images: zod
											.array(
												zod
													.object({
														id: zod.string().optional(),
														link: zod.string().optional(),
														mime_type: zod.string().optional(),
														name: zod.string().optional(),
													})
													.describe(
														'Represents `Image` entity with\nnecessary fields.',
													),
											)
											.optional()
											.describe(
												'Images to be attached to the header of interactive message.\nMax allowed images: 10.',
											),
									})
									.optional()
									.describe('Images attachment header.'),
								list_reply: zod
									.object({
										main_button_title: zod
											.string()
											.optional()
											.describe(
												'Title of the main button, that on-click show up list.',
											),
										sections: zod
											.array(
												zod
													.object({
														buttons: zod
															.array(
																zod
																	.object({
																		callback: zod
																			.object({
																				data: zod
																					.string()
																					.optional()
																					.describe(
																						'Opaque data payload passed back to the server upon interaction.',
																					),
																			})
																			.optional()
																			.describe(
																				'Triggers a backend event (callback) with associated metadata.',
																			),
																		id: zod
																			.string()
																			.optional()
																			.describe(
																				'Unique idempotent identifier for the button.\nUsed by the frontend to track state and prevent duplicate interactions.',
																			),
																		label: zod
																			.string()
																			.optional()
																			.describe(
																				'The human-readable label displayed on the button.',
																			),
																		metadata: zod
																			.looseObject({})
																			.optional()
																			.describe(
																				'Extensible metadata for UI/UX styling (e.g., "color", "theme", "size").\nUsage: Allows for future-proofing without breaking schema changes.',
																			),
																		request: zod
																			.object({
																				action: zod
																					.string()
																					.optional()
																					.describe(
																						'The specific action to be performed by the client application.',
																					),
																			})
																			.optional()
																			.describe(
																				'Requests sensitive information from the client (e.g., location or contact).',
																			),
																		url: zod
																			.object({
																				url: zod
																					.string()
																					.optional()
																					.describe(
																						'Must be a valid absolute URI (e.g., https://example.com).',
																					),
																			})
																			.optional()
																			.describe(
																				'Directs the user to an external web resource.',
																			),
																	})
																	.describe(
																		'Defines a single interactive element within the keyboard.\nEach button must have a unique identifier and a specific action type.',
																	),
															)
															.optional()
															.describe(
																'Collection of buttons within this section.\nMinimum of 1 button is required to prevent empty sections.',
															),
														section: zod
															.string()
															.optional()
															.describe(
																'The header text for this section. Must be concise and descriptive.',
															),
													})
													.describe(
														'Represents a row of buttons grouped under a specific logical section header.\nUseful for creating categorized menus or structured interactive interfaces.',
													),
											)
											.optional()
											.describe('List with sections with buttons.'),
									})
									.optional()
									.describe(
										'List reply with main list button text and sections with buttons.',
									),
								markup: zod
									.object({
										rows: zod
											.array(
												zod
													.object({
														buttons: zod
															.array(
																zod
																	.object({
																		callback: zod
																			.object({
																				data: zod
																					.string()
																					.optional()
																					.describe(
																						'Opaque data payload passed back to the server upon interaction.',
																					),
																			})
																			.optional()
																			.describe(
																				'Triggers a backend event (callback) with associated metadata.',
																			),
																		id: zod
																			.string()
																			.optional()
																			.describe(
																				'Unique idempotent identifier for the button.\nUsed by the frontend to track state and prevent duplicate interactions.',
																			),
																		label: zod
																			.string()
																			.optional()
																			.describe(
																				'The human-readable label displayed on the button.',
																			),
																		metadata: zod
																			.looseObject({})
																			.optional()
																			.describe(
																				'Extensible metadata for UI/UX styling (e.g., "color", "theme", "size").\nUsage: Allows for future-proofing without breaking schema changes.',
																			),
																		request: zod
																			.object({
																				action: zod
																					.string()
																					.optional()
																					.describe(
																						'The specific action to be performed by the client application.',
																					),
																			})
																			.optional()
																			.describe(
																				'Requests sensitive information from the client (e.g., location or contact).',
																			),
																		url: zod
																			.object({
																				url: zod
																					.string()
																					.optional()
																					.describe(
																						'Must be a valid absolute URI (e.g., https://example.com).',
																					),
																			})
																			.optional()
																			.describe(
																				'Directs the user to an external web resource.',
																			),
																	})
																	.describe(
																		'Defines a single interactive element within the keyboard.\nEach button must have a unique identifier and a specific action type.',
																	),
															)
															.optional()
															.describe(
																'Horizontal collection of buttons.\nCapped at 10 to ensure UI responsiveness and prevent overflow.',
															),
													})
													.describe(
														'A standard horizontal row of interactive buttons without a section header.',
													),
											)
											.optional()
											.describe('Rows of buttons matrix.'),
									})
									.optional()
									.describe('Markup matrix with buttons.'),
								single_use: zod
									.boolean()
									.optional()
									.describe('Force to block user keyboard.'),
							})
							.optional()
							.describe(
								'Interactive represents a rich message with UI elements.',
							),
						location: zod
							.object({
								address: zod.string().optional(),
								latitude: zod.number().optional(),
								longitude: zod.number().optional(),
								name: zod.string().optional(),
							})
							.optional(),
						metadata: zod
							.looseObject({})
							.optional()
							.describe(
								'Arbitrary message metadata.\nCan contain structured data depending on message type.',
							),
						reacted_metadata: zod
							.object({
								button_code: zod
									.string()
									.optional()
									.describe('Button identifier.'),
								callback_data: zod
									.string()
									.optional()
									.describe('Optional callback payload.'),
								in_reply_to: zod
									.string()
									.optional()
									.describe('Original message ID.'),
								reacted_at: zod
									.string()
									.optional()
									.describe(
										'Unix time in milliseconds when callback button was clicked.',
									),
								reacted_by: zod
									.object({
										contact: zod
											.object({
												app_id: zod
													.string()
													.optional()
													.describe(
														'Identifier of the specific integration app or bot.',
													),
												created_at: zod
													.string()
													.optional()
													.describe(
														'Record creation timestamp (Unix Epoch in milliseconds).',
													),
												is_bot: zod
													.boolean()
													.optional()
													.describe(
														'Represents if usere is real person or automatic script.',
													),
												iss: zod
													.string()
													.optional()
													.describe(
														'Provider-specific unique identifier (Issuer ID).',
													),
												metadata: zod
													.record(zod.string(), zod.string())
													.optional()
													.describe(
														'Additional dynamic attributes provided by the messenger.',
													),
												name: zod
													.string()
													.optional()
													.describe('Display name of the contact.'),
												sub: zod
													.string()
													.optional()
													.describe(
														'Associated internal system subject/identifier.',
													),
												type: zod
													.string()
													.optional()
													.describe(
														"Channel type (e.g., 'webchat', 'telegram').",
													),
												updated_at: zod
													.string()
													.optional()
													.describe(
														'Last record update timestamp (Unix Epoch in milliseconds).',
													),
												username: zod
													.string()
													.optional()
													.describe('Technical username or handle.'),
												vias: zod
													.array(
														zod.object({
															contact_id: zod.string().optional(),
															created_at: zod.string().optional(),
															disable: zod.boolean().optional(),
															disable_reason: zod.string().optional(),
															metadata: zod.looseObject({}).optional(),
															updated_at: zod.string().optional(),
															via: zod.string().optional(),
														}),
													)
													.optional(),
											})
											.optional()
											.describe(
												'Contact represents an external messaging identity.',
											),
										id: zod.string().optional(),
										permissions: zod
											.object({
												can_add_members: zod.boolean().optional(),
												can_change_members_permissions: zod
													.boolean()
													.optional(),
												can_change_thread_info: zod.boolean().optional(),
												can_delete_messages: zod.boolean().optional(),
												can_remove_members: zod.boolean().optional(),
												can_send_messages: zod.boolean().optional(),
												created_at: zod.string().optional(),
												id: zod.string().optional(),
												member_id: zod.string().optional(),
												updated_at: zod.string().optional(),
											})
											.optional(),
										role: zod
											.enum([
												'ROLE_UNSPECIFIED',
												'ROLE_MEMBER',
												'ROLE_ADMIN',
												'ROLE_OWNER',
												'ROLE_SUPERVISOR',
											])
											.default(
												messageHistorySearchThreadMessagesHistoryResponseItemsItemReactedMetadataReactedByRoleDefault,
											),
									})
									.optional()
									.describe('User who clicked the button.'),
							})
							.optional()
							.describe(
								'Metadata for button reaction for interactive message.',
							),
						reply_to: zod
							.object({
								attachment_kind: zod.string().optional(),
								attachment_mime: zod.string().optional(),
								attachment_name: zod.string().optional(),
								body: zod.string().optional(),
								created_at: zod.string().optional(),
								id: zod.string().optional(),
								sender: zod
									.object({
										contact: zod
											.object({
												app_id: zod
													.string()
													.optional()
													.describe(
														'Identifier of the specific integration app or bot.',
													),
												created_at: zod
													.string()
													.optional()
													.describe(
														'Record creation timestamp (Unix Epoch in milliseconds).',
													),
												is_bot: zod
													.boolean()
													.optional()
													.describe(
														'Represents if usere is real person or automatic script.',
													),
												iss: zod
													.string()
													.optional()
													.describe(
														'Provider-specific unique identifier (Issuer ID).',
													),
												metadata: zod
													.record(zod.string(), zod.string())
													.optional()
													.describe(
														'Additional dynamic attributes provided by the messenger.',
													),
												name: zod
													.string()
													.optional()
													.describe('Display name of the contact.'),
												sub: zod
													.string()
													.optional()
													.describe(
														'Associated internal system subject/identifier.',
													),
												type: zod
													.string()
													.optional()
													.describe(
														"Channel type (e.g., 'webchat', 'telegram').",
													),
												updated_at: zod
													.string()
													.optional()
													.describe(
														'Last record update timestamp (Unix Epoch in milliseconds).',
													),
												username: zod
													.string()
													.optional()
													.describe('Technical username or handle.'),
												vias: zod
													.array(
														zod.object({
															contact_id: zod.string().optional(),
															created_at: zod.string().optional(),
															disable: zod.boolean().optional(),
															disable_reason: zod.string().optional(),
															metadata: zod.looseObject({}).optional(),
															updated_at: zod.string().optional(),
															via: zod.string().optional(),
														}),
													)
													.optional(),
											})
											.optional()
											.describe(
												'Contact represents an external messaging identity.',
											),
										id: zod.string().optional(),
										permissions: zod
											.object({
												can_add_members: zod.boolean().optional(),
												can_change_members_permissions: zod
													.boolean()
													.optional(),
												can_change_thread_info: zod.boolean().optional(),
												can_delete_messages: zod.boolean().optional(),
												can_remove_members: zod.boolean().optional(),
												can_send_messages: zod.boolean().optional(),
												created_at: zod.string().optional(),
												id: zod.string().optional(),
												member_id: zod.string().optional(),
												updated_at: zod.string().optional(),
											})
											.optional(),
										role: zod
											.enum([
												'ROLE_UNSPECIFIED',
												'ROLE_MEMBER',
												'ROLE_ADMIN',
												'ROLE_OWNER',
												'ROLE_SUPERVISOR',
											])
											.default(
												messageHistorySearchThreadMessagesHistoryResponseItemsItemReplyToSenderRoleDefault,
											),
									})
									.optional()
									.describe(
										'ThreadMember represents a thread participant\nwith optional type-specific settings.',
									),
								sender_id: zod.string().optional(),
								type: zod.int().optional(),
							})
							.optional(),
						sender: zod
							.object({
								contact: zod
									.object({
										app_id: zod
											.string()
											.optional()
											.describe(
												'Identifier of the specific integration app or bot.',
											),
										created_at: zod
											.string()
											.optional()
											.describe(
												'Record creation timestamp (Unix Epoch in milliseconds).',
											),
										is_bot: zod
											.boolean()
											.optional()
											.describe(
												'Represents if usere is real person or automatic script.',
											),
										iss: zod
											.string()
											.optional()
											.describe(
												'Provider-specific unique identifier (Issuer ID).',
											),
										metadata: zod
											.record(zod.string(), zod.string())
											.optional()
											.describe(
												'Additional dynamic attributes provided by the messenger.',
											),
										name: zod
											.string()
											.optional()
											.describe('Display name of the contact.'),
										sub: zod
											.string()
											.optional()
											.describe(
												'Associated internal system subject/identifier.',
											),
										type: zod
											.string()
											.optional()
											.describe("Channel type (e.g., 'webchat', 'telegram')."),
										updated_at: zod
											.string()
											.optional()
											.describe(
												'Last record update timestamp (Unix Epoch in milliseconds).',
											),
										username: zod
											.string()
											.optional()
											.describe('Technical username or handle.'),
										vias: zod
											.array(
												zod.object({
													contact_id: zod.string().optional(),
													created_at: zod.string().optional(),
													disable: zod.boolean().optional(),
													disable_reason: zod.string().optional(),
													metadata: zod.looseObject({}).optional(),
													updated_at: zod.string().optional(),
													via: zod.string().optional(),
												}),
											)
											.optional(),
									})
									.optional()
									.describe(
										'Contact represents an external messaging identity.',
									),
								id: zod.string().optional(),
								permissions: zod
									.object({
										can_add_members: zod.boolean().optional(),
										can_change_members_permissions: zod.boolean().optional(),
										can_change_thread_info: zod.boolean().optional(),
										can_delete_messages: zod.boolean().optional(),
										can_remove_members: zod.boolean().optional(),
										can_send_messages: zod.boolean().optional(),
										created_at: zod.string().optional(),
										id: zod.string().optional(),
										member_id: zod.string().optional(),
										updated_at: zod.string().optional(),
									})
									.optional(),
								role: zod
									.enum([
										'ROLE_UNSPECIFIED',
										'ROLE_MEMBER',
										'ROLE_ADMIN',
										'ROLE_OWNER',
										'ROLE_SUPERVISOR',
									])
									.default(
										messageHistorySearchThreadMessagesHistoryResponseItemsItemSenderRoleDefault,
									),
							})
							.optional()
							.describe('Sender user aggregated information.'),
						statuses: zod
							.array(
								zod
									.object({
										delivered_at: zod
											.string()
											.optional()
											.describe(
												'Unix time in milliseconds; zero when not reached.',
											),
										error: zod
											.string()
											.optional()
											.describe(
												'JSON-encoded provider error details for FAILED.',
											),
										failed_at: zod.string().optional(),
										member_id: zod
											.string()
											.optional()
											.describe('Recipient contact id.'),
										read_at: zod.string().optional(),
										status: zod
											.enum([
												'MESSAGE_DELIVERY_STATUS_UNSPECIFIED',
												'MESSAGE_DELIVERY_STATUS_SENT',
												'MESSAGE_DELIVERY_STATUS_DELIVERED',
												'MESSAGE_DELIVERY_STATUS_READ',
												'MESSAGE_DELIVERY_STATUS_FAILED',
											])
											.default(
												messageHistorySearchThreadMessagesHistoryResponseItemsItemStatusesItemStatusDefault,
											)
											.describe(
												'MessageDeliveryStatus is a per-recipient delivery state of a message.\nTransitions are monotonic: SENT -> DELIVERED -> READ.\nFAILED is terminal but may be superseded by a later DELIVERED (retry).\n\n - MESSAGE_DELIVERY_STATUS_SENT: Accepted by the system and queued for delivery.\n - MESSAGE_DELIVERY_STATUS_DELIVERED: Reached the recipient (stream ACK, push, provider receipt, bot dispatch).\n - MESSAGE_DELIVERY_STATUS_READ: Read by the recipient. Not applicable to bots.\n - MESSAGE_DELIVERY_STATUS_FAILED: Delivery failed (provider rejected, invalid contact, channel restriction).',
											),
										via: zod
											.string()
											.optional()
											.describe('Confirmation source: ws|push|provider|bot.'),
									})
									.describe(
										'MessageRecipientStatus is a per-recipient delivery state of a message.',
									),
							)
							.optional()
							.describe('Per-recipient delivery details.'),
						system: zod
							.object({
								message_id: zod
									.string()
									.optional()
									.describe(
										'ID of message for which system messages is binded.',
									),
								metadata: zod
									.looseObject({})
									.optional()
									.describe(
										'Represents additional metadata binded into system  message.',
									),
								type: zod
									.string()
									.optional()
									.describe('Represents type of the message.'),
							})
							.optional()
							.describe('System message content.'),
						thread_id: zod
							.string()
							.optional()
							.describe('Identifier of the thread the message belongs to.'),
						type: zod.int().optional().describe('Message type identifier.'),
					})
					.describe(
						'HistoryMessage represents a single message\nin thread history.',
					),
			)
			.optional()
			.describe('List of messages matching the search criteria.'),
		next_cursor: zod
			.object({
				id: zod
					.string()
					.optional()
					.describe('Unique identifier last message where cursor stopped.'),
			})
			.optional()
			.describe(
				"Cursor that represents position to get older messages (used without 'before' param).",
			),
		prev_cursor: zod
			.object({
				id: zod
					.string()
					.optional()
					.describe('Unique identifier last message where cursor stopped.'),
			})
			.optional()
			.describe(
				"Cursor that represents position to get newest messages (used with 'before' param).",
			),
	})
	.describe(
		'SearchMessageHistoryResponse contains\nmessage history search results and pagination metadata.',
	);
