/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import axios from '../../api/axios/genClient';

import type {
	ListFilesAttachmentsParams,
	WebitelKbFile,
	WebitelKbFileList,
} from '../_models';

// --- header start
//

export const // --- title start
	getAttachments =
		// --- title end
		(axiosInstance: AxiosInstance = axios) => {
			// --- header end
			/**
			 * @summary ListFiles returns the files attached to an article.
			 */
			const listFilesAttachments = (
				articleEtag: string,
				params?: ListFilesAttachmentsParams,
				options?: AxiosRequestConfig,
			): Promise<AxiosResponse<WebitelKbFileList>> => {
				return axiosInstance.get(`/v1/kb/articles/${articleEtag}/files`, {
					...options,
					params: {
						...params,
						...options?.params,
					},
				});
			};
			/**
			 * @summary DeleteFile unbinds and removes a file from an article.
			 */
			const deleteFileAttachments = (
				articleEtag: string,
				id: string,
				options?: AxiosRequestConfig,
			): Promise<AxiosResponse<WebitelKbFile>> => {
				return axiosInstance.delete(
					`/v1/kb/articles/${articleEtag}/files/${id}`,
					options,
				);
			};

			// --- footer start
			return {
				listFilesAttachments,
				deleteFileAttachments,
			};
		};
export type ListFilesAttachmentsResult = AxiosResponse<WebitelKbFileList>;
export type DeleteFileAttachmentsResult = AxiosResponse<WebitelKbFile>;

// --- footer end
