/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

export const ShiftTemplateServiceSearchShiftTemplateQueryParams = zod.object({
	q: zod.string().optional(),
	page: zod.int().optional(),
	size: zod.int().optional(),
	sort: zod.string().optional(),
	fields: zod.array(zod.string()).optional(),
});

export const ShiftTemplateServiceSearchShiftTemplateResponse = zod.object({
	items: zod
		.array(
			zod.object({
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				description: zod.string().optional(),
				domain_id: zod.string().optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				times: zod
					.array(
						zod.object({
							end: zod.int().optional(),
							start: zod.int().optional(),
						}),
					)
					.optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});

export const ShiftTemplateServiceCreateShiftTemplateBody = zod.object({
	item: zod
		.object({
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			description: zod.string().optional(),
			domain_id: zod.string().optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			times: zod
				.array(
					zod.object({
						end: zod.int().optional(),
						start: zod.int().optional(),
					}),
				)
				.optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});

export const ShiftTemplateServiceCreateShiftTemplateResponse = zod.object({
	item: zod
		.object({
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			description: zod.string().optional(),
			domain_id: zod.string().optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			times: zod
				.array(
					zod.object({
						end: zod.int().optional(),
						start: zod.int().optional(),
					}),
				)
				.optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});

export const ShiftTemplateServiceDeleteShiftTemplateParams = zod.object({
	id: zod.string(),
});

export const ShiftTemplateServiceDeleteShiftTemplateResponse = zod.object({
	id: zod.string().optional(),
});

export const ShiftTemplateServiceReadShiftTemplateParams = zod.object({
	id: zod.string(),
});

export const ShiftTemplateServiceReadShiftTemplateQueryParams = zod.object({
	fields: zod.array(zod.string()).optional(),
});

export const ShiftTemplateServiceReadShiftTemplateResponse = zod.object({
	item: zod
		.object({
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			description: zod.string().optional(),
			domain_id: zod.string().optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			times: zod
				.array(
					zod.object({
						end: zod.int().optional(),
						start: zod.int().optional(),
					}),
				)
				.optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});

/**
 * @summary UpdateShiftTemplate updates a shift template with a list times.
Update existing time, create that not exists in database and delete that not exists in the list.
 */
export const ShiftTemplateServiceUpdateShiftTemplateParams = zod.object({
	'item.id': zod.string(),
});

export const ShiftTemplateServiceUpdateShiftTemplateBody = zod.object({
	item: zod
		.object({
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			description: zod.string().optional(),
			domain_id: zod.string().optional(),
			name: zod.string().optional(),
			times: zod
				.array(
					zod.object({
						end: zod.int().optional(),
						start: zod.int().optional(),
					}),
				)
				.optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});

export const ShiftTemplateServiceUpdateShiftTemplateResponse = zod.object({
	item: zod
		.object({
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			description: zod.string().optional(),
			domain_id: zod.string().optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			times: zod
				.array(
					zod.object({
						end: zod.int().optional(),
						start: zod.int().optional(),
					}),
				)
				.optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});
