/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import axios from '../../api/axios/genClient';

import type {
	KnowledgebaseTagsList,
	ListTagsParams,
	SuggestTagsParams,
	WebitelKbSuggestTagsResponse,
} from '../_models';

// --- header start
//

export const // --- title start
	getTags =
		// --- title end
		(axiosInstance: AxiosInstance = axios) => {
			// --- header end
			/**
			 * @summary List of the all Articles's Tag(s).
			 */
			const listTags = (
				params?: ListTagsParams,
				options?: AxiosRequestConfig,
			): Promise<AxiosResponse<KnowledgebaseTagsList>> => {
				return axiosInstance.get(`/spaces/tags`, {
					...options,
					params: {
						...params,
						...options?.params,
					},
				});
			};
			/**
			 * @summary SuggestTags returns existing tags in a space matching a prefix.
			 */
			const suggestTags = (
				spaceId: string,
				params?: SuggestTagsParams,
				options?: AxiosRequestConfig,
			): Promise<AxiosResponse<WebitelKbSuggestTagsResponse>> => {
				return axiosInstance.get(`/v1/kb/spaces/${spaceId}/tags`, {
					...options,
					params: {
						...params,
						...options?.params,
					},
				});
			};

			// --- footer start
			return {
				listTags,
				suggestTags,
			};
		};
export type ListTagsResult = AxiosResponse<KnowledgebaseTagsList>;
export type SuggestTagsResult = AxiosResponse<WebitelKbSuggestTagsResponse>;

// --- footer end
