/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

/**
 * @summary List of the all Articles's Tag(s).
 */
export const ListTagsQueryParams = zod.object({
	page: zod.int().optional(),
	size: zod.int().optional(),
});

export const ListTagsResponse = zod.object({
	data: zod
		.array(
			zod.object({
				name: zod.string().optional().describe('The name of the tag.'),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
	page: zod.int().optional(),
});

/**
 * @summary SuggestTags returns existing tags in a space matching a prefix.
 */
export const SuggestTagsParams = zod.object({
	space_id: zod.string().describe('Space to read tags from.'),
});

export const SuggestTagsQueryParams = zod.object({
	q: zod.string().optional().describe('Prefix to match.'),
	size: zod.int().optional().describe('Maximum number of suggestions.'),
});

export const SuggestTagsResponse = zod
	.object({
		tags: zod.array(zod.string()).optional().describe('Matching tags.'),
	})
	.describe('SuggestTagsResponse returns matching tags.');
