/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

/**
 * @summary rpc GetCertificate(CertificateUsageRequest) returns (CertificateUsageResponse) {}
 */
export const GetCustomerQueryParams = zod.object({
	id: zod
		.string()
		.optional()
		.describe('Available Filters\n\nshow by customer id; serial number (uuid)'),
	valid: zod.boolean().optional().describe('show if valid only!'),
	'domain.id': zod.string().optional().describe('identifier'),
	'domain.name': zod.string().optional().describe('display name'),
	fields: zod
		.array(zod.string())
		.optional()
		.describe('Request Controls\n\nserial,'),
	sort: zod.array(zod.string()).optional(),
});

export const GetCustomerResponse = zod.object({
	customer: zod
		.object({
			created_at: zod.string().optional().describe('local created ms'),
			dnsrv: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			id: zod.string().optional(),
			issued_at: zod
				.string()
				.optional()
				.describe('[required] issuer(CA) created at'),
			license: zod
				.array(
					zod.object({
						competitive: zod.boolean().optional(),
						id: zod.string().optional(),
						limit: zod.int().optional(),
						name: zod.string().optional(),
						not_after: zod.string().optional(),
						not_before: zod.string().optional(),
						product: zod.string().optional(),
						remain: zod.int().optional().describe('available'),
						scope: zod
							.array(zod.string())
							.optional()
							.describe(
								"list of known classes, &this product grants mandatory access to, e.g.: 'users', 'roles', 'cc_agent', 'calendars', ...",
							),
						status: zod
							.object({
								errors: zod.array(zod.string()).optional(),
								notify: zod.array(zod.string()).optional(),
							})
							.optional(),
						users: zod
							.array(
								zod.object({
									expires_at: zod.string().optional(),
									id: zod.string().optional(),
									issued_at: zod.string().optional(),
									name: zod.string().optional(),
									prod: zod.string().optional(),
									scope: zod.array(zod.string()).optional(),
									user: zod
										.object({
											id: zod.string().optional(),
											name: zod.string().optional(),
										})
										.optional(),
								}),
							)
							.optional(),
					}),
				)
				.optional()
				.describe('grants issued'),
			limit: zod
				.record(zod.string(), zod.int())
				.optional()
				.describe('defines map[class]limit usage'),
			next_update: zod.string().optional(),
			not_after: zod.string().optional(),
			not_before: zod.string().optional(),
			organization: zod.string().optional(),
			revoked_at: zod.string().optional(),
			this_update: zod
				.string()
				.optional()
				.describe('[optional]: issuer(CA) signed at'),
			updated_at: zod.string().optional(),
			verify: zod
				.object({
					errors: zod.array(zod.string()).optional(),
					notify: zod.array(zod.string()).optional(),
				})
				.optional()
				.describe('[optional] validation results'),
		})
		.optional(),
});

export const UpdateCustomerQueryParams = zod.object({
	organization: zod
		.string()
		.optional()
		.describe('[optional] e.g.: Example Org.'),
	logo_picture: zod
		.string()
		.optional()
		.describe('[optional] logo source image'),
	certificate: zod
		.string()
		.optional()
		.describe(
			'[optional] raw bytes protobuf::base64.RawStdEncoding != certificate::base64.StdEncoding',
		),
	revoke: zod.boolean().optional(),
});

export const UpdateCustomerResponse = zod.object({
	customer: zod
		.object({
			created_at: zod.string().optional().describe('local created ms'),
			dnsrv: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			id: zod.string().optional(),
			issued_at: zod
				.string()
				.optional()
				.describe('[required] issuer(CA) created at'),
			license: zod
				.array(
					zod.object({
						competitive: zod.boolean().optional(),
						id: zod.string().optional(),
						limit: zod.int().optional(),
						name: zod.string().optional(),
						not_after: zod.string().optional(),
						not_before: zod.string().optional(),
						product: zod.string().optional(),
						remain: zod.int().optional().describe('available'),
						scope: zod
							.array(zod.string())
							.optional()
							.describe(
								"list of known classes, &this product grants mandatory access to, e.g.: 'users', 'roles', 'cc_agent', 'calendars', ...",
							),
						status: zod
							.object({
								errors: zod.array(zod.string()).optional(),
								notify: zod.array(zod.string()).optional(),
							})
							.optional(),
						users: zod
							.array(
								zod.object({
									expires_at: zod.string().optional(),
									id: zod.string().optional(),
									issued_at: zod.string().optional(),
									name: zod.string().optional(),
									prod: zod.string().optional(),
									scope: zod.array(zod.string()).optional(),
									user: zod
										.object({
											id: zod.string().optional(),
											name: zod.string().optional(),
										})
										.optional(),
								}),
							)
							.optional(),
					}),
				)
				.optional()
				.describe('grants issued'),
			limit: zod
				.record(zod.string(), zod.int())
				.optional()
				.describe('defines map[class]limit usage'),
			next_update: zod.string().optional(),
			not_after: zod.string().optional(),
			not_before: zod.string().optional(),
			organization: zod.string().optional(),
			revoked_at: zod.string().optional(),
			this_update: zod
				.string()
				.optional()
				.describe('[optional]: issuer(CA) signed at'),
			updated_at: zod.string().optional(),
			verify: zod
				.object({
					errors: zod.array(zod.string()).optional(),
					notify: zod.array(zod.string()).optional(),
				})
				.optional()
				.describe('[optional] validation results'),
		})
		.optional(),
});

export const LicenseUsageParams = zod.object({
	customer_id: zod.string(),
});

export const LicenseUsageQueryParams = zod.object({
	size: zod
		.int()
		.optional()
		.describe('----- Search Options ----- //\n\ndefault: 16'),
	page: zod.int().optional().describe('default: 1'),
	fields: zod.array(zod.string()).optional().describe('set of output fields'),
	sort: zod
		.array(zod.string())
		.optional()
		.describe('e.g.: "updated_at" - ASC; "!updated_at" - DESC;'),
	'user.id': zod.string().optional().describe('identifier'),
	'user.name': zod.string().optional().describe('display name'),
	'domain.id': zod.string().optional().describe('identifier'),
	'domain.name': zod.string().optional().describe('display name'),
	id: zod.array(zod.string()).optional().describe('by serial number(s)'),
	product: zod.array(zod.string()).optional().describe('by product name(s)'),
	valid: zod
		.boolean()
		.optional()
		.describe('view: all|valid|grantable\n\nshow: available to be granted'),
	q: zod.string().optional().describe('filter: term of search'),
});

export const LicenseUsageResponse = zod.object({
	items: zod
		.array(
			zod.object({
				competitive: zod.boolean().optional(),
				id: zod.string().optional(),
				limit: zod.int().optional(),
				name: zod.string().optional(),
				not_after: zod.string().optional(),
				not_before: zod.string().optional(),
				product: zod.string().optional(),
				remain: zod.int().optional().describe('available'),
				scope: zod
					.array(zod.string())
					.optional()
					.describe(
						"list of known classes, &this product grants mandatory access to, e.g.: 'users', 'roles', 'cc_agent', 'calendars', ...",
					),
				status: zod
					.object({
						errors: zod.array(zod.string()).optional(),
						notify: zod.array(zod.string()).optional(),
					})
					.optional(),
				users: zod
					.array(
						zod.object({
							expires_at: zod.string().optional(),
							id: zod.string().optional(),
							issued_at: zod.string().optional(),
							name: zod.string().optional(),
							prod: zod.string().optional(),
							scope: zod.array(zod.string()).optional(),
							user: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								})
								.optional(),
						}),
					)
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
	page: zod.int().optional().describe('this page number !'),
});

/**
 * @summary rpc GetCertificate(CertificateUsageRequest) returns (CertificateUsageResponse) {}
 */
export const GetCustomer2Params = zod.object({
	id: zod
		.string()
		.describe('Available Filters\n\nshow by customer id; serial number (uuid)'),
});

export const GetCustomer2QueryParams = zod.object({
	valid: zod.boolean().optional().describe('show if valid only!'),
	'domain.id': zod.string().optional().describe('identifier'),
	'domain.name': zod.string().optional().describe('display name'),
	fields: zod
		.array(zod.string())
		.optional()
		.describe('Request Controls\n\nserial,'),
	sort: zod.array(zod.string()).optional(),
});

export const GetCustomer2Response = zod.object({
	customer: zod
		.object({
			created_at: zod.string().optional().describe('local created ms'),
			dnsrv: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			id: zod.string().optional(),
			issued_at: zod
				.string()
				.optional()
				.describe('[required] issuer(CA) created at'),
			license: zod
				.array(
					zod.object({
						competitive: zod.boolean().optional(),
						id: zod.string().optional(),
						limit: zod.int().optional(),
						name: zod.string().optional(),
						not_after: zod.string().optional(),
						not_before: zod.string().optional(),
						product: zod.string().optional(),
						remain: zod.int().optional().describe('available'),
						scope: zod
							.array(zod.string())
							.optional()
							.describe(
								"list of known classes, &this product grants mandatory access to, e.g.: 'users', 'roles', 'cc_agent', 'calendars', ...",
							),
						status: zod
							.object({
								errors: zod.array(zod.string()).optional(),
								notify: zod.array(zod.string()).optional(),
							})
							.optional(),
						users: zod
							.array(
								zod.object({
									expires_at: zod.string().optional(),
									id: zod.string().optional(),
									issued_at: zod.string().optional(),
									name: zod.string().optional(),
									prod: zod.string().optional(),
									scope: zod.array(zod.string()).optional(),
									user: zod
										.object({
											id: zod.string().optional(),
											name: zod.string().optional(),
										})
										.optional(),
								}),
							)
							.optional(),
					}),
				)
				.optional()
				.describe('grants issued'),
			limit: zod
				.record(zod.string(), zod.int())
				.optional()
				.describe('defines map[class]limit usage'),
			next_update: zod.string().optional(),
			not_after: zod.string().optional(),
			not_before: zod.string().optional(),
			organization: zod.string().optional(),
			revoked_at: zod.string().optional(),
			this_update: zod
				.string()
				.optional()
				.describe('[optional]: issuer(CA) signed at'),
			updated_at: zod.string().optional(),
			verify: zod
				.object({
					errors: zod.array(zod.string()).optional(),
					notify: zod.array(zod.string()).optional(),
				})
				.optional()
				.describe('[optional] validation results'),
		})
		.optional(),
});

export const LicenseUsage2QueryParams = zod.object({
	size: zod
		.int()
		.optional()
		.describe('----- Search Options ----- //\n\ndefault: 16'),
	page: zod.int().optional().describe('default: 1'),
	fields: zod.array(zod.string()).optional().describe('set of output fields'),
	sort: zod
		.array(zod.string())
		.optional()
		.describe('e.g.: "updated_at" - ASC; "!updated_at" - DESC;'),
	'user.id': zod.string().optional().describe('identifier'),
	'user.name': zod.string().optional().describe('display name'),
	'domain.id': zod.string().optional().describe('identifier'),
	'domain.name': zod.string().optional().describe('display name'),
	customer_id: zod.string().optional(),
	id: zod.array(zod.string()).optional().describe('by serial number(s)'),
	product: zod.array(zod.string()).optional().describe('by product name(s)'),
	valid: zod
		.boolean()
		.optional()
		.describe('view: all|valid|grantable\n\nshow: available to be granted'),
	q: zod.string().optional().describe('filter: term of search'),
});

export const LicenseUsage2Response = zod.object({
	items: zod
		.array(
			zod.object({
				competitive: zod.boolean().optional(),
				id: zod.string().optional(),
				limit: zod.int().optional(),
				name: zod.string().optional(),
				not_after: zod.string().optional(),
				not_before: zod.string().optional(),
				product: zod.string().optional(),
				remain: zod.int().optional().describe('available'),
				scope: zod
					.array(zod.string())
					.optional()
					.describe(
						"list of known classes, &this product grants mandatory access to, e.g.: 'users', 'roles', 'cc_agent', 'calendars', ...",
					),
				status: zod
					.object({
						errors: zod.array(zod.string()).optional(),
						notify: zod.array(zod.string()).optional(),
					})
					.optional(),
				users: zod
					.array(
						zod.object({
							expires_at: zod.string().optional(),
							id: zod.string().optional(),
							issued_at: zod.string().optional(),
							name: zod.string().optional(),
							prod: zod.string().optional(),
							scope: zod.array(zod.string()).optional(),
							user: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								})
								.optional(),
						}),
					)
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
	page: zod.int().optional().describe('this page number !'),
});

export const LicenseUsage3QueryParams = zod.object({
	size: zod
		.int()
		.optional()
		.describe('----- Search Options ----- //\n\ndefault: 16'),
	page: zod.int().optional().describe('default: 1'),
	fields: zod.array(zod.string()).optional().describe('set of output fields'),
	sort: zod
		.array(zod.string())
		.optional()
		.describe('e.g.: "updated_at" - ASC; "!updated_at" - DESC;'),
	'user.id': zod.string().optional().describe('identifier'),
	'user.name': zod.string().optional().describe('display name'),
	'domain.id': zod.string().optional().describe('identifier'),
	'domain.name': zod.string().optional().describe('display name'),
	customer_id: zod.string().optional(),
	id: zod.array(zod.string()).optional().describe('by serial number(s)'),
	product: zod.array(zod.string()).optional().describe('by product name(s)'),
	valid: zod
		.boolean()
		.optional()
		.describe('view: all|valid|grantable\n\nshow: available to be granted'),
	q: zod.string().optional().describe('filter: term of search'),
});

export const LicenseUsage3Response = zod.object({
	items: zod
		.array(
			zod.object({
				competitive: zod.boolean().optional(),
				id: zod.string().optional(),
				limit: zod.int().optional(),
				name: zod.string().optional(),
				not_after: zod.string().optional(),
				not_before: zod.string().optional(),
				product: zod.string().optional(),
				remain: zod.int().optional().describe('available'),
				scope: zod
					.array(zod.string())
					.optional()
					.describe(
						"list of known classes, &this product grants mandatory access to, e.g.: 'users', 'roles', 'cc_agent', 'calendars', ...",
					),
				status: zod
					.object({
						errors: zod.array(zod.string()).optional(),
						notify: zod.array(zod.string()).optional(),
					})
					.optional(),
				users: zod
					.array(
						zod.object({
							expires_at: zod.string().optional(),
							id: zod.string().optional(),
							issued_at: zod.string().optional(),
							name: zod.string().optional(),
							prod: zod.string().optional(),
							scope: zod.array(zod.string()).optional(),
							user: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								})
								.optional(),
						}),
					)
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
	page: zod.int().optional().describe('this page number !'),
});

export const LicenseUsersParams = zod.object({
	id: zod
		.string()
		.describe('----- Search Filters ----- //\n\nREQUIRED Product ID'),
});

export const LicenseUsersQueryParams = zod.object({
	size: zod
		.int()
		.optional()
		.describe('----- Search Options ----- //\n\ndefault: 16'),
	page: zod.int().optional().describe('default: 1'),
	fields: zod.array(zod.string()).optional().describe('set of output fields'),
	sort: zod
		.array(zod.string())
		.optional()
		.describe('e.g.: "updated_at" - ASC; "!updated_at" - DESC;'),
	q: zod.string().optional().describe('filter: term of search (username)'),
});

export const LicenseUsersResponse = zod.object({
	items: zod
		.array(
			zod.object({
				domain: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				expires_at: zod.string().optional(),
				issued_at: zod.string().optional(),
				sessions: zod.int().optional(),
				user: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
	page: zod.int().optional().describe('this page number !'),
});

export const ServerInfoResponse = zod.object({
	key: zod.string().optional(),
});
