/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

/**
 * @summary SendViberBmTemplate sends an approved, business-initiated template message
for cold-start outreach (no open 24h session).
 */
export const ViberBmServiceSendViberBmTemplateWebitelImApiProviderV1ViberBmServiceParams =
	zod.object({
		gate_id: zod.string(),
	});

export const ViberBmServiceSendViberBmTemplateWebitelImApiProviderV1ViberBmServiceBody =
	zod.object({
		parameters: zod.record(zod.string(), zod.string()).optional(),
		language: zod.string().optional(),
		template_id: zod.string().optional(),
		to: zod.string().optional(),
	});

export const ViberBmServiceSendViberBmTemplateWebitelImApiProviderV1ViberBmServiceResponse =
	zod.object({
		bulk_id: zod.string().optional(),
		message_id: zod.string().optional(),
	});

export const ViberBmServiceDeleteViberBmWebitelImApiProviderV1ViberBmServiceParams =
	zod.object({
		id: zod.string(),
	});

export const viberBmServiceDeleteViberBmWebitelImApiProviderV1ViberBmServiceResponseItemStatusDefault = `PROVIDER_STATUS_UNSPECIFIED`;

export const ViberBmServiceDeleteViberBmWebitelImApiProviderV1ViberBmServiceResponse =
	zod.object({
		item: zod
			.object({
				base_url: zod.string().optional(),
				created_at: zod.string().optional(),
				enabled: zod.boolean().optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				sender_name: zod.string().optional(),
				status: zod
					.enum([
						'PROVIDER_STATUS_UNSPECIFIED',
						'PROVIDER_STATUS_ACTIVE',
						'PROVIDER_STATUS_INACTIVE',
						'PROVIDER_STATUS_ERROR',
					])
					.default(
						viberBmServiceDeleteViberBmWebitelImApiProviderV1ViberBmServiceResponseItemStatusDefault,
					)
					.describe(
						'/ ProviderStatus represents the operational state of a provider gateway.',
					),
				updated_at: zod.string().optional(),
				webhook_url: zod.string().optional(),
			})
			.optional(),
	});

export const ViberBmServiceGetViberBmWebitelImApiProviderV1ViberBmServiceParams =
	zod.object({
		id: zod.string(),
	});

export const viberBmServiceGetViberBmWebitelImApiProviderV1ViberBmServiceResponseItemStatusDefault = `PROVIDER_STATUS_UNSPECIFIED`;

export const ViberBmServiceGetViberBmWebitelImApiProviderV1ViberBmServiceResponse =
	zod.object({
		item: zod
			.object({
				base_url: zod.string().optional(),
				created_at: zod.string().optional(),
				enabled: zod.boolean().optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				sender_name: zod.string().optional(),
				status: zod
					.enum([
						'PROVIDER_STATUS_UNSPECIFIED',
						'PROVIDER_STATUS_ACTIVE',
						'PROVIDER_STATUS_INACTIVE',
						'PROVIDER_STATUS_ERROR',
					])
					.default(
						viberBmServiceGetViberBmWebitelImApiProviderV1ViberBmServiceResponseItemStatusDefault,
					)
					.describe(
						'/ ProviderStatus represents the operational state of a provider gateway.',
					),
				updated_at: zod.string().optional(),
				webhook_url: zod.string().optional(),
			})
			.optional(),
	});

export const ViberBmServiceUpdateViberBmWebitelImApiProviderV1ViberBmServiceParams =
	zod.object({
		id: zod.string(),
	});

export const ViberBmServiceUpdateViberBmWebitelImApiProviderV1ViberBmServiceBody =
	zod.object({
		api_key: zod.string().optional(),
		base_url: zod.string().optional(),
		enabled: zod.boolean().optional(),
		name: zod.string().optional(),
		peer: zod
			.object({
				iss: zod.string().optional(),
				sub: zod.string().optional(),
			})
			.optional(),
		sender_name: zod.string().optional(),
		webhook_secret: zod.string().optional(),
	});

export const viberBmServiceUpdateViberBmWebitelImApiProviderV1ViberBmServiceResponseItemStatusDefault = `PROVIDER_STATUS_UNSPECIFIED`;

export const ViberBmServiceUpdateViberBmWebitelImApiProviderV1ViberBmServiceResponse =
	zod.object({
		item: zod
			.object({
				base_url: zod.string().optional(),
				created_at: zod.string().optional(),
				enabled: zod.boolean().optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				sender_name: zod.string().optional(),
				status: zod
					.enum([
						'PROVIDER_STATUS_UNSPECIFIED',
						'PROVIDER_STATUS_ACTIVE',
						'PROVIDER_STATUS_INACTIVE',
						'PROVIDER_STATUS_ERROR',
					])
					.default(
						viberBmServiceUpdateViberBmWebitelImApiProviderV1ViberBmServiceResponseItemStatusDefault,
					)
					.describe(
						'/ ProviderStatus represents the operational state of a provider gateway.',
					),
				updated_at: zod.string().optional(),
				webhook_url: zod.string().optional(),
			})
			.optional(),
	});
