/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

/**
 * @summary List of List
 */
export const SearchListQueryParams = zod.object({
	page: zod.int().optional(),
	size: zod.int().optional(),
	q: zod.string().optional(),
	sort: zod.string().optional(),
	fields: zod.array(zod.string()).optional(),
	id: zod.array(zod.int()).optional(),
});

export const SearchListResponse = zod.object({
	items: zod
		.array(
			zod.object({
				count: zod.string().optional(),
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				description: zod.string().optional(),
				domain_id: zod.string().optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});

/**
 * @summary Create List
 */
export const CreateListBody = zod.object({
	description: zod.string().optional(),
	domain_id: zod.string().optional(),
	name: zod.string().optional(),
});

export const CreateListResponse = zod.object({
	count: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	domain_id: zod.string().optional(),
	id: zod.string().optional(),
	name: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary Remove list
 */
export const DeleteListParams = zod.object({
	id: zod.string(),
});

export const DeleteListQueryParams = zod.object({
	domain_id: zod.string().optional(),
});

export const DeleteListResponse = zod.object({
	count: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	domain_id: zod.string().optional(),
	id: zod.string().optional(),
	name: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary List item
 */
export const ReadListParams = zod.object({
	id: zod.string(),
});

export const ReadListQueryParams = zod.object({
	domain_id: zod.string().optional(),
});

export const ReadListResponse = zod.object({
	count: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	domain_id: zod.string().optional(),
	id: zod.string().optional(),
	name: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary Update list
 */
export const UpdateListParams = zod.object({
	id: zod.string(),
});

export const UpdateListBody = zod.object({
	description: zod.string().optional(),
	domain_id: zod.string().optional(),
	name: zod.string().optional(),
});

export const UpdateListResponse = zod.object({
	count: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	domain_id: zod.string().optional(),
	id: zod.string().optional(),
	name: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary List of List
 */
export const SearchListCommunicationParams = zod.object({
	list_id: zod.string(),
});

export const SearchListCommunicationQueryParams = zod.object({
	page: zod.int().optional(),
	size: zod.int().optional(),
	q: zod.string().optional(),
	sort: zod.string().optional(),
	fields: zod.array(zod.string()).optional(),
	id: zod.array(zod.int()).optional(),
	'expire_at.from': zod.string().optional(),
	'expire_at.to': zod.string().optional(),
});

export const SearchListCommunicationResponse = zod.object({
	items: zod
		.array(
			zod.object({
				description: zod.string().optional(),
				expire_at: zod.string().optional(),
				id: zod.string().optional(),
				list_id: zod.string().optional(),
				number: zod.string().optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});

/**
 * @summary Create ListCommunication
 */
export const CreateListCommunicationParams = zod.object({
	list_id: zod.string(),
});

export const CreateListCommunicationBody = zod.object({
	description: zod.string().optional(),
	expire_at: zod.string().optional(),
	number: zod.string().optional(),
});

export const CreateListCommunicationResponse = zod.object({
	description: zod.string().optional(),
	expire_at: zod.string().optional(),
	id: zod.string().optional(),
	list_id: zod.string().optional(),
	number: zod.string().optional(),
});

/**
 * @summary Remove ListCommunication
 */
export const DeleteListCommunicationParams = zod.object({
	list_id: zod.string(),
	id: zod.string(),
});

export const DeleteListCommunicationQueryParams = zod.object({
	domain_id: zod.string().optional(),
});

export const DeleteListCommunicationResponse = zod.object({
	description: zod.string().optional(),
	expire_at: zod.string().optional(),
	id: zod.string().optional(),
	list_id: zod.string().optional(),
	number: zod.string().optional(),
});

/**
 * @summary List item
 */
export const ReadListCommunicationParams = zod.object({
	list_id: zod.string(),
	id: zod.string(),
});

export const ReadListCommunicationQueryParams = zod.object({
	domain_id: zod.string().optional(),
});

export const ReadListCommunicationResponse = zod.object({
	description: zod.string().optional(),
	expire_at: zod.string().optional(),
	id: zod.string().optional(),
	list_id: zod.string().optional(),
	number: zod.string().optional(),
});

/**
 * @summary Update ListCommunication
 */
export const UpdateListCommunicationParams = zod.object({
	list_id: zod.string(),
	id: zod.string(),
});

export const UpdateListCommunicationBody = zod.object({
	description: zod.string().optional(),
	expire_at: zod.string().optional(),
	number: zod.string().optional(),
});

export const UpdateListCommunicationResponse = zod.object({
	description: zod.string().optional(),
	expire_at: zod.string().optional(),
	id: zod.string().optional(),
	list_id: zod.string().optional(),
	number: zod.string().optional(),
});
