/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import axios from '../../api/axios/genClient';

import type {
	ContactsEmptyResponse,
	ContactsIMClientList,
	ListIMClientsParams,
} from '../_models';

// --- header start
//

export const // --- title start
	getImclients =
		// --- title end
		(axiosInstance: AxiosInstance = axios) => {
			// --- header end
			/**
			 * @summary Search IM client links
			 */
			const listIMClients = (
				contactId: string,
				params?: ListIMClientsParams,
				options?: AxiosRequestConfig,
			): Promise<AxiosResponse<ContactsIMClientList>> => {
				return axiosInstance.get(`/contacts/${contactId}/imclients`, {
					...options,
					params: {
						...params,
						...options?.params,
					},
				});
			};
			const deleteIMClient = (
				contactId: string,
				id: string,
				options?: AxiosRequestConfig,
			): Promise<AxiosResponse<ContactsEmptyResponse>> => {
				return axiosInstance.delete(
					`/contacts/${contactId}/imclients/${id}`,
					options,
				);
			};

			// --- footer start
			return {
				listIMClients,
				deleteIMClient,
			};
		};
export type ListIMClientsResult = AxiosResponse<ContactsIMClientList>;
export type DeleteIMClientResult = AxiosResponse<ContactsEmptyResponse>;

// --- footer end
