/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

export const SearchChatTagParams = zod.object({
	team_id: zod.string(),
});

export const SearchChatTagQueryParams = zod.object({
	page: zod.int().optional(),
	size: zod.int().optional(),
	q: zod.string().optional(),
	sort: zod.string().optional(),
	fields: zod.array(zod.string()).optional(),
	id: zod.array(zod.int()).optional(),
});

export const SearchChatTagResponse = zod.object({
	items: zod
		.array(
			zod.object({
				id: zod.int().optional(),
				tag: zod.string().optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});

export const CreateChatTagParams = zod.object({
	team_id: zod.string(),
});

export const CreateChatTagBody = zod.object({
	tag: zod.string().optional(),
});

export const CreateChatTagResponse = zod.object({
	id: zod.int().optional(),
	tag: zod.string().optional(),
});

export const DeleteChatTagParams = zod.object({
	team_id: zod.string(),
	id: zod.int(),
});

export const DeleteChatTagResponse = zod.object({
	id: zod.int().optional(),
	tag: zod.string().optional(),
});

export const UpdateChatTagParams = zod.object({
	team_id: zod.string(),
	id: zod.int(),
});

export const UpdateChatTagBody = zod.object({
	tag: zod.string().optional(),
});

export const UpdateChatTagResponse = zod.object({
	id: zod.int().optional(),
	tag: zod.string().optional(),
});
