/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

export const SearchAuditFormQueryParams = zod.object({
	page: zod.int().optional(),
	size: zod.int().optional(),
	q: zod.string().optional(),
	sort: zod.string().optional(),
	fields: zod.array(zod.string()).optional(),
	id: zod.array(zod.int()).optional(),
	team_id: zod.array(zod.int()).optional(),
	enabled: zod.boolean().optional(),
	editable: zod
		.boolean()
		.optional()
		.describe('bool archive = 9;\n\nbool active = 11; // not archive'),
	question: zod.string().optional(),
	team_filter: zod
		.int()
		.optional()
		.describe("expects userID to filter by user's team"),
});

export const searchAuditFormResponseItemsItemQuestionsItemTypeDefault = `question_default`;

export const SearchAuditFormResponse = zod.object({
	items: zod
		.array(
			zod.object({
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				description: zod.string().optional(),
				editable: zod.boolean().optional(),
				enabled: zod.boolean().optional(),
				id: zod.int().optional(),
				name: zod.string().optional(),
				questions: zod
					.array(
						zod.object({
							critical_violation: zod.boolean().optional(),
							description: zod.string().optional(),
							max: zod.int().optional(),
							min: zod.int().optional(),
							options: zod
								.array(
									zod.object({
										name: zod.string().optional(),
										score: zod.number().optional(),
									}),
								)
								.optional(),
							question: zod.string().optional(),
							required: zod.boolean().optional(),
							type: zod
								.enum([
									'question_default',
									'question_score',
									'question_option',
									'question_yes',
								])
								.default(
									searchAuditFormResponseItemsItemQuestionsItemTypeDefault,
								),
						}),
					)
					.optional(),
				teams: zod
					.array(
						zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
					)
					.optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});

export const createAuditFormBodyQuestionsItemTypeDefault = `question_default`;

export const CreateAuditFormBody = zod.object({
	description: zod.string().optional(),
	enabled: zod.boolean().optional(),
	name: zod.string().optional(),
	questions: zod
		.array(
			zod.object({
				critical_violation: zod.boolean().optional(),
				description: zod.string().optional(),
				max: zod.int().optional(),
				min: zod.int().optional(),
				options: zod
					.array(
						zod.object({
							name: zod.string().optional(),
							score: zod.number().optional(),
						}),
					)
					.optional(),
				question: zod.string().optional(),
				required: zod.boolean().optional(),
				type: zod
					.enum([
						'question_default',
						'question_score',
						'question_option',
						'question_yes',
					])
					.default(createAuditFormBodyQuestionsItemTypeDefault),
			}),
		)
		.optional(),
	teams: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
});

export const createAuditFormResponseQuestionsItemTypeDefault = `question_default`;

export const CreateAuditFormResponse = zod.object({
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	editable: zod.boolean().optional(),
	enabled: zod.boolean().optional(),
	id: zod.int().optional(),
	name: zod.string().optional(),
	questions: zod
		.array(
			zod.object({
				critical_violation: zod.boolean().optional(),
				description: zod.string().optional(),
				max: zod.int().optional(),
				min: zod.int().optional(),
				options: zod
					.array(
						zod.object({
							name: zod.string().optional(),
							score: zod.number().optional(),
						}),
					)
					.optional(),
				question: zod.string().optional(),
				required: zod.boolean().optional(),
				type: zod
					.enum([
						'question_default',
						'question_score',
						'question_option',
						'question_yes',
					])
					.default(createAuditFormResponseQuestionsItemTypeDefault),
			}),
		)
		.optional(),
	teams: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const SearchAuditRateParams = zod.object({
	form_id: zod.int(),
});

export const SearchAuditRateQueryParams = zod.object({
	page: zod.int().optional(),
	size: zod.int().optional(),
	q: zod.string().optional(),
	sort: zod.string().optional(),
	fields: zod.array(zod.string()).optional(),
	'created_at.from': zod.string().optional(),
	'created_at.to': zod.string().optional(),
	id: zod.array(zod.int()).optional(),
	call_id: zod.array(zod.string()).optional(),
	rated_user: zod.array(zod.string()).optional(),
	conversation_id: zod.array(zod.string()).optional(),
});

export const searchAuditRateResponseItemsItemQuestionsItemTypeDefault = `question_default`;

export const SearchAuditRateResponse = zod.object({
	items: zod
		.array(
			zod.object({
				answers: zod
					.array(
						zod.object({
							comment: zod.string().optional(),
							score: zod.number().optional(),
							updated_at: zod.string().optional(),
							updated_by: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								})
								.optional(),
						}),
					)
					.optional(),
				comment: zod.string().optional(),
				conversation_id: zod.string().optional(),
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				critical_count: zod.string().optional(),
				form: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				id: zod.string().optional(),
				questions: zod
					.array(
						zod.object({
							critical_violation: zod.boolean().optional(),
							description: zod.string().optional(),
							max: zod.int().optional(),
							min: zod.int().optional(),
							options: zod
								.array(
									zod.object({
										name: zod.string().optional(),
										score: zod.number().optional(),
									}),
								)
								.optional(),
							question: zod.string().optional(),
							required: zod.boolean().optional(),
							type: zod
								.enum([
									'question_default',
									'question_score',
									'question_option',
									'question_yes',
								])
								.default(
									searchAuditRateResponseItemsItemQuestionsItemTypeDefault,
								),
						}),
					)
					.optional(),
				rated_user: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				score_optional: zod.number().optional(),
				score_required: zod.number().optional(),
				select_yes_count: zod.string().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});

export const DeleteAuditFormParams = zod.object({
	id: zod.int(),
});

export const deleteAuditFormResponseQuestionsItemTypeDefault = `question_default`;

export const DeleteAuditFormResponse = zod.object({
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	editable: zod.boolean().optional(),
	enabled: zod.boolean().optional(),
	id: zod.int().optional(),
	name: zod.string().optional(),
	questions: zod
		.array(
			zod.object({
				critical_violation: zod.boolean().optional(),
				description: zod.string().optional(),
				max: zod.int().optional(),
				min: zod.int().optional(),
				options: zod
					.array(
						zod.object({
							name: zod.string().optional(),
							score: zod.number().optional(),
						}),
					)
					.optional(),
				question: zod.string().optional(),
				required: zod.boolean().optional(),
				type: zod
					.enum([
						'question_default',
						'question_score',
						'question_option',
						'question_yes',
					])
					.default(deleteAuditFormResponseQuestionsItemTypeDefault),
			}),
		)
		.optional(),
	teams: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const ReadAuditFormParams = zod.object({
	id: zod.int(),
});

export const readAuditFormResponseQuestionsItemTypeDefault = `question_default`;

export const ReadAuditFormResponse = zod.object({
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	editable: zod.boolean().optional(),
	enabled: zod.boolean().optional(),
	id: zod.int().optional(),
	name: zod.string().optional(),
	questions: zod
		.array(
			zod.object({
				critical_violation: zod.boolean().optional(),
				description: zod.string().optional(),
				max: zod.int().optional(),
				min: zod.int().optional(),
				options: zod
					.array(
						zod.object({
							name: zod.string().optional(),
							score: zod.number().optional(),
						}),
					)
					.optional(),
				question: zod.string().optional(),
				required: zod.boolean().optional(),
				type: zod
					.enum([
						'question_default',
						'question_score',
						'question_option',
						'question_yes',
					])
					.default(readAuditFormResponseQuestionsItemTypeDefault),
			}),
		)
		.optional(),
	teams: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const PatchAuditFormParams = zod.object({
	id: zod.int(),
});

export const patchAuditFormBodyQuestionsItemTypeDefault = `question_default`;

export const PatchAuditFormBody = zod.object({
	description: zod.string().optional(),
	enabled: zod.boolean().optional(),
	fields: zod.array(zod.string()).optional(),
	name: zod.string().optional(),
	questions: zod
		.array(
			zod.object({
				critical_violation: zod.boolean().optional(),
				description: zod.string().optional(),
				max: zod.int().optional(),
				min: zod.int().optional(),
				options: zod
					.array(
						zod.object({
							name: zod.string().optional(),
							score: zod.number().optional(),
						}),
					)
					.optional(),
				question: zod.string().optional(),
				required: zod.boolean().optional(),
				type: zod
					.enum([
						'question_default',
						'question_score',
						'question_option',
						'question_yes',
					])
					.default(patchAuditFormBodyQuestionsItemTypeDefault),
			}),
		)
		.optional(),
	teams: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
});

export const patchAuditFormResponseQuestionsItemTypeDefault = `question_default`;

export const PatchAuditFormResponse = zod.object({
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	editable: zod.boolean().optional(),
	enabled: zod.boolean().optional(),
	id: zod.int().optional(),
	name: zod.string().optional(),
	questions: zod
		.array(
			zod.object({
				critical_violation: zod.boolean().optional(),
				description: zod.string().optional(),
				max: zod.int().optional(),
				min: zod.int().optional(),
				options: zod
					.array(
						zod.object({
							name: zod.string().optional(),
							score: zod.number().optional(),
						}),
					)
					.optional(),
				question: zod.string().optional(),
				required: zod.boolean().optional(),
				type: zod
					.enum([
						'question_default',
						'question_score',
						'question_option',
						'question_yes',
					])
					.default(patchAuditFormResponseQuestionsItemTypeDefault),
			}),
		)
		.optional(),
	teams: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const UpdateAuditFormParams = zod.object({
	id: zod.int(),
});

export const updateAuditFormBodyQuestionsItemTypeDefault = `question_default`;

export const UpdateAuditFormBody = zod.object({
	description: zod.string().optional(),
	enabled: zod.boolean().optional(),
	name: zod.string().optional(),
	questions: zod
		.array(
			zod.object({
				critical_violation: zod.boolean().optional(),
				description: zod.string().optional(),
				max: zod.int().optional(),
				min: zod.int().optional(),
				options: zod
					.array(
						zod.object({
							name: zod.string().optional(),
							score: zod.number().optional(),
						}),
					)
					.optional(),
				question: zod.string().optional(),
				required: zod.boolean().optional(),
				type: zod
					.enum([
						'question_default',
						'question_score',
						'question_option',
						'question_yes',
					])
					.default(updateAuditFormBodyQuestionsItemTypeDefault),
			}),
		)
		.optional(),
	teams: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
});

export const updateAuditFormResponseQuestionsItemTypeDefault = `question_default`;

export const UpdateAuditFormResponse = zod.object({
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	editable: zod.boolean().optional(),
	enabled: zod.boolean().optional(),
	id: zod.int().optional(),
	name: zod.string().optional(),
	questions: zod
		.array(
			zod.object({
				critical_violation: zod.boolean().optional(),
				description: zod.string().optional(),
				max: zod.int().optional(),
				min: zod.int().optional(),
				options: zod
					.array(
						zod.object({
							name: zod.string().optional(),
							score: zod.number().optional(),
						}),
					)
					.optional(),
				question: zod.string().optional(),
				required: zod.boolean().optional(),
				type: zod
					.enum([
						'question_default',
						'question_score',
						'question_option',
						'question_yes',
					])
					.default(updateAuditFormResponseQuestionsItemTypeDefault),
			}),
		)
		.optional(),
	teams: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const CreateAuditFormRateBody = zod.object({
	answers: zod
		.array(
			zod.object({
				score: zod.number().optional(),
			}),
		)
		.optional(),
	call_id: zod.string().optional(),
	comment: zod.string().optional(),
	conversation_id: zod.string().optional(),
	form: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const createAuditFormRateResponseQuestionsItemTypeDefault = `question_default`;

export const CreateAuditFormRateResponse = zod.object({
	answers: zod
		.array(
			zod.object({
				comment: zod.string().optional(),
				score: zod.number().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	comment: zod.string().optional(),
	conversation_id: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	critical_count: zod.string().optional(),
	form: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	id: zod.string().optional(),
	questions: zod
		.array(
			zod.object({
				critical_violation: zod.boolean().optional(),
				description: zod.string().optional(),
				max: zod.int().optional(),
				min: zod.int().optional(),
				options: zod
					.array(
						zod.object({
							name: zod.string().optional(),
							score: zod.number().optional(),
						}),
					)
					.optional(),
				question: zod.string().optional(),
				required: zod.boolean().optional(),
				type: zod
					.enum([
						'question_default',
						'question_score',
						'question_option',
						'question_yes',
					])
					.default(createAuditFormRateResponseQuestionsItemTypeDefault),
			}),
		)
		.optional(),
	rated_user: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	score_optional: zod.number().optional(),
	score_required: zod.number().optional(),
	select_yes_count: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const DeleteAuditRateParams = zod.object({
	id: zod.string(),
});

export const deleteAuditRateResponseQuestionsItemTypeDefault = `question_default`;

export const DeleteAuditRateResponse = zod.object({
	answers: zod
		.array(
			zod.object({
				comment: zod.string().optional(),
				score: zod.number().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	comment: zod.string().optional(),
	conversation_id: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	critical_count: zod.string().optional(),
	form: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	id: zod.string().optional(),
	questions: zod
		.array(
			zod.object({
				critical_violation: zod.boolean().optional(),
				description: zod.string().optional(),
				max: zod.int().optional(),
				min: zod.int().optional(),
				options: zod
					.array(
						zod.object({
							name: zod.string().optional(),
							score: zod.number().optional(),
						}),
					)
					.optional(),
				question: zod.string().optional(),
				required: zod.boolean().optional(),
				type: zod
					.enum([
						'question_default',
						'question_score',
						'question_option',
						'question_yes',
					])
					.default(deleteAuditRateResponseQuestionsItemTypeDefault),
			}),
		)
		.optional(),
	rated_user: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	score_optional: zod.number().optional(),
	score_required: zod.number().optional(),
	select_yes_count: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const ReadAuditRateParams = zod.object({
	id: zod.string(),
});

export const readAuditRateResponseQuestionsItemTypeDefault = `question_default`;

export const ReadAuditRateResponse = zod.object({
	answers: zod
		.array(
			zod.object({
				comment: zod.string().optional(),
				score: zod.number().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	comment: zod.string().optional(),
	conversation_id: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	critical_count: zod.string().optional(),
	form: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	id: zod.string().optional(),
	questions: zod
		.array(
			zod.object({
				critical_violation: zod.boolean().optional(),
				description: zod.string().optional(),
				max: zod.int().optional(),
				min: zod.int().optional(),
				options: zod
					.array(
						zod.object({
							name: zod.string().optional(),
							score: zod.number().optional(),
						}),
					)
					.optional(),
				question: zod.string().optional(),
				required: zod.boolean().optional(),
				type: zod
					.enum([
						'question_default',
						'question_score',
						'question_option',
						'question_yes',
					])
					.default(readAuditRateResponseQuestionsItemTypeDefault),
			}),
		)
		.optional(),
	rated_user: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	score_optional: zod.number().optional(),
	score_required: zod.number().optional(),
	select_yes_count: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const UpdateAuditRateParams = zod.object({
	id: zod.string(),
});

export const UpdateAuditRateBody = zod.object({
	answers: zod
		.array(
			zod.object({
				comment: zod.string().optional(),
				score: zod.number().optional(),
			}),
		)
		.optional(),
	comment: zod.string().optional(),
});

export const updateAuditRateResponseQuestionsItemTypeDefault = `question_default`;

export const UpdateAuditRateResponse = zod.object({
	answers: zod
		.array(
			zod.object({
				comment: zod.string().optional(),
				score: zod.number().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	comment: zod.string().optional(),
	conversation_id: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	critical_count: zod.string().optional(),
	form: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	id: zod.string().optional(),
	questions: zod
		.array(
			zod.object({
				critical_violation: zod.boolean().optional(),
				description: zod.string().optional(),
				max: zod.int().optional(),
				min: zod.int().optional(),
				options: zod
					.array(
						zod.object({
							name: zod.string().optional(),
							score: zod.number().optional(),
						}),
					)
					.optional(),
				question: zod.string().optional(),
				required: zod.boolean().optional(),
				type: zod
					.enum([
						'question_default',
						'question_score',
						'question_option',
						'question_yes',
					])
					.default(updateAuditRateResponseQuestionsItemTypeDefault),
			}),
		)
		.optional(),
	rated_user: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	score_optional: zod.number().optional(),
	score_required: zod.number().optional(),
	select_yes_count: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});
