/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

/**
 * @summary Retrieve a list of catalogs or search catalogs
 */
export const ListCatalogsQueryParams = zod.object({
	page: zod.int().optional().describe('Page number for pagination'),
	size: zod.int().optional().describe('Number of records per page'),
	fields: zod
		.array(zod.string())
		.optional()
		.describe(
			'Fields to be retrieved as a result.\nIf the user passes "-" as the value for fields,\nit will retrieve all available fields for each catalog.',
		),
	sort: zod.string().optional().describe('Sorting options by fields'),
	id: zod
		.array(zod.string())
		.optional()
		.describe('List of IDs to filter the catalogs'),
	query: zod
		.string()
		.optional()
		.describe(
			'Search query string for filtering by name. Supports:\n- Wildcards (*) for substring matching\n- Placeholder (?) for single character substitution\n- Exact match for full names',
		),
	state: zod
		.boolean()
		.optional()
		.describe('Filter by state (true for active, false for inactive)'),
	depth: zod
		.string()
		.optional()
		.describe(
			'Filter by the depth of the hierarchy to retrieve services.\nThe depth indicates how many ancestor levels of services\nwill be included for each catalog.\n- A depth of 0 includes only the direct catalog.\n- A depth of 1 includes the catalog and its immediate services.\n- By default the depth is limited by 3,\n  meaning all nested services and sub-services will be included.',
		),
	sub_fields: zod
		.array(zod.string())
		.optional()
		.describe(
			'Fields to be retrieved as a result for [SUBSERVICES].\nIf the user passes "-" as the value for fields,\nit will retrieve all available fields for each catalog subservices.',
		),
	hasSubservices: zod
		.boolean()
		.optional()
		.describe('Filter catalogs with subservices'),
});

export const ListCatalogsResponse = zod.object({
	items: zod
		.array(
			zod.object({
				close_reason_group: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				code: zod.string().optional(),
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				default_priority: zod
					.object({
						color: zod.string(),
						created_at: zod.string(),
						created_by: zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
						description: zod.string().optional(),
						id: zod.string(),
						name: zod.string(),
						updated_at: zod.string(),
						updated_by: zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
					})
					.optional()
					.describe(
						'Priority message represents a priority entity with metadata.',
					),
				description: zod.string().optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				prefix: zod.string().optional(),
				searched: zod.boolean().optional(),
				service: zod
					.array(
						zod.object({
							assignee: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								})
								.optional(),
							catalog_id: zod.string().optional(),
							code: zod.string().optional(),
							created_at: zod.string().optional(),
							created_by: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								})
								.optional(),
							default_priority: zod
								.object({
									color: zod.string(),
									created_at: zod.string(),
									created_by: zod.object({
										id: zod.string().optional(),
										name: zod.string().optional(),
									}),
									description: zod.string().optional(),
									id: zod.string(),
									name: zod.string(),
									updated_at: zod.string(),
									updated_by: zod.object({
										id: zod.string().optional(),
										name: zod.string().optional(),
									}),
								})
								.optional()
								.describe(
									'Priority message represents a priority entity with metadata.',
								),
							description: zod.string().optional(),
							group: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
									type: zod.string().optional(),
								})
								.optional(),
							id: zod.string().optional(),
							name: zod.string().optional(),
							root_id: zod.string().optional(),
							searched: zod.boolean().optional(),
							service: zod.array(zod.unknown()).optional(),
							sla: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								})
								.optional(),
							state: zod.boolean().optional(),
							updated_at: zod.string().optional(),
							updated_by: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								})
								.optional(),
						}),
					)
					.optional(),
				skills: zod
					.array(
						zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
					)
					.optional(),
				sla: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				state: zod.boolean().optional(),
				status: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				teams: zod
					.array(
						zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
					)
					.optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
	page: zod.int().optional(),
});

/**
 * @summary Create a new catalog
 */
export const CreateCatalogQueryParams = zod.object({
	fields: zod.array(zod.string()).optional(),
});

export const CreateCatalogBody = zod.object({
	close_reason_group: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	code: zod.string().optional(),
	default_priority: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	name: zod.string().optional(),
	prefix: zod.string().optional(),
	skills: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
	sla: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	state: zod.boolean().optional(),
	status: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	teams: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
});

export const CreateCatalogResponse = zod.object({
	close_reason_group: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	code: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	default_priority: zod
		.object({
			color: zod.string(),
			created_at: zod.string(),
			created_by: zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
			description: zod.string().optional(),
			id: zod.string(),
			name: zod.string(),
			updated_at: zod.string(),
			updated_by: zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		})
		.optional()
		.describe('Priority message represents a priority entity with metadata.'),
	description: zod.string().optional(),
	id: zod.string().optional(),
	name: zod.string().optional(),
	prefix: zod.string().optional(),
	searched: zod.boolean().optional(),
	service: zod
		.array(
			zod.object({
				assignee: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				catalog_id: zod.string().optional(),
				code: zod.string().optional(),
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				default_priority: zod
					.object({
						color: zod.string(),
						created_at: zod.string(),
						created_by: zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
						description: zod.string().optional(),
						id: zod.string(),
						name: zod.string(),
						updated_at: zod.string(),
						updated_by: zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
					})
					.optional()
					.describe(
						'Priority message represents a priority entity with metadata.',
					),
				description: zod.string().optional(),
				group: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
						type: zod.string().optional(),
					})
					.optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				root_id: zod.string().optional(),
				searched: zod.boolean().optional(),
				service: zod.array(zod.unknown()).optional(),
				sla: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				state: zod.boolean().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	skills: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
	sla: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	state: zod.boolean().optional(),
	status: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	teams: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary Delete a catalog
 */

export const DeleteCatalogParams = zod.object({
	id: zod
		.array(zod.string())
		.min(1)
		.describe('ID of the catalog to be deleted'),
});

export const DeleteCatalogResponse = zod.object({
	items: zod
		.array(
			zod.object({
				close_reason_group: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				code: zod.string().optional(),
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				default_priority: zod
					.object({
						color: zod.string(),
						created_at: zod.string(),
						created_by: zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
						description: zod.string().optional(),
						id: zod.string(),
						name: zod.string(),
						updated_at: zod.string(),
						updated_by: zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
					})
					.optional()
					.describe(
						'Priority message represents a priority entity with metadata.',
					),
				description: zod.string().optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				prefix: zod.string().optional(),
				searched: zod.boolean().optional(),
				service: zod
					.array(
						zod.object({
							assignee: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								})
								.optional(),
							catalog_id: zod.string().optional(),
							code: zod.string().optional(),
							created_at: zod.string().optional(),
							created_by: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								})
								.optional(),
							default_priority: zod
								.object({
									color: zod.string(),
									created_at: zod.string(),
									created_by: zod.object({
										id: zod.string().optional(),
										name: zod.string().optional(),
									}),
									description: zod.string().optional(),
									id: zod.string(),
									name: zod.string(),
									updated_at: zod.string(),
									updated_by: zod.object({
										id: zod.string().optional(),
										name: zod.string().optional(),
									}),
								})
								.optional()
								.describe(
									'Priority message represents a priority entity with metadata.',
								),
							description: zod.string().optional(),
							group: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
									type: zod.string().optional(),
								})
								.optional(),
							id: zod.string().optional(),
							name: zod.string().optional(),
							root_id: zod.string().optional(),
							searched: zod.boolean().optional(),
							service: zod.array(zod.unknown()).optional(),
							sla: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								})
								.optional(),
							state: zod.boolean().optional(),
							updated_at: zod.string().optional(),
							updated_by: zod
								.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								})
								.optional(),
						}),
					)
					.optional(),
				skills: zod
					.array(
						zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
					)
					.optional(),
				sla: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				state: zod.boolean().optional(),
				status: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				teams: zod
					.array(
						zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
					)
					.optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
	page: zod.int().optional(),
});

/**
 * @summary Locate a catalog by ID
 */
export const LocateCatalogParams = zod.object({
	id: zod.string().describe('ID of the catalog to be located'),
});

export const LocateCatalogQueryParams = zod.object({
	fields: zod
		.array(zod.string())
		.optional()
		.describe(
			'Fields to be retrieved as a result.\nIf the user passes "-" as the value for fields,\nit will retrieve all available fields for each catalog.',
		),
	sub_fields: zod
		.array(zod.string())
		.optional()
		.describe(
			'Fields to be retrieved as a result for [SUBSERVICES].\nIf the user passes "-" as the value for fields,\nit will retrieve all available fields for each catalog subservices.',
		),
});

export const LocateCatalogResponse = zod.object({
	catalog: zod
		.object({
			close_reason_group: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			code: zod.string().optional(),
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			default_priority: zod
				.object({
					color: zod.string(),
					created_at: zod.string(),
					created_by: zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
					description: zod.string().optional(),
					id: zod.string(),
					name: zod.string(),
					updated_at: zod.string(),
					updated_by: zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				})
				.optional()
				.describe(
					'Priority message represents a priority entity with metadata.',
				),
			description: zod.string().optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			prefix: zod.string().optional(),
			searched: zod.boolean().optional(),
			service: zod
				.array(
					zod.object({
						assignee: zod
							.object({
								id: zod.string().optional(),
								name: zod.string().optional(),
							})
							.optional(),
						catalog_id: zod.string().optional(),
						code: zod.string().optional(),
						created_at: zod.string().optional(),
						created_by: zod
							.object({
								id: zod.string().optional(),
								name: zod.string().optional(),
							})
							.optional(),
						default_priority: zod
							.object({
								color: zod.string(),
								created_at: zod.string(),
								created_by: zod.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								}),
								description: zod.string().optional(),
								id: zod.string(),
								name: zod.string(),
								updated_at: zod.string(),
								updated_by: zod.object({
									id: zod.string().optional(),
									name: zod.string().optional(),
								}),
							})
							.optional()
							.describe(
								'Priority message represents a priority entity with metadata.',
							),
						description: zod.string().optional(),
						group: zod
							.object({
								id: zod.string().optional(),
								name: zod.string().optional(),
								type: zod.string().optional(),
							})
							.optional(),
						id: zod.string().optional(),
						name: zod.string().optional(),
						root_id: zod.string().optional(),
						searched: zod.boolean().optional(),
						service: zod.array(zod.unknown()).optional(),
						sla: zod
							.object({
								id: zod.string().optional(),
								name: zod.string().optional(),
							})
							.optional(),
						state: zod.boolean().optional(),
						updated_at: zod.string().optional(),
						updated_by: zod
							.object({
								id: zod.string().optional(),
								name: zod.string().optional(),
							})
							.optional(),
					}),
				)
				.optional(),
			skills: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			sla: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			state: zod.boolean().optional(),
			status: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			teams: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});

/**
 * @summary Update an existing catalog
 */
export const UpdateCatalog2Params = zod.object({
	id: zod.string().describe('ID of the catalog to be updated'),
});

export const UpdateCatalog2QueryParams = zod.object({
	fields: zod.array(zod.string()).optional(),
});

export const UpdateCatalog2Body = zod.object({
	close_reason_group: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	code: zod.string().optional(),
	default_priority: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	name: zod.string().optional(),
	prefix: zod.string().optional(),
	skills: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
	sla: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	state: zod.boolean().optional(),
	status: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	teams: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
});

export const UpdateCatalog2Response = zod.object({
	close_reason_group: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	code: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	default_priority: zod
		.object({
			color: zod.string(),
			created_at: zod.string(),
			created_by: zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
			description: zod.string().optional(),
			id: zod.string(),
			name: zod.string(),
			updated_at: zod.string(),
			updated_by: zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		})
		.optional()
		.describe('Priority message represents a priority entity with metadata.'),
	description: zod.string().optional(),
	id: zod.string().optional(),
	name: zod.string().optional(),
	prefix: zod.string().optional(),
	searched: zod.boolean().optional(),
	service: zod
		.array(
			zod.object({
				assignee: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				catalog_id: zod.string().optional(),
				code: zod.string().optional(),
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				default_priority: zod
					.object({
						color: zod.string(),
						created_at: zod.string(),
						created_by: zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
						description: zod.string().optional(),
						id: zod.string(),
						name: zod.string(),
						updated_at: zod.string(),
						updated_by: zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
					})
					.optional()
					.describe(
						'Priority message represents a priority entity with metadata.',
					),
				description: zod.string().optional(),
				group: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
						type: zod.string().optional(),
					})
					.optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				root_id: zod.string().optional(),
				searched: zod.boolean().optional(),
				service: zod.array(zod.unknown()).optional(),
				sla: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				state: zod.boolean().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	skills: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
	sla: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	state: zod.boolean().optional(),
	status: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	teams: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary Update an existing catalog
 */
export const UpdateCatalogParams = zod.object({
	id: zod.string().describe('ID of the catalog to be updated'),
});

export const UpdateCatalogQueryParams = zod.object({
	fields: zod.array(zod.string()).optional(),
});

export const UpdateCatalogBody = zod.object({
	close_reason_group: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	code: zod.string().optional(),
	default_priority: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	name: zod.string().optional(),
	prefix: zod.string().optional(),
	skills: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
	sla: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	state: zod.boolean().optional(),
	status: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	teams: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
});

export const UpdateCatalogResponse = zod.object({
	close_reason_group: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	code: zod.string().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	default_priority: zod
		.object({
			color: zod.string(),
			created_at: zod.string(),
			created_by: zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
			description: zod.string().optional(),
			id: zod.string(),
			name: zod.string(),
			updated_at: zod.string(),
			updated_by: zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		})
		.optional()
		.describe('Priority message represents a priority entity with metadata.'),
	description: zod.string().optional(),
	id: zod.string().optional(),
	name: zod.string().optional(),
	prefix: zod.string().optional(),
	searched: zod.boolean().optional(),
	service: zod
		.array(
			zod.object({
				assignee: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				catalog_id: zod.string().optional(),
				code: zod.string().optional(),
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				default_priority: zod
					.object({
						color: zod.string(),
						created_at: zod.string(),
						created_by: zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
						description: zod.string().optional(),
						id: zod.string(),
						name: zod.string(),
						updated_at: zod.string(),
						updated_by: zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
					})
					.optional()
					.describe(
						'Priority message represents a priority entity with metadata.',
					),
				description: zod.string().optional(),
				group: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
						type: zod.string().optional(),
					})
					.optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				root_id: zod.string().optional(),
				searched: zod.boolean().optional(),
				service: zod.array(zod.unknown()).optional(),
				sla: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				state: zod.boolean().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	skills: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
	sla: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	state: zod.boolean().optional(),
	status: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	teams: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				name: zod.string().optional(),
			}),
		)
		.optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});
