/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

import axios from '../../api/axios/genClient';

import type {
	WebitelImProviderV1CustomServiceUpdateCustomGateBody,
	WebitelImProviderV1ProviderCreateCustomGateRequest,
	WebitelImProviderV1ProviderCreateCustomGateResponse,
	WebitelImProviderV1ProviderDeleteCustomGateResponse,
	WebitelImProviderV1ProviderGetCustomGateResponse,
	WebitelImProviderV1ProviderUpdateCustomGateResponse,
} from '../_models';

// --- header start
//

export const // --- title start
	getWebitelImProviderV1Customservice =
		// --- title end
		(axiosInstance: AxiosInstance = axios) => {
			// --- header end
			/**
			 * @summary / CreateCustomGate registers an external system as a messaging gateway.
			 */
			const customServiceCreateCustomGate = (
				webitelImProviderV1ProviderCreateCustomGateRequest: WebitelImProviderV1ProviderCreateCustomGateRequest,
				options?: AxiosRequestConfig,
			): Promise<
				AxiosResponse<WebitelImProviderV1ProviderCreateCustomGateResponse>
			> => {
				return axiosInstance.post(
					`/im/gates/custom`,
					webitelImProviderV1ProviderCreateCustomGateRequest,
					options,
				);
			};
			/**
			 * @summary / DeleteCustomGate removes the custom gateway integration.
			 */
			const customServiceDeleteCustomGate = (
				id: string,
				options?: AxiosRequestConfig,
			): Promise<
				AxiosResponse<WebitelImProviderV1ProviderDeleteCustomGateResponse>
			> => {
				return axiosInstance.delete(`/im/gates/custom/${id}`, options);
			};
			/**
			 * @summary / GetCustomGate retrieves configuration and status for a custom gateway.
			 */
			const customServiceGetCustomGate = (
				id: string,
				options?: AxiosRequestConfig,
			): Promise<
				AxiosResponse<WebitelImProviderV1ProviderGetCustomGateResponse>
			> => {
				return axiosInstance.get(`/im/gates/custom/${id}`, options);
			};
			/**
			 * @summary / UpdateCustomGate updates custom gateway settings.
			 */
			const customServiceUpdateCustomGate = (
				id: string,
				webitelImProviderV1CustomServiceUpdateCustomGateBody: WebitelImProviderV1CustomServiceUpdateCustomGateBody,
				options?: AxiosRequestConfig,
			): Promise<
				AxiosResponse<WebitelImProviderV1ProviderUpdateCustomGateResponse>
			> => {
				return axiosInstance.patch(
					`/im/gates/custom/${id}`,
					webitelImProviderV1CustomServiceUpdateCustomGateBody,
					options,
				);
			};

			// --- footer start
			return {
				customServiceCreateCustomGate,
				customServiceDeleteCustomGate,
				customServiceGetCustomGate,
				customServiceUpdateCustomGate,
			};
		};
export type CustomServiceCreateCustomGateResult =
	AxiosResponse<WebitelImProviderV1ProviderCreateCustomGateResponse>;
export type CustomServiceDeleteCustomGateResult =
	AxiosResponse<WebitelImProviderV1ProviderDeleteCustomGateResponse>;
export type CustomServiceGetCustomGateResult =
	AxiosResponse<WebitelImProviderV1ProviderGetCustomGateResponse>;
export type CustomServiceUpdateCustomGateResult =
	AxiosResponse<WebitelImProviderV1ProviderUpdateCustomGateResponse>;

// --- footer end
