/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

export const WorkingConditionServiceSearchWorkingConditionQueryParams =
	zod.object({
		page: zod.int().optional(),
		size: zod.int().optional(),
		q: zod.string().optional(),
		sort: zod.string().optional(),
		fields: zod.array(zod.string()).optional(),
	});

export const WorkingConditionServiceSearchWorkingConditionResponse = zod.object(
	{
		items: zod
			.array(
				zod.object({
					created_at: zod.string().optional(),
					created_by: zod
						.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						})
						.optional(),
					days_off: zod.int().optional(),
					description: zod.string().optional(),
					domain_id: zod.string().optional(),
					id: zod.string().optional(),
					name: zod.string().optional(),
					pause_duration: zod.int().optional(),
					pause_template: zod
						.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						})
						.optional(),
					shift_template: zod
						.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						})
						.optional(),
					sick_leaves: zod.int().optional(),
					updated_at: zod.string().optional(),
					updated_by: zod
						.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						})
						.optional(),
					vacation: zod.int().optional(),
					workday_hours: zod.int().optional(),
					workdays_per_month: zod.int().optional(),
				}),
			)
			.optional(),
		next: zod.boolean().optional(),
	},
);

export const WorkingConditionServiceCreateWorkingConditionBody = zod.object({
	item: zod
		.object({
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			days_off: zod.int().optional(),
			description: zod.string().optional(),
			domain_id: zod.string().optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			pause_duration: zod.int().optional(),
			pause_template: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			shift_template: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			sick_leaves: zod.int().optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			vacation: zod.int().optional(),
			workday_hours: zod.int().optional(),
			workdays_per_month: zod.int().optional(),
		})
		.optional(),
});

export const WorkingConditionServiceCreateWorkingConditionResponse = zod.object(
	{
		item: zod
			.object({
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				days_off: zod.int().optional(),
				description: zod.string().optional(),
				domain_id: zod.string().optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				pause_duration: zod.int().optional(),
				pause_template: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				shift_template: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				sick_leaves: zod.int().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				vacation: zod.int().optional(),
				workday_hours: zod.int().optional(),
				workdays_per_month: zod.int().optional(),
			})
			.optional(),
	},
);

export const WorkingConditionServiceDeleteWorkingConditionParams = zod.object({
	id: zod.string(),
});

export const WorkingConditionServiceDeleteWorkingConditionResponse = zod.object(
	{
		id: zod.string().optional(),
	},
);

export const WorkingConditionServiceReadWorkingConditionParams = zod.object({
	id: zod.string(),
});

export const WorkingConditionServiceReadWorkingConditionQueryParams =
	zod.object({
		fields: zod.array(zod.string()).optional(),
	});

export const WorkingConditionServiceReadWorkingConditionResponse = zod.object({
	item: zod
		.object({
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			days_off: zod.int().optional(),
			description: zod.string().optional(),
			domain_id: zod.string().optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			pause_duration: zod.int().optional(),
			pause_template: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			shift_template: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			sick_leaves: zod.int().optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			vacation: zod.int().optional(),
			workday_hours: zod.int().optional(),
			workdays_per_month: zod.int().optional(),
		})
		.optional(),
});

export const WorkingConditionServiceUpdateWorkingConditionParams = zod.object({
	'item.id': zod.string(),
});

export const WorkingConditionServiceUpdateWorkingConditionBody = zod.object({
	item: zod
		.object({
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			days_off: zod.int().optional(),
			description: zod.string().optional(),
			domain_id: zod.string().optional(),
			name: zod.string().optional(),
			pause_duration: zod.int().optional(),
			pause_template: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			shift_template: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			sick_leaves: zod.int().optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			vacation: zod.int().optional(),
			workday_hours: zod.int().optional(),
			workdays_per_month: zod.int().optional(),
		})
		.optional(),
});

export const WorkingConditionServiceUpdateWorkingConditionResponse = zod.object(
	{
		item: zod
			.object({
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				days_off: zod.int().optional(),
				description: zod.string().optional(),
				domain_id: zod.string().optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				pause_duration: zod.int().optional(),
				pause_template: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				shift_template: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				sick_leaves: zod.int().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				vacation: zod.int().optional(),
				workday_hours: zod.int().optional(),
				workdays_per_month: zod.int().optional(),
			})
			.optional(),
	},
);
