const IconAction = Object.freeze({
  REFRESH: 'refresh',
  ADD: 'add',
  DELETE: 'delete',
  FILTERS: 'filters',
  UPLOAD: 'upload',
  DOWNLOAD: 'download',
  EXPORT: 'export',
  COPY: 'copy',
  COLUMNS: 'columns',
  HISTORY: 'history',
  EDIT: 'edit',
  COLLAPSE: 'collapse',
  EXPAND: 'expand',
  CLOSE: 'close',
  CANCEL: 'cancel',
  VARIABLES: 'variables',
  CLEAR: 'clear',
  ADD_FILTER: 'add-filter',
  SAVE: 'save',
  SAVE_PRESET: 'save-preset',
  APPLY_PRESET: 'apply-preset',
  ADD_USER: 'add-user',
});

export default IconAction;
