/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

import axios from '../../api/axios/genClient';

import type {
	GetTimelineParams,
	WebitelCasesGetTimelineCounterResponse,
	WebitelCasesGetTimelineItemInfoResponse,
	WebitelCasesGetTimelineResponse,
} from '../_models';

// --- header start
//

export const // --- title start
	getCaseTimeline =
		// --- title end
		(axiosInstance: AxiosInstance = axios) => {
			// --- header end
			const getTimeline = (
				caseId: string,
				params?: GetTimelineParams,
				options?: AxiosRequestConfig,
			): Promise<AxiosResponse<WebitelCasesGetTimelineResponse>> => {
				return axiosInstance.get(`/cases/${caseId}/timeline`, {
					...options,
					params: {
						...params,
						...options?.params,
					},
				});
			};
			const getTimelineCounter = (
				caseId: string,
				options?: AxiosRequestConfig,
			): Promise<AxiosResponse<WebitelCasesGetTimelineCounterResponse>> => {
				return axiosInstance.get(`/cases/${caseId}/timeline/counter`, options);
			};
			const getTimelineItemInfo = (
				caseId: string,
				type: 'chat' | 'call' | 'email',
				id: string,
				options?: AxiosRequestConfig,
			): Promise<AxiosResponse<WebitelCasesGetTimelineItemInfoResponse>> => {
				return axiosInstance.get(
					`/cases/${caseId}/timeline/${type}/${id}/info`,
					options,
				);
			};

			// --- footer start
			return {
				getTimeline,
				getTimelineCounter,
				getTimelineItemInfo,
			};
		};
export type GetTimelineResult = AxiosResponse<WebitelCasesGetTimelineResponse>;
export type GetTimelineCounterResult =
	AxiosResponse<WebitelCasesGetTimelineCounterResponse>;
export type GetTimelineItemInfoResult =
	AxiosResponse<WebitelCasesGetTimelineItemInfoResponse>;

// --- footer end
