const FlowApp = Object.freeze({
  CALENDAR: 'calendar',
  EXECUTE: 'execute',
  FUNCTION: 'function',
  GOTO: 'goto',
  IF: 'if',
  JS: 'js',
  MATH: 'math',
  MONO_PAY: 'monoPay',
  START: 'start',
  STOP: 'stop',
  SWITCH: 'switch',
  STRING: 'string',
  MARK_IVR: 'markIVR',
  SOFT_SLEEP: 'softSleep',
  SET_GRANTEE: 'setGrantee',
  SCHEMA: 'schema',
  LOG: 'log',
  TRIGGER: 'trigger',
  HTTP_REQUEST: 'httpRequest',
  CUSTOM_CODE: 'customCode',
  EXPORT_VARIABLES: 'export',
  SET_VARIABLES: 'set',
  UN_SET_VARIABLES: 'unSet',
  USER_INFO: 'userInfo',
  LIST: 'list',
  LIST_ADD: 'listAdd',
  WHILE: 'while',

  PLAYBACK: 'playback',
  RING_READY: 'ringReady',
  PRE_ANSWER: 'preAnswer',
  ANSWER: 'answer',
  HANGUP: 'hangup',
  SIP_REDIRECT: 'sipRedirect',
  RINGBACK: 'ringback',
  BRIDGE: 'bridge',
  CONFERENCE: 'conference',
  GENERATE_LINK: 'generateLink',
  IN_BAND_DTMF: 'inBandDTMF',
  FLUSH_DTMF: 'flushDTMF',
  UPDATE_CID: 'updateCid',
  PARK: 'park',
  JOIN_QUEUE: 'joinQueue',
  RECORD_FILE: 'recordFile',
  RECORD_SESSION: 'recordSession',
  TTS: 'tts',
  MEMBER_INFO: 'memberInfo',
  GET_QUEUE_AGENTS: 'getQueueAgents',
  JOIN_AGENT: 'joinAgent',
  CALLBACK_QUEUE: 'callbackQueue',
  PATCH_MEMBERS: 'patchMembers',

  RECV_MESSAGE: 'recvMessage',
  SEND_TEXT: 'sendText',
  SEND_FILE: 'sendFile',
  SEND_EMAIL: 'sendEmail',
  SEND_TTS: 'sendTts',
  STT: 'stt',
  SEND_MESSAGE: 'sendMessage',
  CLASSIFIER: 'classifier',
  MENU: 'menu',
  BROADCAST_CHAT_MESSAGE: 'broadcastChatMessage',
  CHAT_HISTORY: 'chatHistory',

  FORM_TEXTFIELD: 'formTextfield',
  FORM_SELECT: 'formSelect',
  FORM_TEXT: 'formText',
  FORM_DATETIME_PICKER: 'formDatetimePicker',
  FORM_RICH_TEXT_EDITOR: 'formRichTextEditor',
  GENERATE_FORM: 'generateForm',
  ATTEMPT_RESULT: 'attemptResult',
  GET_EMAIL: 'getEmail',
  FORM_FILE: 'formFile',
});

export default FlowApp;
