import type { DefineComponent } from 'vue';

type WtComponent = DefineComponent<
	Record<string, unknown>,
	Record<string, unknown>,
	any
>;

export declare const WtActionBar: WtComponent;
export declare const WtImage: WtComponent;
export declare const WtEmpty: WtComponent;
export declare const WtLogo: WtComponent;
export declare const WtAvatar: WtComponent;
export declare const WtBadge: WtComponent;
export declare const WtBadgeNew: WtComponent;
export declare const WtMessage: WtComponent;
export declare const WtIcon: WtComponent;
export declare const WtIndicator: WtComponent;
export declare const WtButton: WtComponent;
export declare const WtChip: WtComponent;
export declare const WtConfirmDialog: WtComponent;
export declare const WtDivider: WtComponent;
export declare const WtTooltip: WtComponent;
export declare const WtLabel: WtComponent;
export declare const WtLoader: WtComponent;
export declare const WtRoundedAction: WtComponent;
export declare const WtReplaceTransition: WtComponent;
export declare const WtCheckbox: WtComponent;
export declare const WtDatepicker: WtComponent;
export declare const WtIconBtn: WtComponent;
export declare const WtInputNumber: WtComponent;
export declare const WtInputText: WtComponent;
export declare const WtPassword: WtComponent;
export declare const WtIntersectionObserver: WtComponent;
export declare const WtHint: WtComponent;
export declare const WtPopup: WtComponent;
export declare const WtProgressBar: WtComponent;
export declare const WtRadio: WtComponent;
export declare const WtSearchBar: WtComponent;
export declare const WtSlider: WtComponent;
export declare const WtSwitcher: WtComponent;
export declare const WtTabs: WtComponent;
export declare const WtTimeInput: WtComponent;
export declare const WtTimepicker: WtComponent;
export declare const WtTextarea: WtComponent;
export declare const WtToast: WtComponent;
export declare const WtAppHeader: WtComponent;
export declare const WtHeadline: WtComponent;
export declare const WtBreadcrumb: WtComponent;
export declare const WtNavigationBar: WtComponent;
export declare const WtAppNavigator: WtComponent;
export declare const WtFiltersPanelWrapper: WtComponent;
export declare const WtHeaderActions: WtComponent;
export declare const WtErrorPage: WtComponent;
export declare const WtNotificationsBar: WtComponent;
export declare const WtPageWrapper: WtComponent;
export declare const WtDualPanel: WtComponent;
export declare const WtPagination: WtComponent;
export declare const WtPlayer: WtComponent;
export declare const WtPopover: WtComponent;
export declare const WtStatusSelect: WtComponent;
export declare const WtTable: WtComponent;
export declare const WtTree: WtComponent;
export declare const WtTreeTable: WtComponent;
export declare const WtTableActions: WtComponent;
export declare const WtTableColumnSelect: WtComponent;
export declare const WtButtonSelect: WtComponent;
export declare const WtContextMenu: WtComponent;
export declare const WtCopyAction: WtComponent;
export declare const WtLoadBar: WtComponent;
export declare const WtIconAction: WtComponent;
export declare const WtPageHeader: WtComponent;
export declare const WtItemLink: WtComponent;
export declare const WtDummy: WtComponent;
export declare const WtStepper: WtComponent;
export declare const WtExpansionPanel: WtComponent;
export declare const WtNavigationMenu: WtComponent;
export declare const WtStartPage: WtComponent;
export declare const WtSelectionPopup: WtComponent;
export declare const WtDisplayChipItems: WtComponent;
export declare const WtGalleria: WtComponent;
export declare const WtVidstackPlayer: WtComponent;
export declare const WtChatEmoji: WtComponent;
export declare const WtExpansionCard: WtComponent;
export declare const WtDatetimeText: WtComponent;
export declare const WtCard: WtComponent;
export declare const WtSingleSelect: WtComponent;
export declare const WtMultiSelect: WtComponent;
export declare const WtScreenRecordingsAction: WtComponent;
export declare const WtInlineAddPanel: WtComponent;
export declare const WtCallMediaAction: WtComponent;
export declare const WtCallMediaMetric: WtComponent;
export declare const WtSendMessagePopup: WtComponent;

declare const Components: Record<string, WtComponent>;
export default Components;
