const lightColors = {
  root: {
    primary: {
      background: '{primary.color}',
      hoverBackground: '{primary.hover.color}',
      activeBackground: '{primary.active.color}',
      borderColor: '{primary.color}',
      hoverBorderColor: '{primary.color}',
      activeBorderColor: '{primary.color}',
      color: '{primary.foreground}',
      hoverColor: '{primary.foreground}',
      activeColor: '{primary.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    secondary: {
      background: '{secondary.color}',
      hoverBackground: '{secondary.hover.color}',
      activeBackground: '{secondary.active.color}',
      borderColor: '{secondary.color}',
      hoverBorderColor: '{secondary.color}',
      activeBorderColor: '{secondary.color}',
      color: '{secondary.foreground}',
      hoverColor: '{secondary.foreground}',
      activeColor: '{secondary.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    success: {
      background: '{success.color}',
      hoverBackground: '{success.hover.color}',
      activeBackground: '{success.active.color}',
      borderColor: '{success.color}',
      hoverBorderColor: '{success.color}',
      activeBorderColor: '{success.color}',
      color: '{success.foreground}',
      hoverColor: '{success.foreground}',
      activeColor: '{success.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    warn: {
      background: '{warn.color}',
      hoverBackground: '{warn.hover.color}',
      activeBackground: '{warn.active.color}',
      borderColor: '{warn.color}',
      hoverBorderColor: '{warn.color}',
      activeBorderColor: '{warn.color}',
      color: '{warn.foreground}',
      hoverColor: '{warn.foreground}',
      activeColor: '{warn.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    error: {
      background: '{error.color}',
      hoverBackground: '{error.hover.color}',
      activeBackground: '{error.active.color}',
      borderColor: '{error.color}',
      hoverBorderColor: '{error.color}',
      activeBorderColor: '{error.color}',
      color: '{error.foreground}',
      hoverColor: '{error.foreground}',
      activeColor: '{error.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    info: {
      background: '{info.color}',
      hoverBackground: '{info.hover.color}',
      activeBackground: '{info.active.color}',
      borderColor: '{info.color}',
      hoverBorderColor: '{info.color}',
      activeBorderColor: '{info.color}',
      color: '{info.foreground}',
      hoverColor: '{info.foreground}',
      activeColor: '{info.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    /**
     * TODO @Oleksandr Palonnyi
     * need to replace name "job" to "task",
     * */
    job: {
      background: '{task.color}',
      hoverBackground: '{task.hover.color}',
      activeBackground: '{task.active.color}',
      borderColor: '{task.color}',
      hoverBorderColor: '{task.color}',
      activeBorderColor: '{task.color}',
      color: '{task.foreground}',
      hoverColor: '{task.foreground}',
      activeColor: '{task.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    transfer: {
      background: '{transfer.color}',
      hoverBackground: '{transfer.hover.color}',
      activeBackground: '{transfer.active.color}',
      borderColor: '{transfer.color}',
      hoverBorderColor: '{transfer.color}',
      activeBorderColor: '{transfer.color}',
      color: '{transfer.foreground}',
      hoverColor: '{transfer.foreground}',
      activeColor: '{transfer.foreground}',
      focusRing: {
        color: '{focus-color}',
        shadow: 'none',
      },
    },
    disabled: {
      color: '{gray.400}',
      background: '{gray.100}',
    },
  },
  outlined: {
    primary: {
      hoverBackground: '{primary.highlight.color}',
      activeBackground: '{primary.active.color}',
      borderColor: '{primary.color}',
      color: '{primary.color}',
    },
    secondary: {
      hoverBackground: '{secondary.highlight.color}',
      activeBackground: '{secondary.active.color}',
      borderColor: '{secondary.color}',
      color: '{secondary.foreground}',
    },
    success: {
      hoverBackground: '{success.highlight.color}',
      activeBackground: '{success.active.color}',
      borderColor: '{success.color}',
      color: '{success.color}',
    },
    info: {
      hoverBackground: '{info.highlight.color}',
      activeBackground: '{info.active.color}',
      borderColor: '{info.color}',
      color: '{info.color}',
    },
    warn: {
      hoverBackground: '{warn.highlight.color}',
      activeBackground: '{warn.active.color}',
      borderColor: '{warn.color}',
      color: '{warn.color}',
    },
    job: {
      hoverBackground: '{task.highlight.color}',
      activeBackground: '{task.active.color}',
      borderColor: '{task.color}',
      color: '{task.color}',
    },
    error: {
      hoverBackground: '{error.highlight.color}',
      activeBackground: '{error.active.color}',
      borderColor: '{error.color}',
      color: '{error.color}',
    },
    transfer: {
      hoverBackground: '{transfer.highlight.color}',
      activeBackground: '{transfer.active.color}',
      borderColor: '{transfer.color}',
      color: '{transfer.color}',
    },
    disabled: {
      hoverBackground: '{transparent}',
      activeBackground: '{transparent}',
      borderColor: '{surface.100}',
      color: '{surface.200}',
    }
  },
  text: {
    primary: {
      hoverBackground: '{primary.hover.color}',
      activeBackground: '{primary.active.color}',
      color: '{primary.color}',
    },
    secondary: {
      hoverBackground: '{secondary.hover.color}',
      activeBackground: '{secondary.active.color}',
      color: '{secondary.foreground}',
    },
    success: {
      hoverBackground: '{success.hover.color}',
      activeBackground: '{success.active.color}',
      color: '{success.color}',
    },
    info: {
      hoverBackground: '{info.hover.color}',
      activeBackground: '{info.active.color}',
      color: '{info.color}',
    },
    warn: {
      hoverBackground: '{warn.hover.color}',
      activeBackground: '{warn.active.color}',
      color: '{warn.color}',
    },
    job: {
      hoverBackground: '{task.hover.color}',
      activeBackground: '{task.active.color}',
      color: '{task.color}',
    },
    error: {
      hoverBackground: '{error.hover.color}',
      activeBackground: '{error.active.color}',
      color: '{error.color}',
    },
    transfer: {
      hoverBackground: '{transfer.hover.color}',
      activeBackground: '{transfer.active.color}',
      color: '{transfer.color}',
    },
  },
  link: {
    color: '{info.color}',
    hoverColor: '{info.hover.color}',
    activeColor: '{info.active.color}',
  },
};

export default lightColors;
