/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

export const DeleteAgentSkillsParams = zod.object({
	agent_id: zod.string(),
});

export const DeleteAgentSkillsQueryParams = zod.object({
	id: zod.array(zod.string()).optional(),
	skill_id: zod.array(zod.string()).optional(),
});

export const DeleteAgentSkillsResponse = zod.object({
	items: zod
		.array(
			zod.object({
				capacity: zod.int().optional(),
				enabled: zod.boolean().optional(),
				id: zod.string().optional(),
				skill: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});

/**
 * @summary List of AgentSkill
 */
export const SearchAgentSkillParams = zod.object({
	agent_id: zod.string(),
});

export const SearchAgentSkillQueryParams = zod.object({
	page: zod.int().optional(),
	size: zod.int().optional(),
	q: zod.string().optional(),
	sort: zod.string().optional(),
	fields: zod.array(zod.string()).optional(),
	id: zod.array(zod.string()).optional(),
	skill_id: zod.array(zod.string()).optional(),
});

export const SearchAgentSkillResponse = zod.object({
	items: zod
		.array(
			zod.object({
				capacity: zod.int().optional(),
				enabled: zod.boolean().optional(),
				id: zod.string().optional(),
				skill: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});

export const PatchAgentSkillsParams = zod.object({
	agent_id: zod.string(),
});

export const PatchAgentSkillsBody = zod.object({
	capacity: zod.int().optional(),
	enabled: zod.boolean().optional(),
	fields: zod.array(zod.string()).optional(),
	id: zod.array(zod.string()).optional(),
	skill_id: zod.array(zod.string()).optional(),
});

export const PatchAgentSkillsResponse = zod.object({
	items: zod
		.array(
			zod.object({
				capacity: zod.int().optional(),
				enabled: zod.boolean().optional(),
				id: zod.string().optional(),
				skill: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});

/**
 * @summary Create AgentSkill
 */
export const CreateAgentSkillParams = zod.object({
	agent_id: zod.string(),
});

export const CreateAgentSkillBody = zod.object({
	capacity: zod.int().optional(),
	domain_id: zod.string().optional(),
	enabled: zod.boolean().optional(),
	skill: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const CreateAgentSkillResponse = zod.object({
	agent: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	capacity: zod.int().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	domain_id: zod.string().optional(),
	enabled: zod.boolean().optional(),
	id: zod.string().optional(),
	skill: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const CreateAgentSkillsParams = zod.object({
	agent_id: zod.string(),
});

export const CreateAgentSkillsBody = zod.object({
	items: zod
		.array(
			zod.object({
				capacity: zod.int().optional(),
				domain_id: zod.string().optional(),
				enabled: zod.boolean().optional(),
				skill: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
});

export const CreateAgentSkillsResponse = zod.object({
	ids: zod.array(zod.string()).optional(),
});

/**
 * @summary Remove AgentSkill
 */
export const DeleteAgentSkillParams = zod.object({
	agent_id: zod.string(),
	id: zod.string(),
});

export const DeleteAgentSkillQueryParams = zod.object({
	domain_id: zod.string().optional(),
});

export const DeleteAgentSkillResponse = zod.object({
	agent: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	capacity: zod.int().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	domain_id: zod.string().optional(),
	enabled: zod.boolean().optional(),
	id: zod.string().optional(),
	skill: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary AgentSkill item
 */
export const ReadAgentSkillParams = zod.object({
	agent_id: zod.string(),
	id: zod.string(),
});

export const ReadAgentSkillQueryParams = zod.object({
	domain_id: zod.string().optional(),
});

export const ReadAgentSkillResponse = zod.object({
	agent: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	capacity: zod.int().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	domain_id: zod.string().optional(),
	enabled: zod.boolean().optional(),
	id: zod.string().optional(),
	skill: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const PatchAgentSkillParams = zod.object({
	agent_id: zod.string(),
	id: zod.string(),
});

export const PatchAgentSkillBody = zod.object({
	capacity: zod.int().optional(),
	domain_id: zod.string().optional(),
	enabled: zod.boolean().optional(),
	fields: zod.array(zod.string()).optional(),
	skill: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const PatchAgentSkillResponse = zod.object({
	agent: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	capacity: zod.int().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	domain_id: zod.string().optional(),
	enabled: zod.boolean().optional(),
	id: zod.string().optional(),
	skill: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary Update AgentSkill
 */
export const UpdateAgentSkillParams = zod.object({
	agent_id: zod.string(),
	id: zod.string(),
});

export const UpdateAgentSkillBody = zod.object({
	capacity: zod.int().optional(),
	domain_id: zod.string().optional(),
	enabled: zod.boolean().optional(),
	skill: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const UpdateAgentSkillResponse = zod.object({
	agent: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	capacity: zod.int().optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	domain_id: zod.string().optional(),
	enabled: zod.boolean().optional(),
	id: zod.string().optional(),
	skill: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary SearchLookupAgentNotExistsSkill
 */
export const SearchLookupAgentNotExistsSkillParams = zod.object({
	agent_id: zod.string(),
});

export const SearchLookupAgentNotExistsSkillQueryParams = zod.object({
	page: zod.int().optional(),
	size: zod.int().optional(),
	q: zod.string().optional(),
	domain_id: zod.string().optional(),
});

export const SearchLookupAgentNotExistsSkillResponse = zod.object({
	items: zod
		.array(
			zod.object({
				active_agents: zod.int().optional(),
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				description: zod.string().optional(),
				domain_id: zod.string().optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				total_agents: zod.int().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});
