/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type AgentStateHistoryParams = {
	page?: number;
	size?: number;
	time_from?: string;
	time_to?: string;
	q?: string;
	domain_id?: string;
};
