/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { ApiCustomerLimit } from './apiCustomerLimit.zod';
import type { ApiLicenseV1 } from './apiLicenseV1.zod';
import type { ApiObjectId } from './apiObjectId.zod';
import type { ApiVerification } from './apiVerification.zod';

export interface ApiCustomer {
	/** local created ms */
	created_at?: string;
	dnsrv?: ApiObjectId[];
	id?: string;
	/** [required] issuer(CA) created at */
	issued_at?: string;
	/** grants issued */
	license?: ApiLicenseV1[];
	/** defines map[class]limit usage */
	limit?: ApiCustomerLimit;
	next_update?: string;
	not_after?: string;
	not_before?: string;
	organization?: string;
	revoked_at?: string;
	/** [optional]: issuer(CA) signed at */
	this_update?: string;
	updated_at?: string;
	/** [optional] validation results */
	verify?: ApiVerification;
}
