/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface ApiLDAProcessOptions {
	link_existing_objects?: boolean;
	reassign_device_users?: boolean;
	test?: boolean;
	timeout?: string;
}
