/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { ApiAccessToken } from './apiAccessToken.zod';

export interface ApiLoginResponse {
	authorization?: ApiAccessToken;
}
