/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { ApiLDAProcess } from './apiLDAProcess.zod';

export interface ApiLDAProcessResponse {
	items?: ApiLDAProcess[];
	next?: boolean;
	page?: number;
}
