/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { ApiLDAPCatalogTLSConfig } from './apiLDAPCatalogTLSConfig';
import type { ApiLDAProcess } from './apiLDAProcess';
import type { ApiLDAProcessOptions } from './apiLDAProcessOptions';
import type { ApiLDAPTemplate } from './apiLDAPTemplate';
import type { ApiUserId } from './apiUserId';

export interface ApiLDAPCatalog {
	base_dn?: string;
	/** authorization method e.g.: SIMPLE, SAML, NTLM, etc. */
	bind?: string;
	/** unix */
	created_at?: string;
	created_by?: ApiUserId;
	/** [CRON]OS SPEC ! github.com/robfig/cron/v3 */
	cron?: string;
	entry_modify?: string;
	/** entry unique id (except DN which may be updated) */
	entry_uuid?: string;
	id?: string;
	name?: string;
	password?: string;
	process?: ApiLDAProcess;
	sync?: ApiLDAProcessOptions;
	templates?: ApiLDAPTemplate[];
	tls?: ApiLDAPCatalogTLSConfig;
	updated_at?: string;
	updated_by?: ApiUserId;
	/** URL e.g.: [(ldap|ldapi|ldaps)://]host[:port] */
	url?: string;
	username?: string;
}
