/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { ApiObjectId } from './apiObjectId';
import type { ApiPermission } from './apiPermission';
import type { ApiRoleMetadata } from './apiRoleMetadata';
import type { ApiUserId } from './apiUserId';

export interface ApiRole {
	created_at?: string;
	created_by?: ApiUserId;
	deleted_at?: string;
	deleted_by?: ApiUserId;
	description?: string;
	id?: string;
	/** users/roles */
	members?: ApiObjectId[];
	metadata?: ApiRoleMetadata;
	name?: string;
	permissions?: ApiPermission[];
	updated_at?: string;
	updated_by?: ApiUserId;
	user?: boolean;
}
