/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { ApiDeviceId } from './apiDeviceId.zod';
import type { ApiUserId } from './apiUserId.zod';

export interface ApiRegistration {
	callid?: string;
	contact?: string;
	device?: ApiDeviceId;
	expires_at?: string;
	id?: string;
	instance?: string;
	received?: string;
	register_at?: string;
	socket?: string;
	user?: ApiUserId;
	user_agent?: string;
}
