/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface ApiUpdatePasswordRequest {
	confirm_password?: string;
	domain?: string;
	id?: string;
	old_password?: string;
	user_password?: string;
	username?: string;
}
