/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { ApiLicenseExpiryWarning } from './apiLicenseExpiryWarning.zod';
import type { ApiPasswordExpiryWarning } from './apiPasswordExpiryWarning.zod';

export interface ApiWarningData {
	license_expiry?: ApiLicenseExpiryWarning;
	password_expiry?: ApiPasswordExpiryWarning;
}
