/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelContactsLookup } from './webitelContactsLookup';

/**
 * A contact's photo.
 * A picture shown next to the contact's name
 * to help others recognize the contact.
 */
export interface ContactsPhoto {
	/** The user who created this Field. */
	created_at?: string;
	/** Timestamp(milli) of the Field creation. */
	created_by?: WebitelContactsLookup;
	/**
	 * Unique ID of the latest version of the update.
	 * This ID changes after any update to the underlying value(s).
	 */
	etag?: string;
	/** The unique ID of the association. Never changes. */
	id?: string;
	photo_id?: string;
	photo_url?: string;
	/** True if the photo is a default photo; false if the photo is a user-provided photo. */
	primary?: boolean;
	/**
	 * Timestamp(milli) of the last Field update.
	 * Take part in Etag generation.
	 */
	updated_at?: string;
	/** The user who performed last Update. */
	updated_by?: WebitelContactsLookup;
	/** Version of the latest update. Numeric sequence. */
	ver?: number;
}
