/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { ContactsCallFile } from './contactsCallFile';
import type { ContactsTranscriptLookup } from './contactsTranscriptLookup';
import type { WebitelContactsLookup } from './webitelContactsLookup';

export interface ContactsCallEvent {
	closed_at?: string;
	duration?: string;
	files?: ContactsCallFile[];
	flow_scheme?: WebitelContactsLookup;
	gateway?: WebitelContactsLookup;
	id?: string;
	is_detailed?: boolean;
	is_inbound?: boolean;
	is_missed?: boolean;
	participants?: WebitelContactsLookup[];
	queue?: WebitelContactsLookup;
	total_duration?: string;
	transcripts?: ContactsTranscriptLookup[];
}
