/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

/**
 * Input of the contact IM client.
 */
export interface ContactsInputIMClient {
	/** Id of Agent created this IM client. */
	created_by?: string;
	external_user?: string;
	/** App (Text-Gateway) used to connect the IM client. */
	gateway_id?: string;
	protocol?: string;
	/** [Via] App(-specific) peer(-id) to connect[from] the IM client. */
	via?: string;
}
