/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type ContactSettingsManagementUpdateAllowInvitesFrom =
	(typeof ContactSettingsManagementUpdateAllowInvitesFrom)[keyof typeof ContactSettingsManagementUpdateAllowInvitesFrom];

export const ContactSettingsManagementUpdateAllowInvitesFrom = {
	All: 'ALL',
	Nobody: 'NOBODY',
	SameIssuer: 'SAME_ISSUER',
} as const;
