/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

/**
 * Position details for conditions in the group.
 */
export interface ContactsPosition {
	cond_down?: string;
	cond_up?: string;
}
