/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WfmAbsenceType } from './wfmAbsenceType';

export interface CreateAgentsAbsencesRequestabsentType {
	date_from?: string;
	date_to?: string;
	type_id?: WfmAbsenceType;
}
