/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { DictionariesBatchCreateDataBodyRowsItem } from './dictionariesBatchCreateDataBodyRowsItem';

export interface DictionariesBatchCreateDataBody {
	/**
	 * Parsed records to create. For Select(lookup) columns each row carries
	 * the related record display name (string); for Multiselect(list of lookup)
	 * columns - an array of display names. Backend resolves name -> id
	 * (case-insensitive).
	 */
	rows?: DictionariesBatchCreateDataBodyRowsItem[];
}
