/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type DownloadCallScreenrecordingArchiveParams = {
	/**
	 * Optional IDs of selected screen recordings.
	 */
	file_ids?: string[];
	/**
	 * Start of the uploaded_at range (Unix millis).
	 */
	from?: string;
	/**
	 * End of the uploaded_at range (Unix millis).
	 */
	to?: string;
};
