/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { GoogleRpcStatus } from './googleRpcStatus';
import type { WebitelMediaExporterDownloadCallScreenrecordingArchiveResponse } from './webitelMediaExporterDownloadCallScreenrecordingArchiveResponse';

export type DownloadCallScreenrecordingArchive200 = {
	error?: GoogleRpcStatus;
	result?: WebitelMediaExporterDownloadCallScreenrecordingArchiveResponse;
};
