/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineDefaultDeviceConfigResponseSipDeviceConfig } from './engineDefaultDeviceConfigResponseSipDeviceConfig.zod';
import type { EngineDefaultDeviceConfigResponseWebRTCDeviceConfig } from './engineDefaultDeviceConfigResponseWebRTCDeviceConfig.zod';

export interface EngineDefaultDeviceConfigResponse {
	sip?: EngineDefaultDeviceConfigResponseSipDeviceConfig;
	webrtc?: EngineDefaultDeviceConfigResponseWebRTCDeviceConfig;
}
