/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup.zod';

export interface EngineHistoryCallCallForm {
	agent?: EngineLookup;
	reporting_at?: string;
}
