/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface EngineCallServiceDtmfCallBody {
	app_id?: string;
	digit?: string;
	domain_id?: string;
}
