/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface EngineCreateAgentPauseCauseRequest {
	allow_admin?: boolean;
	allow_agent?: boolean;
	allow_supervisor?: boolean;
	description?: string;
	limit_min?: number;
	name?: string;
}
