/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineAcceptOfDay } from './engineAcceptOfDay';
import type { EngineExceptDate } from './engineExceptDate';
import type { EngineLookup } from './engineLookup';

export interface EngineCreateCalendarRequest {
	accepts?: EngineAcceptOfDay[];
	description?: string;
	domain_id?: string;
	end_at?: string;
	excepts?: EngineExceptDate[];
	name?: string;
	specials?: EngineAcceptOfDay[];
	start_at?: string;
	timezone?: EngineLookup;
}
