/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface EngineResetActiveAttemptsRequest {
	attempt_type?: string[];
	idle_for_minutes?: string;
	result?: string;
}
