/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface EngineCallServiceHangupCallBody {
	app_id?: string;
	cause?: string;
	domain_id?: string;
}
