/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface EngineMemberServiceCreateAttemptBody {
	agent_id?: string;
	domain_id?: string;
}
