/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineAgentChannel } from './engineAgentChannel.zod';
import type { EngineAgentUserPresence } from './engineAgentUserPresence.zod';
import type { EngineLookup } from './engineLookup.zod';

export interface EngineAgent {
	allow_channels?: string[];
	allow_set_screen_control?: boolean;
	auditor?: EngineLookup[];
	channel?: EngineAgentChannel[];
	chat_count?: number;
	description?: string;
	extension?: string;
	extra_chat_count?: number;
	greeting_media?: EngineLookup;
	id?: string;
	is_supervisor?: boolean;
	last_status_change?: string;
	name?: string;
	progressive_count?: number;
	region?: EngineLookup;
	screen_control?: boolean;
	skills?: EngineLookup[];
	status?: string;
	status_duration?: string;
	supervisor?: EngineLookup[];
	task_count?: number;
	team?: EngineLookup;
	user?: EngineLookup;
	user_presence_status?: EngineAgentUserPresence;
}
