/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineCreateCallRequestCallSettingsVariables } from './engineCreateCallRequestCallSettingsVariables';

export interface EngineCreateCallRequestCallSettings {
	cancel_distribute?: boolean;
	contact_id?: string;
	disable_auto_answer?: boolean;
	disable_stun?: boolean;
	display?: string;
	hide_number?: boolean;
	is_online?: boolean;
	timeout?: number;
	variables?: EngineCreateCallRequestCallSettingsVariables;
}
