/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup';

export interface EngineAgentStatusStatisticItem {
	agent_id?: number;
	auditor?: EngineLookup[];
	chat_count?: number;
	desc_track?: boolean;
	extension?: string;
	name?: string;
	offline?: string;
	online?: string;
	pause?: string;
	pause_cause?: string;
	progressive_count?: number;
	region?: EngineLookup;
	score_count?: string;
	score_optional_avg?: number;
	score_required_avg?: number;
	screen_control?: boolean;
	status?: string;
	status_comment?: string;
	status_duration?: string;
	supervisor?: EngineLookup[];
	team?: EngineLookup;
	user?: EngineLookup;
}
