/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineQueueHook } from './engineQueueHook.zod';

export interface EngineListQueueHook {
	items?: EngineQueueHook[];
	next?: boolean;
}
