/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface EngineOutboundResourceTimeRange {
	end_time_of_day?: number;
	start_time_of_day?: number;
}
