/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup.zod';
import type { EngineOutboundResourceTimeRange } from './engineOutboundResourceTimeRange.zod';

export interface EngineOutboundResourceGroup {
	communication?: EngineLookup;
	created_at?: string;
	created_by?: EngineLookup;
	description?: string;
	domain_id?: string;
	id?: string;
	name?: string;
	strategy?: string;
	time?: EngineOutboundResourceTimeRange[];
	updated_at?: string;
	updated_by?: EngineLookup;
}
