/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup.zod';

export interface EngineAgentState {
	agent?: EngineLookup;
	channel?: string;
	duration?: string;
	id?: string;
	joined_at?: string;
	leaved_at?: string;
	pause_cause?: string;
	payload?: string;
	queue?: EngineLookup;
	state?: string;
}
