/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineAuditForm } from './engineAuditForm.zod';

export interface EngineListAuditForm {
	items?: EngineAuditForm[];
	next?: boolean;
}
