/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup';

export interface EngineMemberAttempt {
	active?: boolean;
	agent?: EngineLookup;
	answered_at?: string;
	attempts?: number;
	bridged_at?: string;
	bucket?: EngineLookup;
	created_at?: string;
	destination?: string;
	hangup_at?: string;
	id?: string;
	leg_a_id?: string;
	leg_b_id?: string;
	member?: EngineLookup;
	node?: string;
	originate_at?: string;
	resource?: EngineLookup;
	result?: string;
	weight?: number;
}
