/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineEmailAuthType } from './engineEmailAuthType.zod';
import type { EngineEmailProfileParams } from './engineEmailProfileParams.zod';
import type { EngineLookup } from './engineLookup.zod';

export interface EngineEmailProfileServiceUpdateEmailProfileBody {
	auth_type?: EngineEmailAuthType;
	description?: string;
	enabled?: boolean;
	fetch_interval?: number;
	imap_host?: string;
	imap_port?: number;
	listen?: boolean;
	login?: string;
	mailbox?: string;
	name?: string;
	params?: EngineEmailProfileParams;
	password?: string;
	schema?: EngineLookup;
	smtp_host?: string;
	smtp_port?: number;
}
