/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineTriggerJob } from './engineTriggerJob.zod';

export interface EngineListTriggerJob {
	items?: EngineTriggerJob[];
	next?: boolean;
}
