/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup';
import type { EngineTriggerJobState } from './engineTriggerJobState';

export interface EngineTriggerJob {
	created_at?: string;
	error?: string;
	id?: string;
	started_at?: string;
	state?: EngineTriggerJobState;
	stopped_at?: string;
	trigger?: EngineLookup;
}
