/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineMemberCommunication } from './engineMemberCommunication';

export interface EngineListOfMemberCommunication {
	items?: EngineMemberCommunication[];
	next?: boolean;
}
