/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface EngineListCommunication {
	description?: string;
	expire_at?: string;
	id?: string;
	list_id?: string;
	number?: string;
}
