/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup';

export interface EngineSchemaVersion {
	created_at?: string;
	created_by?: EngineLookup;
	id?: string;
	note?: string;
	schema_id?: string;
	version?: string;
}
