/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup';

export interface EngineQuickReply {
	article?: EngineLookup;
	created_at?: string;
	created_by?: EngineLookup;
	id?: number;
	name?: string;
	queues?: EngineLookup[];
	teams?: EngineLookup[];
	text?: string;
	updated_at?: string;
	updated_by?: EngineLookup;
}
