/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineSystemSettingName } from './engineSystemSettingName.zod';

export interface EngineCreateSystemSettingRequest {
	name?: EngineSystemSettingName;
}
