/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineFilterBetween } from './engineFilterBetween.zod';
import type { EngineSearchHistoryCallRequestVariablesString } from './engineSearchHistoryCallRequestVariablesString.zod';

export interface EngineSearchHistoryCallRequest {
	tags?: string[];
	agent_description?: string;
	agent_id?: string[];
	amd_ai_result?: string[];
	amd_result?: string[];
	answered_at?: EngineFilterBetween;
	cause?: string[];
	contact_id?: string[];
	created_at?: EngineFilterBetween;
	dependency_id?: string;
	direction?: string;
	directions?: string[];
	domain_id?: string;
	duration?: EngineFilterBetween;
	fields?: string[];
	fts?: string;
	gateway_id?: string[];
	grantee_id?: string[];
	has_file?: boolean;
	has_transcript?: boolean;
	has_transfer?: boolean;
	id?: string[];
	member_id?: string[];
	missed?: boolean;
	number?: string;
	owner_id?: string[];
	page?: number;
	parent_id?: string;
	q?: string;
	queue_id?: string[];
	rated?: boolean;
	rated_by?: string[];
	rated_user?: string[];
	schema_id?: number[];
	score_optional?: EngineFilterBetween;
	score_required?: EngineFilterBetween;
	size?: number;
	skip_parent?: boolean;
	sort?: string;
	stored_at?: EngineFilterBetween;
	talk?: EngineFilterBetween;
	team_id?: string[];
	timeline?: boolean;
	transfer_from?: string[];
	transfer_to?: string[];
	user_id?: string[];
	'variables[string]'?: EngineSearchHistoryCallRequestVariablesString;
}
