/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineCreateCallRequestCallSettings } from './engineCreateCallRequestCallSettings';
import type { EngineCreateCallRequestEndpointRequest } from './engineCreateCallRequestEndpointRequest';

export interface EngineCreateCallRequest {
	destination?: string;
	domain_id?: string;
	from?: EngineCreateCallRequestEndpointRequest;
	params?: EngineCreateCallRequestCallSettings;
	to?: EngineCreateCallRequestEndpointRequest;
}
