/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineActiveCallVariables } from './engineActiveCallVariables.zod';
import type { EngineEndpoint } from './engineEndpoint.zod';
import type { EngineLookup } from './engineLookup.zod';

export interface EngineActiveCall {
	agent?: EngineLookup;
	answered_at?: string;
	app_id?: string;
	bill_sec?: number;
	blind_transfer?: string;
	bridged_at?: string;
	bridged_id?: string;
	created_at?: string;
	destination?: string;
	direction?: string;
	display?: string;
	duration?: number;
	extension?: string;
	from?: EngineEndpoint;
	gateway?: EngineLookup;
	hold_sec?: number;
	id?: string;
	joined_at?: string;
	leaving_at?: string;
	member?: EngineLookup;
	parent_id?: string;
	queue?: EngineLookup;
	queue_bridged_at?: string;
	queue_duration_sec?: number;
	queue_wait_sec?: number;
	reporting_at?: string;
	reporting_sec?: number;
	state?: string;
	supervisor?: EngineLookup[];
	team?: EngineLookup;
	timestamp?: string;
	to?: EngineEndpoint;
	type?: string;
	user?: EngineLookup;
	variables?: EngineActiveCallVariables;
	wait_sec?: number;
}
