/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup.zod';
import type { EngineQueueVariables } from './engineQueueVariables.zod';
import type { EngineResource } from './engineResource.zod';
import type { EngineResourceGroup } from './engineResourceGroup.zod';
import type { EngineTag } from './engineTag.zod';
import type { EngineTaskProcessing } from './engineTaskProcessing.zod';

export interface EngineQueue {
	tags?: EngineTag[];
	active?: number;
	after_schema?: EngineLookup;
	calendar?: EngineLookup;
	count?: number;
	created_at?: string;
	created_by?: EngineLookup;
	description?: string;
	dnc_list?: EngineLookup;
	do_schema?: EngineLookup;
	domain_id?: string;
	enabled?: boolean;
	form_schema?: EngineLookup;
	grantee?: EngineLookup;
	id?: string;
	name?: string;
	priority?: number;
	processing?: boolean;
	processing_renewal_sec?: number;
	processing_sec?: number;
	resource_groups?: EngineResourceGroup[];
	resources?: EngineResource[];
	ringtone?: EngineLookup;
	schema?: EngineLookup;
	sec_locate_agent?: number;
	sticky_agent?: boolean;
	strategy?: string;
	task_processing?: EngineTaskProcessing;
	team?: EngineLookup;
	timeout?: number;
	type?: number;
	updated_at?: string;
	updated_by?: EngineLookup;
	variables?: EngineQueueVariables;
	waiting?: number;
}
