/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup.zod';

export interface EngineQuestionAnswer {
	comment?: string;
	score?: number;
	updated_at?: string;
	updated_by?: EngineLookup;
}
