/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface EngineEavesdropCallRequestEndpointRequest {
	app_id?: string;
	extension?: string;
	id?: string;
	type?: string;
}
