/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineHistoryFileJobHistoryFileJobAction } from './engineHistoryFileJobHistoryFileJobAction';
import type { EngineHistoryFileJobHistoryFileJobState } from './engineHistoryFileJobHistoryFileJobState';

export interface EngineHistoryFileJob {
	action?: EngineHistoryFileJobHistoryFileJobAction;
	created_at?: string;
	error_detail?: string;
	file_id?: string;
	id?: string;
	state?: EngineHistoryFileJobHistoryFileJobState;
}
