/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineEavesdropCallRequestEndpointRequest } from './engineEavesdropCallRequestEndpointRequest.zod';

export interface EngineCallServiceEavesdropCallBody {
	app_id?: string;
	control?: boolean;
	from?: EngineEavesdropCallRequestEndpointRequest;
	listen_a?: boolean;
	listen_b?: boolean;
	whisper_a?: boolean;
	whisper_b?: boolean;
}
