/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineOnlineSkills } from './engineOnlineSkills.zod';

/**
 * Response containing the requested online skills.
 */
export interface EngineGetOnlineSkillsResponse {
	/** Requested online skills item. */
	item?: EngineOnlineSkills;
}
