/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineCreateMemberBulkItemVariables } from './engineCreateMemberBulkItemVariables';
import type { EngineLookup } from './engineLookup';
import type { EngineMemberCommunicationCreateRequest } from './engineMemberCommunicationCreateRequest';

export interface EngineCreateMemberBulkItem {
	agent?: EngineLookup;
	bucket?: EngineLookup;
	communications?: EngineMemberCommunicationCreateRequest[];
	expire_at?: string;
	min_offering_at?: string;
	name?: string;
	priority?: number;
	skill?: EngineLookup;
	timezone?: EngineLookup;
	variables?: EngineCreateMemberBulkItemVariables;
}
