/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineCommunicationChannels } from './engineCommunicationChannels.zod';

export interface EngineCommunicationType {
	channel?: EngineCommunicationChannels;
	code?: string;
	default?: boolean;
	description?: string;
	domain_id?: string;
	id?: string;
	name?: string;
}
