/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup.zod';

export interface EngineAgentPauseCause {
	allow_admin?: boolean;
	allow_agent?: boolean;
	allow_supervisor?: boolean;
	created_at?: string;
	created_by?: EngineLookup;
	description?: string;
	id?: number;
	limit_min?: number;
	name?: string;
	updated_at?: string;
	updated_by?: EngineLookup;
}
