/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface EngineExceptDate {
	date?: string;
	disabled?: boolean;
	name?: string;
	repeat?: boolean;
	work_start?: number;
	work_stop?: number;
	working?: boolean;
}
