/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup.zod';
import type { EngineRoutingSchemaType } from './engineRoutingSchemaType.zod';
import type { EngineSchemaTag } from './engineSchemaTag.zod';

export interface EngineRoutingSchema {
	tags?: EngineSchemaTag[];
	created_at?: string;
	created_by?: EngineLookup;
	debug?: boolean;
	description?: string;
	editor?: boolean;
	id?: string;
	name?: string;
	type?: EngineRoutingSchemaType;
	updated_at?: string;
	updated_by?: EngineLookup;
}
