/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineOnlineSkills } from './engineOnlineSkills';

/**
 * Search results for online skills.
 */
export interface EngineSearchOnlineSkillsResponse {
	/** Matching online skills items. */
	items?: EngineOnlineSkills[];
	/** Indicates whether another page of results exists. */
	next?: boolean;
}
