/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup.zod';

export interface EngineWebHook {
	authorization?: string;
	created_at?: string;
	created_by?: EngineLookup;
	description?: string;
	enabled?: boolean;
	id?: number;
	key?: string;
	name?: string;
	origin?: string[];
	schema?: EngineLookup;
	updated_at?: string;
	updated_by?: EngineLookup;
}
