/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface EngineAcceptOfDay {
	day?: number;
	disabled?: boolean;
	end_time_of_day?: number;
	start_time_of_day?: number;
}
