/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup';
import type { EngineQueueServiceUpdateQueueBodyVariables } from './engineQueueServiceUpdateQueueBodyVariables';
import type { EngineTag } from './engineTag';
import type { EngineTaskProcessing } from './engineTaskProcessing';

export interface EngineQueueServiceUpdateQueueBody {
	tags?: EngineTag[];
	after_schema?: EngineLookup;
	calendar?: EngineLookup;
	description?: string;
	dnc_list?: EngineLookup;
	do_schema?: EngineLookup;
	domain_id?: string;
	enabled?: boolean;
	form_schema?: EngineLookup;
	grantee?: EngineLookup;
	name?: string;
	priority?: number;
	processing?: boolean;
	processing_renewal_sec?: number;
	processing_sec?: number;
	ringtone?: EngineLookup;
	schema?: EngineLookup;
	sec_locate_agent?: number;
	sticky_agent?: boolean;
	strategy?: string;
	task_processing?: EngineTaskProcessing;
	team?: EngineLookup;
	timeout?: number;
	type?: number;
	variables?: EngineQueueServiceUpdateQueueBodyVariables;
}
