/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup';
import type { EngineOutboundResourceParameters } from './engineOutboundResourceParameters';
import type { EngineOutboundResourceServicePatchOutboundResourceBodyVariables } from './engineOutboundResourceServicePatchOutboundResourceBodyVariables';

export interface EngineOutboundResourceServicePatchOutboundResourceBody {
	parameters?: EngineOutboundResourceParameters;
	description?: string;
	enabled?: boolean;
	error_ids?: string[];
	failure_dial_delay?: number;
	fields?: string[];
	gateway?: EngineLookup;
	limit?: number;
	max_successively_errors?: number;
	name?: string;
	number?: string;
	patterns?: string[];
	reserve?: boolean;
	rps?: number;
	variables?: EngineOutboundResourceServicePatchOutboundResourceBodyVariables;
}
