/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface EngineMemberServiceAssignAttemptBody {
	/** Optional. If omitted (0), the attempt is assigned to the calling user's own agent. */
	agent_id?: string;
}
