/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface EngineOpenedWebSocket {
	application_name?: string;
	created_at?: string;
	duration?: string;
	id?: string;
	ip?: string;
	pong?: string;
	updated_at?: string;
	user_agent?: string;
	ver?: string;
}
