/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup';
import type { EngineQuestion } from './engineQuestion';

export interface EngineAuditForm {
	created_at?: string;
	created_by?: EngineLookup;
	description?: string;
	editable?: boolean;
	enabled?: boolean;
	id?: number;
	name?: string;
	questions?: EngineQuestion[];
	teams?: EngineLookup[];
	updated_at?: string;
	updated_by?: EngineLookup;
}
