/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type ExportCasesParams = {
	q?: string;
	ids?: string[];
	sort?: string;
	fields?: string[];
	filters?: string[];
	contact_id?: string;
	qin?: string;
	filters_v1?: string;
	format?: string;
	separator?: string;
};
