/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { GetTimelineTypeItem } from './getTimelineTypeItem.zod';

export type GetTimelineParams = {
	page?: number;
	size?: number;
	q?: string;
	sort?: string;
	fields?: string[];
	ids?: string[];
	date_from?: string;
	date_to?: string;
	type?: GetTimelineTypeItem[];
};
