/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { GetTimelineTimelineTypeItem } from './getTimelineTimelineTypeItem';

export type GetTimelineTimelineParams = {
	page?: string;
	size?: string;
	q?: string;
	sort?: string;
	fields?: string[];
	ids?: string[];
	date_from?: string;
	date_to?: string;
	type?: GetTimelineTimelineTypeItem[];
};
