/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImProviderV1Peer } from './webitelImProviderV1Peer.zod';

export interface ImServiceProviderV1CreateTelegramBotGateRequest {
	api_token?: string;
	enabled?: boolean;
	name?: string;
	peer?: WebitelImProviderV1Peer;
	uri?: string;
	webhook_secret?: string;
}
