/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { ApiUserId } from './apiUserId.zod';
import type { LDAPUpdateLDAPTemplateBodyTemplateAgent } from './lDAPUpdateLDAPTemplateBodyTemplateAgent.zod';
import type { LDAPUpdateLDAPTemplateBodyTemplateCatalog } from './lDAPUpdateLDAPTemplateBodyTemplateCatalog.zod';
import type { LDAPUpdateLDAPTemplateBodyTemplateDevice } from './lDAPUpdateLDAPTemplateBodyTemplateDevice.zod';
import type { LDAPUpdateLDAPTemplateBodyTemplateRole } from './lDAPUpdateLDAPTemplateBodyTemplateRole.zod';
import type { LDAPUpdateLDAPTemplateBodyTemplateUser } from './lDAPUpdateLDAPTemplateBodyTemplateUser.zod';

/**
 * Template changes.
 */
export type LDAPUpdateLDAPTemplateBodyTemplate = {
	agent?: LDAPUpdateLDAPTemplateBodyTemplateAgent;
	base_dn?: string;
	catalog?: LDAPUpdateLDAPTemplateBodyTemplateCatalog;
	/** unix */
	created_at?: string;
	created_by?: ApiUserId;
	device?: LDAPUpdateLDAPTemplateBodyTemplateDevice;
	enabled?: boolean;
	name?: string;
	role?: LDAPUpdateLDAPTemplateBodyTemplateRole;
	search?: string;
	updated_at?: string;
	updated_by?: ApiUserId;
	user?: LDAPUpdateLDAPTemplateBodyTemplateUser;
};
