/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type ListRegistrationsParams = {
	/**
	 * Object ID
	 */
	'user.id'?: string;
	/**
	 * Display Name
	 */
	'user.name'?: string;
	/**
	 * Display Name
	 */
	'device.name'?: string;
};
