/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { LoggerLookup } from './loggerLookup.zod';

export interface LoggerConfig {
	days_to_store?: number;
	description?: string;
	enabled?: boolean;
	id?: number;
	logs_count?: string;
	logs_size?: string;
	object?: LoggerLookup;
	period?: number;
	storage?: LoggerLookup;
}
