/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { LoggerConfig } from './loggerConfig.zod';

export interface LoggerConfigs {
	items?: LoggerConfig[];
	next?: boolean;
	page?: number;
}
