/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WfmLookupEntity } from './wfmLookupEntity';
import type { WfmPauseTemplateCause } from './wfmPauseTemplateCause';

export type PauseTemplateServiceUpdatePauseTemplateBodyItem = {
	causes?: WfmPauseTemplateCause[];
	created_at?: string;
	created_by?: WfmLookupEntity;
	description?: string;
	domain_id?: string;
	name?: string;
	updated_at?: string;
	updated_by?: WfmLookupEntity;
};
