/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type PublishCommentParams = {
	/**
	 * Result fields to include in the response.
	 */
	fields?: string[];
	/**
	 * Optional creation timestamp. If not set, will be set default(current) time.
	 */
	created_at?: string;
};
