/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type ReadUser2Params = {
	id?: string;
	/**
	 * partial output
	 */
	fields?: string[];
};
