/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type ResetMembersCountParams = {
	/**
	 * Filter by specific queue member identifiers.
	 */
	ids?: string[];
	/**
	 * Filter by bucket identifiers.
	 */
	bucket_id?: string[];
	/**
	 * Filter by stop causes.
	 */
	stop_cause?: string[];
	/**
	 * Filter by assigned agent identifiers.
	 */
	agent_id?: number[];
	/**
	 * Filter by member phone numbers.
	 */
	numbers?: string[];
	/**
	 * This is a request variable of the map type. The query format is "map_name[key]=value", e.g. If the map name is Age, the key type is string, and the value type is integer, the query parameter is expressed as Age["bob"]=18
	 */
	'variables[string]'?: string;
	/**
	 * Filter by related entity identifiers.
	 */
	id?: string[];
	'created_at.from'?: string;
	'created_at.to'?: string;
	'priority.from'?: string;
	'priority.to'?: string;
	/**
	 * Search pattern used to filter queue members.
	 * The value is matched against the member name
	 * and against the member's searchable destination values.
	 */
	q?: string;
};
