/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type SearchOnlineSkillsParams = {
	/**
	 * Page number (1-based).
	 */
	page?: number;
	/**
	 * Maximum number of items per page.
	 */
	size?: number;
	/**
	 * Search pattern applied to names.
	 */
	q?: string;
	/**
	 * Sort expression.
	 * Example: "-name", "+created_at".
	 */
	sort?: string;
	/**
	 * List of fields to include in the response.
	 */
	fields?: string[];
	/**
	 * Filter by online skills identifiers.
	 */
	ids?: string[];
	/**
	 * Filter by associated skill identifiers.
	 */
	skill_ids?: string[];
	/**
	 * Skip the default entry in the search results.
	 */
	skip_default?: boolean;
};
