/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { SearchFilesChannelItem } from './searchFilesChannelItem';

export type SearchFilesParams = {
	page?: number;
	size?: number;
	q?: string;
	sort?: string;
	fields?: string[];
	id?: string[];
	'uploaded_at.from'?: string;
	'uploaded_at.to'?: string;
	uploaded_by?: string[];
	reference_id?: string[];
	/**
	 *  - ScreenRecordingChannel: ScreenshotChannel = 8; // deprecated
	 */
	channel?: SearchFilesChannelItem[];
	'retention_until.from'?: string;
	'retention_until.to'?: string;
};
