/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type SearchRoutingVariableParams = {
	page?: number;
	size?: number;
	domain_id?: string;
};
