/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type SearchQueueHookParams = {
	page?: number;
	size?: number;
	q?: string;
	sort?: string;
	fields?: string[];
	id?: number[];
	schema_id?: number[];
	event?: string[];
};
