/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type SearchQueueReportGeneralParams = {
	page?: number;
	size?: number;
	'joined_at.from'?: string;
	'joined_at.to'?: string;
	domain_id?: string;
	fields?: string[];
	sort?: string;
	q?: string;
	queue_id?: number[];
	team_id?: number[];
	type?: number[];
};
