/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { SearchRetrievalTagMatch } from './searchRetrievalTagMatch';

export type SearchRetrievalParams = {
	/**
	 * Free-text query.
	 */
	query?: string;
	/**
	 * Spaces to search within.
	 */
	space_ids?: string[];
	/**
	 * Optional tag filter.
	 */
	tags?: string[];
	/**
	 * How to combine the tag filter.
	 *
	 *  - TAG_MATCH_ALL: Default: match articles having ALL listed tags (AND).
	 *  - TAG_MATCH_ANY: Match articles having ANY listed tag (OR).
	 */
	tag_match?: SearchRetrievalTagMatch;
	/**
	 * Page size.
	 */
	size?: number;
	/**
	 * Page number (1-based).
	 */
	page?: number;
};
