/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type SearchHistoryCallParams = {
	page?: number;
	size?: number;
	q?: string;
	sort?: string;
	fields?: string[];
	'created_at.from'?: string;
	'created_at.to'?: string;
	user_id?: string[];
	agent_id?: string[];
	queue_id?: string[];
	team_id?: string[];
	member_id?: string[];
	gateway_id?: string[];
	'duration.from'?: string;
	'duration.to'?: string;
	skip_parent?: boolean;
	parent_id?: string;
	cause?: string[];
	has_file?: boolean;
	domain_id?: string;
	number?: string;
	direction?: string;
	'answered_at.from'?: string;
	'answered_at.to'?: string;
	missed?: boolean;
	'stored_at.from'?: string;
	'stored_at.to'?: string;
	id?: string[];
	transfer_from?: string[];
	transfer_to?: string[];
	dependency_id?: string;
	tags?: string[];
	/**
	 * This is a request variable of the map type. The query format is "map_name[key]=value", e.g. If the map name is Age, the key type is string, and the value type is integer, the query parameter is expressed as Age["bob"]=18
	 */
	'variables[string]'?: string;
	amd_result?: string[];
	fts?: string;
	directions?: string[];
	has_transcript?: boolean;
	agent_description?: string;
	owner_id?: string[];
	grantee_id?: string[];
	amd_ai_result?: string[];
	'talk.from'?: string;
	'talk.to'?: string;
	rated?: boolean;
	rated_by?: string[];
	'score_required.from'?: string;
	'score_required.to'?: string;
	'score_optional.from'?: string;
	'score_optional.to'?: string;
	rated_user?: string[];
	contact_id?: string[];
	schema_id?: number[];
	has_transfer?: boolean;
	timeline?: boolean;
};
