/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { SearchScreenRecordingsChannel } from './searchScreenRecordingsChannel.zod';
import type { SearchScreenRecordingsType } from './searchScreenRecordingsType.zod';

export type SearchScreenRecordingsParams = {
	page?: number;
	size?: number;
	q?: string;
	sort?: string;
	fields?: string[];
	id?: string[];
	'uploaded_at.from'?: string;
	'uploaded_at.to'?: string;
	reference_id?: string[];
	'retention_until.from'?: string;
	'retention_until.to'?: string;
	type?: SearchScreenRecordingsType;
	channel?: SearchScreenRecordingsChannel;
};
