/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type SearchAttemptsHistoryParams = {
	page?: number;
	size?: number;
	q?: string;
	sort?: string;
	fields?: string[];
	'joined_at.from'?: string;
	'joined_at.to'?: string;
	id?: string[];
	queue_id?: string[];
	bucket_id?: string[];
	member_id?: string[];
	agent_id?: string[];
	result?: string[];
	'leaving_at.from'?: string;
	'leaving_at.to'?: string;
	'offering_at.from'?: string;
	'offering_at.to'?: string;
	'duration.from'?: string;
	'duration.to'?: string;
	offered_agent_id?: string[];
};
