/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type SearchParams = {
	page?: number;
	size?: number;
	q?: string;
	sort?: string;
	fields?: string[];
	object_name?: string[];
};
