/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { SearchScreenRecordingsByAgentChannel } from './searchScreenRecordingsByAgentChannel';
import type { SearchScreenRecordingsByAgentType } from './searchScreenRecordingsByAgentType';

export type SearchScreenRecordingsByAgentParams = {
	page?: number;
	size?: number;
	q?: string;
	sort?: string;
	fields?: string[];
	id?: string[];
	'uploaded_at.from'?: string;
	'uploaded_at.to'?: string;
	reference_id?: string[];
	'retention_until.from'?: string;
	'retention_until.to'?: string;
	type?: SearchScreenRecordingsByAgentType;
	channel?: SearchScreenRecordingsByAgentChannel;
};
