/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WfmLookupEntity } from './wfmLookupEntity.zod';
import type { WfmShiftTemplateTime } from './wfmShiftTemplateTime.zod';

export type ShiftTemplateServiceUpdateShiftTemplateBodyItem = {
	created_at?: string;
	created_by?: WfmLookupEntity;
	description?: string;
	domain_id?: string;
	name?: string;
	times?: WfmShiftTemplateTime[];
	updated_at?: string;
	updated_by?: WfmLookupEntity;
};
