/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { StorageFileMalwareScan } from './storageFileMalwareScan.zod';
import type { StorageThumbnail } from './storageThumbnail.zod';
import type { StorageUploadStatusCode } from './storageUploadStatusCode.zod';

export interface StorageUploadFileResponse {
	code?: StorageUploadStatusCode;
	file_id?: string;
	file_url?: string;
	malware?: StorageFileMalwareScan;
	server?: string;
	sha256sum?: string;
	size?: string;
	thumbnail?: StorageThumbnail;
}
