/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface StorageGenerateFileLinkResponseMetadata {
	id?: string;
	mime_type?: string;
	name?: string;
	size?: string;
	uuid?: string;
}
