/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup.zod';

export interface StorageStartFileTranscriptRequest {
	file_id?: string[];
	locale?: string;
	profile?: EngineLookup;
	uuid?: string[];
}
