/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { StorageUploadFileChannel } from './storageUploadFileChannel';

export interface StorageFilePoliciesServicePatchFilePolicyBody {
	channels?: StorageUploadFileChannel[];
	description?: string;
	enabled?: boolean;
	encrypt?: boolean;
	fields?: string[];
	max_upload_size?: string;
	mime_types?: string[];
	name?: string;
	retention_days?: number;
	speed_download?: string;
	speed_upload?: string;
}
