/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { StorageBackendProfileServicePatchBackendProfileBodyProperties } from './storageBackendProfileServicePatchBackendProfileBodyProperties';

export interface StorageBackendProfileServicePatchBackendProfileBody {
	description?: string;
	disabled?: boolean;
	domain_id?: string;
	expire_days?: number;
	fields?: string[];
	max_size?: string;
	name?: string;
	priority?: number;
	properties?: StorageBackendProfileServicePatchBackendProfileBodyProperties;
}
