/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup';
import type { StorageProviderType } from './storageProviderType';
import type { StorageServiceType } from './storageServiceType';

export interface StorageCognitiveProfile {
	created_at?: string;
	created_by?: EngineLookup;
	default?: boolean;
	description?: string;
	enabled?: boolean;
	id?: string;
	name?: string;
	provider?: StorageProviderType;
	service?: StorageServiceType;
	updated_at?: string;
	updated_by?: EngineLookup;
}
