/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { StorageCustomFileProperties } from './storageCustomFileProperties.zod';
import type { StorageUploadFileChannel } from './storageUploadFileChannel.zod';

export interface StorageSafeUploadFileRequestMetadata {
	channel?: StorageUploadFileChannel;
	domain_id?: string;
	generate_thumbnail?: boolean;
	mime_type?: string;
	name?: string;
	profile_id?: string;
	progress?: boolean;
	properties?: StorageCustomFileProperties;
	stream_response?: boolean;
	uuid?: string;
}
