/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { StorageFileMalwareScan } from './storageFileMalwareScan.zod';
import type { StorageThumbnail } from './storageThumbnail.zod';
import type { StorageUploadStatusCode } from './storageUploadStatusCode.zod';

export interface StorageSafeUploadFileResponseMetadata {
	code?: StorageUploadStatusCode;
	file_id?: string;
	file_url?: string;
	malware?: StorageFileMalwareScan;
	mime_type?: string;
	name?: string;
	server?: string;
	sha256sum?: string;
	size?: string;
	thumbnail?: StorageThumbnail;
	uuid?: string;
}
