/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { StorageGenerateFileLinkRequestQuery } from './storageGenerateFileLinkRequestQuery.zod';

export interface StorageGenerateFileLinkRequest {
	action?: string;
	domain_id?: string;
	file_id?: string;
	metadata?: boolean;
	query?: StorageGenerateFileLinkRequestQuery;
	source?: string;
}
