/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { EngineLookup } from './engineLookup.zod';
import type { StorageCustomFileProperties } from './storageCustomFileProperties.zod';
import type { StorageThumbnail } from './storageThumbnail.zod';
import type { StorageUploadFileChannel } from './storageUploadFileChannel.zod';

export interface StorageFile {
	channel?: StorageUploadFileChannel;
	id?: string;
	mime_type?: string;
	name?: string;
	properties?: StorageCustomFileProperties;
	reference_id?: string;
	retention_until?: string;
	sha256sum?: string;
	size?: string;
	thumbnail?: StorageThumbnail;
	uploaded_at?: string;
	uploaded_by?: EngineLookup;
	uuid?: string;
	view_name?: string;
}
