/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { TypeTextViolation } from './typeTextViolation';

export interface TypeText {
	max_bytes?: number;
	max_chars?: number;
	multiline?: boolean;
	violation?: TypeTextViolation;
}
