/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { TypeBinaryViolation } from './typeBinaryViolation';

export interface TypeBinary {
	max_bytes?: number;
	violation?: TypeBinaryViolation;
}
