/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type UpdateCustomerParams = {
	/**
	 * [optional] e.g.: Example Org.
	 */
	organization?: string;
	/**
	 * [optional] logo source image
	 */
	logo_picture?: string;
	/**
	 * [optional] raw bytes protobuf::base64.RawStdEncoding != certificate::base64.StdEncoding
	 */
	certificate?: string;
	revoke?: boolean;
};
