/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type UpdatePhotoBody = {
	photo_id?: string;
	photo_url?: string;
	/** True if the photo is a default photo; false if the photo is a user-provided photo. */
	primary?: boolean;
};
