/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { ApiObjectId } from './apiObjectId';
import type { UpdateUserAccessTokenBodyUser } from './updateUserAccessTokenBodyUser';

export type UpdateUserAccessTokenBody = {
	created_at?: string;
	created_by?: ApiObjectId;
	deleted_at?: string;
	deleted_by?: ApiObjectId;
	token?: string;
	updated_at?: string;
	updated_by?: ApiObjectId;
	usage?: string;
	user?: UpdateUserAccessTokenBodyUser;
};
