/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { ApiObjectId } from './apiObjectId';
import type { UpdateUserAccessToken2BodyUser } from './updateUserAccessToken2BodyUser';

export type UpdateUserAccessToken2Body = {
	created_at?: string;
	created_by?: ApiObjectId;
	deleted_at?: string;
	deleted_by?: ApiObjectId;
	token?: string;
	updated_at?: string;
	updated_by?: ApiObjectId;
	usage?: string;
	user?: UpdateUserAccessToken2BodyUser;
};
