/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { ApiUserId } from './apiUserId.zod';
import type { UpdateDevice2BodyProvision } from './updateDevice2BodyProvision.zod';

export type UpdateDevice2Body = {
	/** username */
	account?: string;
	/** vendor brand name */
	brand?: string;
	created_at?: string;
	created_by?: ApiUserId;
	deleted_at?: string;
	deleted_by?: ApiUserId;
	/** act as a hotdesk */
	hotdesk?: boolean;
	hotdesks?: string[];
	ip?: string;
	logged_in?: string;
	mac?: string;
	model?: string;
	/** display name */
	name?: string;
	password?: string;
	provision?: UpdateDevice2BodyProvision;
	reged?: boolean;
	updated_at?: string;
	updated_by?: ApiUserId;
	user?: ApiUserId;
};
