/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { GeneralLookup } from './generalLookup.zod';
import type { UpdateRelatedCaseBodyPrimaryCase } from './updateRelatedCaseBodyPrimaryCase.zod';
import type { WebitelCasesRelationType } from './webitelCasesRelationType.zod';

export type UpdateRelatedCaseBody = {
	/** Primary case details. */
	primary_case?: UpdateRelatedCaseBodyPrimaryCase;
	/** Related case details. */
	related_case?: GeneralLookup;
	/** Relation type. */
	relation_type?: WebitelCasesRelationType;
	/** Optional creator / updater ID. Use this to explicitly set the case creator / updater instead of deriving it from the auth token. */
	userID?: GeneralLookup;
};
