/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

/**
 * Client sends callback event when user clicks a button.
 */
export interface WebitelImApiGatewayV1MessageSendInteractiveCallbackBody {
	/** Button identifier. */
	button_code?: string;
	/** Optional callback payload. */
	callback_data?: string;
}
