/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelKbArticleSummary } from './webitelKbArticleSummary';

/**
 * ResolveResponse returns the resolved article summaries.
 */
export interface WebitelKbResolveResponse {
	/** Resolved article summaries (RBAC filtered). */
	items?: WebitelKbArticleSummary[];
}
