/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelKbArticleType } from './webitelKbArticleType.zod';

/**
 * TreeNode is a single node of an article hierarchy tree.
 */
export interface WebitelKbTreeNode {
	/** Child nodes. */
	children?: WebitelKbTreeNode[];
	/** Hierarchy depth (1..5). */
	depth?: number;
	/** Article id. */
	id?: string;
	/** Article subject. */
	subject?: string;
	/** Article type. */
	type?: WebitelKbArticleType;
}
