/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImProviderV1Peer } from './webitelImProviderV1Peer';

/**
 * / ProviderUpdateViberBmGateRequest updates settings. A non-empty api_key rotates the key.
 */
export interface WebitelImProviderV1ViberBmServiceUpdateViberBmBody {
	api_key?: string;
	base_url?: string;
	enabled?: boolean;
	name?: string;
	peer?: WebitelImProviderV1Peer;
	sender_name?: string;
	webhook_secret?: string;
}
