/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

/**
 * Represents `Document` message with necessary fields
 * to process it into frequently used `document`
 * entity in messaging systems.
 */
export interface WebitelImApiGatewayV1DocumentInput {
	file_name?: string;
	id?: string;
	mime_type?: string;
	size_bytes?: string;
	url?: string;
}
