/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type WebitelImApiGatewayV1SkippedMessageReason =
	(typeof WebitelImApiGatewayV1SkippedMessageReason)[keyof typeof WebitelImApiGatewayV1SkippedMessageReason];

export const WebitelImApiGatewayV1SkippedMessageReason = {
	ReasonUnspecified: 'REASON_UNSPECIFIED',
	ReasonNotFound: 'REASON_NOT_FOUND',
	ReasonNotAuthor: 'REASON_NOT_AUTHOR',
	ReasonAlreadyDeleted: 'REASON_ALREADY_DELETED',
	ReasonChatClosed: 'REASON_CHAT_CLOSED',
	ReasonNotAllowed: 'REASON_NOT_ALLOWED',
} as const;
