/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

/**
 * InputPeer identity.
 */
export interface WebitelChatInputPeer {
	id?: string;
	type?: string;
	via?: string;
}
