/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { GeneralLookup } from './generalLookup.zod';
import type { WebitelCasesRelatedCaseLookup } from './webitelCasesRelatedCaseLookup.zod';
import type { WebitelCasesRelationType } from './webitelCasesRelationType.zod';

/**
 * Represents a related case with its relationship details.
 */
export interface WebitelCasesRelatedCase {
	/** Timestamp (in milliseconds) of when the relation was created. */
	created_at?: string;
	/** User who created the relation. */
	created_by?: GeneralLookup;
	/** Etag for the related case entity. */
	etag?: string;
	/** Unique identifier for the related case. */
	id?: string;
	/** Primary case details. */
	primary_case?: WebitelCasesRelatedCaseLookup;
	/** Related case details. */
	related_case?: WebitelCasesRelatedCaseLookup;
	/** Relation type between cases. */
	relation_type?: WebitelCasesRelationType;
	/** Timestamp (in milliseconds) of the last update. */
	updated_at?: string;
	/** User who last updated the relation. */
	updated_by?: GeneralLookup;
	/** Version number of the related case, used for concurrency control. */
	ver?: number;
}
