/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { GeneralExtendedLookup } from './generalExtendedLookup.zod';

/**
 * Metadata for a file associated with a case.
 */
export interface WebitelCasesFile {
	/** Creation timestamp in Unix milliseconds. */
	created_at?: string;
	/** Creator of the file. */
	created_by?: GeneralExtendedLookup;
	/** Storage file ID. */
	id?: string;
	/** MIME type of the file. */
	mime?: string;
	/** File name. */
	name?: string;
	/** File size in bytes. */
	size?: string;
	source?: string;
	url?: string;
}
