/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelMediaExporterExportStatus } from './webitelMediaExporterExportStatus';

/**
 * Metadata about an export task immediately after creation.
 */
export interface WebitelMediaExporterExportTask {
	/** Target name of the PDF file. */
	file_name?: string;
	/** MIME type (usually application/pdf). */
	mime_type?: string;
	/** File size in bytes (0 if not yet generated). */
	size?: string;
	/** Current lifecycle status of the task. */
	status?: WebitelMediaExporterExportStatus;
	/** Unique ID to track the background task. */
	task_id?: string;
}
