/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelChatServerMessage } from './webitelChatServerMessage';

export interface WebitelChatServerStartConversationResponse {
	channel_id?: string;
	conversation_id?: string;
	message?: WebitelChatServerMessage;
}
