/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface WebitelImApiGatewayV1ThreadPermissions {
	can_add_members?: boolean;
	can_change_members_permissions?: boolean;
	can_change_thread_info?: boolean;
	can_delete_messages?: boolean;
	can_remove_members?: boolean;
	can_send_messages?: boolean;
	created_at?: string;
	id?: string;
	member_id?: string;
	updated_at?: string;
}
