/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

/**
 * Entity is a single formatting span over a message's plain-text content.
 * im-gateway-service parses the original markdown exactly once and turns it
 * into a list of these canonical spans (the "parse-once-at-gateway" design);
 * im-providers-service only relays and renders them for the destination
 * channel -- it does not re-parse markdown.
 *
 * `type` is an open allow-list, not an enum, so new span kinds can be added
 * later without breaking readers that don't know them yet. Values in use
 * today: BOLD, ITALIC, STRIKETHROUGH, CODE, PRE, LINK.
 */
export interface WebitelImProviderV1Entity {
	/** Length of the span, in UTF-8 bytes, matching `offset`. */
	length?: number;
	/**
	 * Start of the span, as a UTF-8 byte offset into the message's text
	 * (`text` or `caption`). Bounded to reject pathological payloads.
	 */
	offset?: number;
	/** Span kind. Open allow-list -- see message comment above. */
	type?: string;
	/**
	 * Extra data the span kind needs, e.g. the target URL for a LINK entity.
	 * Unset for kinds that don't need one (BOLD, ITALIC, STRIKETHROUGH, CODE, PRE).
	 */
	value?: string;
}
