/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface WebitelImApiProviderV1ProviderMetaLinkedPage {
	access_token?: string;
	page_id?: string;
	page_name?: string;
	platform?: string;
}
