/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelCasesCallFileType } from './webitelCasesCallFileType';

export interface WebitelCasesCallFile {
	channel?: string;
	id?: string;
	mime_type?: string;
	name?: string;
	size?: string;
	start_at?: string;
	stop_at?: string;
	type?: WebitelCasesCallFileType;
}
