/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { GeneralExtendedLookup } from './generalExtendedLookup';
import type { GeneralLookup } from './generalLookup';
import type { WebitelCasesCaseCommentList } from './webitelCasesCaseCommentList';
import type { WebitelCasesCaseCustom } from './webitelCasesCaseCustom';
import type { WebitelCasesCaseFileList } from './webitelCasesCaseFileList';
import type { WebitelCasesCaseLinkList } from './webitelCasesCaseLinkList';
import type { WebitelCasesPriority } from './webitelCasesPriority';
import type { WebitelCasesRelatedCaseList } from './webitelCasesRelatedCaseList';
import type { WebitelCasesService } from './webitelCasesService';
import type { WebitelCasesSourceTypeLookup } from './webitelCasesSourceTypeLookup';
import type { WebitelCasesStatusCondition } from './webitelCasesStatusCondition';

/**
 * Message representing a case.
 */
export interface WebitelCasesCase {
	/** Assignee responsible for resolving the case. */
	assignee?: GeneralLookup;
	/** Author or reporter of the case. */
	author?: GeneralLookup;
	close_reason?: GeneralLookup;
	/** Close reason group, immutable once set. */
	close_reason_group?: GeneralLookup;
	close_result?: string;
	/** List of comments on the case. */
	comments?: WebitelCasesCaseCommentList;
	/** Contact information for the case. */
	contact_info?: string;
	/** Creation timestamp (in milliseconds since Unix epoch). */
	created_at?: string;
	/** Creator of the case. */
	created_by?: GeneralLookup;
	/** Custom data extension fields .. */
	custom?: WebitelCasesCaseCustom;
	dc?: string;
	/** Detailed description of the case. */
	description?: string;
	difference_in_reaction?: string;
	difference_in_resolve?: string;
	/** Unique etag identifier. */
	etag?: string;
	/** List of attached files. */
	files?: WebitelCasesCaseFileList;
	/** Group associated with the case. */
	group?: GeneralExtendedLookup;
	/** Unique case ID. */
	id?: string;
	/** Impacted contact (defaults to reporter if null). */
	impacted?: GeneralLookup;
	/** List of attached links. */
	links?: WebitelCasesCaseLinkList;
	/** Name of the case (may serve as an ID in docs). */
	name?: string;
	/** Planned reaction time (in milliseconds). */
	planned_reaction_at?: string;
	/** Planned resolution time (in milliseconds). */
	planned_resolve_at?: string;
	/** Priority level of the case. */
	priority?: WebitelCasesPriority;
	rating?: string;
	rating_comment?: string;
	reacted_at?: string;
	/** List of related cases. */
	related?: WebitelCasesRelatedCaseList;
	/** Reporter of the issue (null if anonymous). */
	reporter?: GeneralLookup;
	resolved_at?: string;
	role_ids?: string[];
	/** Service associated with the case. */
	service?: WebitelCasesService;
	/** SLA associated with the case. */
	sla?: GeneralLookup;
	/** List of SLA conditions. */
	sla_condition?: GeneralLookup;
	/** Source of the case. */
	source?: WebitelCasesSourceTypeLookup;
	/** Current status of the case. */
	status?: GeneralLookup;
	/** Status condition from status lookup. */
	status_condition?: WebitelCasesStatusCondition;
	/** Subject of the case. */
	subject?: string;
	/** Last update timestamp (in milliseconds since Unix epoch). */
	updated_at?: string;
	/** Last updater of the case. */
	updated_by?: GeneralLookup;
	/** Version number of the case. */
	ver?: number;
}
