/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { GeneralLookup } from './generalLookup';
import type { WebitelCasesCallFile } from './webitelCasesCallFile';
import type { WebitelCasesTranscriptLookup } from './webitelCasesTranscriptLookup';

export interface WebitelCasesCallEvent {
	closed_at?: string;
	duration?: string;
	files?: WebitelCasesCallFile[];
	flow_scheme?: GeneralLookup;
	gateway?: GeneralLookup;
	id?: string;
	is_detailed?: boolean;
	is_inbound?: boolean;
	is_missed?: boolean;
	participants?: GeneralLookup[];
	queue?: GeneralLookup;
	total_duration?: string;
	transcripts?: WebitelCasesTranscriptLookup[];
}
