/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelChatAgentChat } from './webitelChatAgentChat.zod';

export interface WebitelChatGetAgentChatsResponse {
	items?: WebitelChatAgentChat[];
	next?: boolean;
	page?: number;
}
