/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { GeneralLookup } from './generalLookup';

export interface WebitelCasesSLA {
	calendar?: GeneralLookup;
	created_at?: string;
	created_by?: GeneralLookup;
	description?: string;
	id?: string;
	name?: string;
	reaction_time?: string;
	resolution_time?: string;
	updated_at?: string;
	updated_by?: GeneralLookup;
	valid_from?: string;
	valid_to?: string;
}
