/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImApiGatewayV1UserFilter } from './webitelImApiGatewayV1UserFilter';

export interface WebitelImApiGatewayV1ContactSettings {
	allow_invites_from?: WebitelImApiGatewayV1UserFilter;
	contact_id?: string;
	updated_at?: string;
}
