/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelChatMessage } from './webitelChatMessage.zod';
import type { WebitelChatPeer } from './webitelChatPeer.zod';

export interface WebitelChatAgentChat {
	close_reason?: string;
	closed_at?: string;
	contact?: WebitelChatPeer;
	gateway?: WebitelChatPeer;
	id?: string;
	last_message?: WebitelChatMessage;
	queue?: WebitelChatPeer;
	started_at?: string;
	title?: string;
	unprocessed_close?: boolean;
}
