/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface WebitelImApiGatewayV1WebPushSubscriptionKey {
	auth?: string;
	p256dh?: string;
}
