/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface WebitelImApiGatewayV1SetReactionResponse {
	/** What the call did relative to the caller's previous reaction (SET, REMOVED, UNCHANGED). */
	action?: string;
	/** The emoji now stored for the caller; empty when it was removed. */
	emoji?: string;
	/** Unix time in milliseconds when the reaction was set; zero when removed. */
	reacted_at?: string;
}
