/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface WebitelImProviderV1WhatsAppBusinessAccount {
	access_token?: string;
	access_token_expires_at?: string;
	business_id?: string;
	id?: string;
	meta_app_id?: string;
	phone_number?: string;
	phone_number_id?: string;
}
