/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImApiProviderV1ProviderStatus } from './webitelImApiProviderV1ProviderStatus.zod';

export interface WebitelImApiProviderV1ProviderInstagramGate {
	business_account_id?: string;
	created_at?: string;
	enabled?: boolean;
	id?: string;
	meta_app_id?: string;
	name?: string;
	status?: WebitelImApiProviderV1ProviderStatus;
	updated_at?: string;
}
