/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelChatServerHistoryMessage } from './webitelChatServerHistoryMessage';
import type { WebitelChatServerMember } from './webitelChatServerMember';

export interface WebitelChatServerConversation {
	closed_at?: string;
	created_at?: string;
	domain_id?: string;
	id?: string;
	members?: WebitelChatServerMember[];
	messages?: WebitelChatServerHistoryMessage[];
	title?: string;
	updated_at?: string;
}
