/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

/**
 * ProviderSendMessageResponse returns the delivery status and external message ID.
 */
export interface WebitelImProviderV1ProviderSendMessageResponse {
	created_at?: string;
	external_id?: string;
}
