/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { GeneralLookup } from './generalLookup.zod';

/**
 * Space is a knowledge-base space read model.
 */
export interface WebitelKbSpace {
	/** Chunking strategy identifier. */
	chunking_strategy?: string;
	/** CreatedAt timestamp (epoch ms). */
	created_at?: string;
	/** User who created the space. */
	created_by?: GeneralLookup;
	/** Free-text description. */
	description?: string;
	/** Owning domain id. */
	domain_id?: string;
	/** Active embedding model id (type=embedding). */
	embedding_model_id?: string;
	/** Article used as the space home page; 0 if unset. */
	home_article_id?: string;
	/** Unique identifier of the space. */
	id?: string;
	/** Space language; immutable, drives full-text config and retrieval. */
	language?: string;
	/** Human-readable name. */
	name?: string;
	/** Whether reranking is applied (default off, on for suggest). */
	rerank_enabled?: boolean;
	/** Reranker model id (type=reranker). */
	reranker_model_id?: string;
	/** Target embedding model id for a pending model migration. */
	target_embedding_model_id?: string;
	/**
	 * Teams the space is bound to as default operator visibility;
	 * empty when no binding is configured.
	 */
	teams?: GeneralLookup[];
	/** UpdatedAt timestamp (epoch ms). */
	updated_at?: string;
	/** User who last updated the space. */
	updated_by?: GeneralLookup;
	/** Whether articles in this space are embedded for vector search. */
	vector_search_enabled?: boolean;
}
