/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImProviderV1ProviderViberBmGate } from './webitelImProviderV1ProviderViberBmGate';

/**
 * / ProviderCreateViberBmGateResponse returns the newly activated gateway.
 */
export interface WebitelImProviderV1ProviderCreateViberBmGateResponse {
	item?: WebitelImProviderV1ProviderViberBmGate;
}
