/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

/**
 * AttachFileRequest binds a file already uploaded to Storage.
 */
export interface WebitelKbAttachmentsAttachFileBody {
	/** Storage file id, as the upload returned it. */
	file_id?: string;
}
