/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImApiProviderV1ProviderStatus } from './webitelImApiProviderV1ProviderStatus';

export interface WebitelImApiProviderV1ProviderWhatsAppGate {
	created_at?: string;
	id?: string;
	meta_app_id?: string;
	name?: string;
	phone_display?: string;
	phone_number_id?: string;
	status?: WebitelImApiProviderV1ProviderStatus;
	updated_at?: string;
	waba_id?: string;
}
