/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImApiProviderV1Peer } from './webitelImApiProviderV1Peer';

export interface WebitelImApiProviderV1ProviderCreateFacebookGateRequest {
	enabled?: boolean;
	meta_app_id?: string;
	name?: string;
	page_id?: string;
	page_token?: string;
	peer?: WebitelImApiProviderV1Peer;
}
