/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImApiGatewayV1HistoryMessage } from './webitelImApiGatewayV1HistoryMessage';
import type { WebitelImApiGatewayV1MemberReadState } from './webitelImApiGatewayV1MemberReadState';
import type { WebitelImApiGatewayV1ThreadKind } from './webitelImApiGatewayV1ThreadKind';
import type { WebitelImApiGatewayV1ThreadMember } from './webitelImApiGatewayV1ThreadMember';
import type { WebitelImApiGatewayV1ThreadSettings } from './webitelImApiGatewayV1ThreadSettings';
import type { WebitelImApiGatewayV1ThreadVariables } from './webitelImApiGatewayV1ThreadVariables';

/**
 * Thread represents a thread (aka chat or conversation) entity.
 */
export interface WebitelImApiGatewayV1Thread {
	/** Thread creation timestamp (Unix time, milliseconds). */
	created_at?: string;
	/** Optional thread description. */
	description?: string;
	/** Unique thread identifier. */
	id?: string;
	/** Last message of the linked thread. */
	last_msg?: WebitelImApiGatewayV1HistoryMessage;
	/** Detailed member information. */
	members?: WebitelImApiGatewayV1ThreadMember[];
	/**
	 * Per-member read horizons (snapshot, matches GetUpdates model).
	 * Client derives inbox/outbox watermarks: own_last_read = inbox; MIN over others = outbox.
	 */
	read_states?: WebitelImApiGatewayV1MemberReadState[];
	/** User-specific settings for this thread. */
	settings?: WebitelImApiGatewayV1ThreadSettings;
	/** Thread subject or title. */
	subject?: string;
	/** Type of the thread. */
	type?: WebitelImApiGatewayV1ThreadKind;
	/**
	 * Number of unread messages in this thread for the calling participant.
	 * Counts content messages not yet read; the caller's own messages and
	 * system messages are excluded.
	 */
	unread_count?: number;
	/** Last update timestamp (Unix time, milliseconds). */
	updated_at?: string;
	/** The caller's GetUpdates cursor as of this read (set by Get; Search carries it on the response). */
	updates_cursor?: string;
	/** Optional variables associated with the thread. */
	variables?: WebitelImApiGatewayV1ThreadVariables;
}
