/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImProviderV1ProviderStatus } from './webitelImProviderV1ProviderStatus.zod';

export interface WebitelImProviderV1ProviderTelegramBotGate {
	created_at?: string;
	id?: string;
	name?: string;
	status?: WebitelImProviderV1ProviderStatus;
	updated_at?: string;
	uri?: string;
}
