/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImApiProviderV1ProviderMenuItem } from './webitelImApiProviderV1ProviderMenuItem';

export interface WebitelImApiProviderV1FacebookServiceSetPersistentMenuBody {
	composer_input_disabled?: boolean;
	items?: WebitelImApiProviderV1ProviderMenuItem[];
}
