/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

/**
 * Tag-filter combination mode.
 *
 *  - TAG_MATCH_ALL: Default: match articles having ALL listed tags (AND).
 *  - TAG_MATCH_ANY: Match articles having ANY listed tag (OR).
 */
export type WebitelKbTagMatch =
	(typeof WebitelKbTagMatch)[keyof typeof WebitelKbTagMatch];

export const WebitelKbTagMatch = {
	TagMatchAll: 'TAG_MATCH_ALL',
	TagMatchAny: 'TAG_MATCH_ANY',
} as const;
