/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImProviderV1ProviderType } from './webitelImProviderV1ProviderType';

/**
 * ProviderSendLocationRequest sends a geographic location.
 */
export interface WebitelImProviderV1ProviderSendLocationRequest {
	address?: string;
	domain_id?: number;
	external_user_id?: string;
	gate_id?: string;
	latitude?: number;
	longitude?: number;
	name?: string;
	reply_to_external_id?: string;
	/**
	 * Display name of the operator (or bot) this message is from, when the channel can
	 * show a per-message sender. Empty means "use the gate's own name".
	 */
	sender_name?: string;
	type?: WebitelImProviderV1ProviderType;
}
