/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelCasesCloseReasonGroup } from './webitelCasesCloseReasonGroup.zod';

export interface WebitelCasesLocateCloseReasonGroupResponse {
	close_reason_group?: WebitelCasesCloseReasonGroup;
}
