/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface WebitelImApiGatewayV1MessageEditMessageBody {
	/** New content for the message. Must not be empty. */
	body?: string;
}
