/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImProviderV1ProviderViberBmGate } from './webitelImProviderV1ProviderViberBmGate';

export interface WebitelImProviderV1ProviderDeleteViberBmGateResponse {
	item?: WebitelImProviderV1ProviderViberBmGate;
}
