/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImProviderV1ViberBmServiceSendViberBmTemplateBodyParameters } from './webitelImProviderV1ViberBmServiceSendViberBmTemplateBodyParameters';

/**
 * / SendViberBmTemplateRequest sends an approved cold-start template.
 */
export interface WebitelImProviderV1ViberBmServiceSendViberBmTemplateBody {
	parameters?: WebitelImProviderV1ViberBmServiceSendViberBmTemplateBodyParameters;
	language?: string;
	template_id?: string;
	to?: string;
}
