/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImApiGatewayV1Peer } from './webitelImApiGatewayV1Peer';
import type { WebitelImApiGatewayV1PeerIdentity } from './webitelImApiGatewayV1PeerIdentity';

/**
 * SendInternalNoteRequest posts an operator-only note into the thread. The
 * sender is taken from the caller's identity; internal-only, no external fields.
 */
export interface WebitelImApiGatewayV1SendInternalNoteRequest {
	body?: string;
	reply_to_message_id?: string;
	send_as?: WebitelImApiGatewayV1PeerIdentity;
	send_id?: string;
	to?: WebitelImApiGatewayV1Peer;
}
