/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImApiProviderV1ProviderInteractive } from './webitelImApiProviderV1ProviderInteractive.zod';

export interface WebitelImApiProviderV1ProviderSendInteractiveRequest {
	body?: string;
	domain_id?: number;
	external_user_id?: string;
	gate_id?: string;
	interactive?: WebitelImApiProviderV1ProviderInteractive;
	send_id?: string;
}
