/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImApiProviderV1ProviderMetaLinkedPage } from './webitelImApiProviderV1ProviderMetaLinkedPage.zod';

export interface WebitelImApiProviderV1ProviderMetaOAuthCallbackResponse {
	pages?: WebitelImApiProviderV1ProviderMetaLinkedPage[];
	user_access_token?: string;
}
