/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImApiGatewayV1Document } from './webitelImApiGatewayV1Document.zod';
import type { WebitelImApiGatewayV1ForwardOrigin } from './webitelImApiGatewayV1ForwardOrigin.zod';
import type { WebitelImApiGatewayV1HistoryMessageMetadata } from './webitelImApiGatewayV1HistoryMessageMetadata.zod';
import type { WebitelImApiGatewayV1Image } from './webitelImApiGatewayV1Image.zod';
import type { WebitelImApiGatewayV1Interactive } from './webitelImApiGatewayV1Interactive.zod';
import type { WebitelImApiGatewayV1InteractiveCallback } from './webitelImApiGatewayV1InteractiveCallback.zod';
import type { WebitelImApiGatewayV1MessageContact } from './webitelImApiGatewayV1MessageContact.zod';
import type { WebitelImApiGatewayV1MessageDeliveryStatus } from './webitelImApiGatewayV1MessageDeliveryStatus.zod';
import type { WebitelImApiGatewayV1MessageLocation } from './webitelImApiGatewayV1MessageLocation.zod';
import type { WebitelImApiGatewayV1MessageReaction } from './webitelImApiGatewayV1MessageReaction.zod';
import type { WebitelImApiGatewayV1MessageRecipientStatus } from './webitelImApiGatewayV1MessageRecipientStatus.zod';
import type { WebitelImApiGatewayV1ReplyToMessage } from './webitelImApiGatewayV1ReplyToMessage.zod';
import type { WebitelImApiGatewayV1System } from './webitelImApiGatewayV1System.zod';
import type { WebitelImApiGatewayV1ThreadMember } from './webitelImApiGatewayV1ThreadMember.zod';

/**
 * HistoryMessage represents a single message
 * in thread history.
 */
export interface WebitelImApiGatewayV1HistoryMessage {
	/** Message body content. */
	body?: string;
	contact?: WebitelImApiGatewayV1MessageContact;
	/** Message creation timestamp (Unix time, milliseconds). */
	created_at?: string;
	/**
	 * True when the message was deleted by its author. Every content field
	 * (body, attachments, contact, location, interactive, metadata) is cleared,
	 * so clients should render a tombstone.
	 */
	deleted?: boolean;
	/** Unix time in milliseconds when the message was deleted. */
	deleted_at?: string;
	/** Contact id of the member who deleted the message; empty when it is live. */
	deleted_by?: string;
	/**
	 * Aggregated delivery status across recipients: FAILED when every
	 * recipient failed, otherwise the minimal status among non-failed ones.
	 * UNSPECIFIED for messages without per-recipient tracking (historical).
	 */
	delivery_status?: WebitelImApiGatewayV1MessageDeliveryStatus;
	/** List of document attachments. */
	documents?: WebitelImApiGatewayV1Document[];
	/** Message last update timestamp (Unix time, milliseconds). */
	edited_at?: string;
	/**
	 * Set when this message is a forward. Never populated for a deleted
	 * message: the tombstone must not leak the origin name.
	 */
	forward_origin?: WebitelImApiGatewayV1ForwardOrigin;
	/** Unique message identifier. */
	id?: string;
	/** List of image attachments. */
	images?: WebitelImApiGatewayV1Image[];
	interactive?: WebitelImApiGatewayV1Interactive;
	location?: WebitelImApiGatewayV1MessageLocation;
	/**
	 * Arbitrary message metadata.
	 * Can contain structured data depending on message type.
	 */
	metadata?: WebitelImApiGatewayV1HistoryMessageMetadata;
	/** Metadata for button reaction for interactive message. */
	reacted_metadata?: WebitelImApiGatewayV1InteractiveCallback;
	/** Emoji reactions currently held on the message, aggregated per emoji. */
	reactions?: WebitelImApiGatewayV1MessageReaction[];
	reply_to?: WebitelImApiGatewayV1ReplyToMessage;
	/**
	 * Number of entries in the message's change history. Zero means the message
	 * was never edited or deleted; otherwise GetMessageRevisions returns that
	 * many entries.
	 */
	revision_count?: number;
	/** Sender user aggregated information. */
	sender?: WebitelImApiGatewayV1ThreadMember;
	/** Per-thread monotonic sequence number, assigned on message creation. */
	seq?: string;
	/** Per-recipient delivery details. */
	statuses?: WebitelImApiGatewayV1MessageRecipientStatus[];
	/** System message content. */
	system?: WebitelImApiGatewayV1System;
	/** Identifier of the thread the message belongs to. */
	thread_id?: string;
	/** Message type identifier. */
	type?: number;
}
