/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { GoogleProtobufAny } from './googleProtobufAny';

export interface WebitelPortalUpdate {
	data?: GoogleProtobufAny;
	/** Date when this update was sent. */
	date?: string;
}
