/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelPortalWebPush } from './webitelPortalWebPush.zod';

export interface WebitelPortalDevicePush {
	APN?: string;
	FCM?: string;
	secret?: string;
	web?: WebitelPortalWebPush;
}
