/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImProviderV1ProviderInstagramGate } from './webitelImProviderV1ProviderInstagramGate';

/**
 * / ProviderCreateInstagramGateResponse returns the newly activated Instagram provider.
 */
export interface WebitelImProviderV1ProviderCreateInstagramGateResponse {
	item?: WebitelImProviderV1ProviderInstagramGate;
}
