/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImApiProviderV1Peer } from './webitelImApiProviderV1Peer';

export interface WebitelImApiProviderV1InstagramServiceUpdateInstagramGateBody {
	business_account_token?: string;
	enabled?: boolean;
	name?: string;
	peer?: WebitelImApiProviderV1Peer;
}
