/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelKbInputSpace } from './webitelKbInputSpace';

/**
 * Updated space fields.
 */
export type WebitelKbInputSpaceBody = WebitelKbInputSpace;
