/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImProviderV1Peer } from './webitelImProviderV1Peer';

/**
 * / ProviderCreateInstagramGateRequest links a specific Instagram Business Account as a messaging gateway.
 */
export interface WebitelImProviderV1ProviderCreateInstagramGateRequest {
	business_account_id?: string;
	business_account_token?: string;
	enabled?: boolean;
	meta_app_id?: string;
	name?: string;
	peer?: WebitelImProviderV1Peer;
}
