/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImProviderV1ProviderCustomGate } from './webitelImProviderV1ProviderCustomGate';

/**
 * / ProviderCreateCustomGateResponse returns the newly activated custom provider.
 */
export interface WebitelImProviderV1ProviderCreateCustomGateResponse {
	item?: WebitelImProviderV1ProviderCustomGate;
}
