/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface WebitelImApiGatewayV1ChatTag {
	created_at?: string;
	id?: string;
	tag?: string;
	thread_id?: string;
}
