/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImProviderV1ProviderViberGate } from './webitelImProviderV1ProviderViberGate.zod';

/**
 * / ProviderUpdateViberGateResponse returns the updated Viber provider.
 */
export interface WebitelImProviderV1ProviderUpdateViberGateResponse {
	item?: WebitelImProviderV1ProviderViberGate;
}
