/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export interface WebitelImProviderV1CreateWABAGateRequest {
	access_token?: string;
	business_id?: string;
	meta_app_id?: string;
	phone_number?: string;
	phone_number_id?: string;
}
