/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelKbInputEmbeddingModel } from './webitelKbInputEmbeddingModel';

/**
 * Updated model fields.
 */
export type WebitelKbInputEmbeddingModelBody = WebitelKbInputEmbeddingModel;
