/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

export type WebitelCasesCallFileType =
	(typeof WebitelCasesCallFileType)[keyof typeof WebitelCasesCallFileType];

export const WebitelCasesCallFileType = {
	FileTypeEmpty: 'file_type_empty',
	FileTypeScreenshot: 'file_type_screenshot',
	FileTypeScreensharing: 'file_type_screensharing',
	FileTypeAudio: 'file_type_audio',
	FileTypeVideo: 'file_type_video',
	FileTypePdf: 'file_type_pdf',
} as const;
