/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelChatServerHistoryMessage } from './webitelChatServerHistoryMessage.zod';
import type { WebitelChatServerMember } from './webitelChatServerMember.zod';

export interface WebitelChatServerConversation {
	closed_at?: string;
	created_at?: string;
	domain_id?: string;
	id?: string;
	members?: WebitelChatServerMember[];
	messages?: WebitelChatServerHistoryMessage[];
	title?: string;
	updated_at?: string;
}
