/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImApiProviderV1ProviderKeyboardRowWithSection } from './webitelImApiProviderV1ProviderKeyboardRowWithSection';

export interface WebitelImApiProviderV1ProviderKeyboardListReply {
	main_button_title?: string;
	sections?: WebitelImApiProviderV1ProviderKeyboardRowWithSection[];
}
