/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

/**
 * ThreadDirectSettings defines settings
 * specific to direct (one-to-one) threads.
 */
export interface WebitelImApiGatewayV1ThreadSettings {
	/** Creation timestamp (Unix time, milliseconds). */
	created_at?: string;
	/** Domain identifier. */
	domain_id?: number;
	/** Settings identifier. */
	id?: string;
	/**
	 * Custom title for the direct thread.
	 * Usually represents the display name of the conversation.
	 */
	title?: string;
	/** Last update timestamp (Unix time, milliseconds). */
	updated_at?: string;
}
