/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { GeneralLookup } from './generalLookup.zod';
import type { WebitelCasesRelationType } from './webitelCasesRelationType.zod';

/**
 * Input for creating a related case.
 */
export interface WebitelCasesCreateInputRelatedCase {
	/** Related case details. */
	related_case?: GeneralLookup;
	/** Relation type between the cases. */
	relation_type?: WebitelCasesRelationType;
	/** Optional creator / updater ID. Use this to explicitly set the case creator / updater instead of deriving it from the auth token. */
	userID?: GeneralLookup;
}
