/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImProviderV1ProviderInstagramGate } from './webitelImProviderV1ProviderInstagramGate';

export interface WebitelImProviderV1ProviderDeleteInstagramGateResponse {
	item?: WebitelImProviderV1ProviderInstagramGate;
}
