/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */

/**
 * InputEmbeddingModel carries the writable fields of a model.
 */
export interface WebitelKbInputEmbeddingModel {
	/** Write-only provider credential; encrypted at rest, never read back. */
	api_key?: string;
	/** Embedding dimension; omit for rerankers. */
	dimensions?: number;
	/** Self-hosted / Azure / BYOM endpoint url. */
	endpoint?: string;
	/** Whether the model runs self-hosted. */
	is_self_hosted?: boolean;
	/** Provider model name or HuggingFace id. */
	model_ref?: string;
	/** Human-readable name. */
	name?: string;
	/** Provider key. */
	provider?: string;
	/** Model type: "embedding" or "reranker". */
	type?: string;
}
