/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelImApiGatewayV1Peer } from './webitelImApiGatewayV1Peer.zod';
import type { WebitelImApiGatewayV1PeerIdentity } from './webitelImApiGatewayV1PeerIdentity.zod';

export interface WebitelImApiGatewayV1ForwardMessagesRequest {
	/**
	 * Optional internal note posted alongside the forward — visible only to
	 * Webitel users, never delivered to the client.
	 */
	internal_note?: string;
	/** Sources to copy, in the order they should appear at the destination. */
	message_ids?: string[];
	send_as?: WebitelImApiGatewayV1PeerIdentity;
	send_id?: string;
	/** Recipient of the copies: a user contact or a bot contact (flow schema). */
	to?: WebitelImApiGatewayV1Peer;
}
