/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebitelCasesCatalog } from './webitelCasesCatalog.zod';

export interface WebitelCasesLocateCatalogResponse {
	catalog?: WebitelCasesCatalog;
}
