/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WebMeetingBackendCreateMeetingRequestVariables } from './webMeetingBackendCreateMeetingRequestVariables.zod';

/**
 * Request to create a new meeting.
 */
export interface WebMeetingBackendCreateMeetingRequest {
	/** Base path for the generated meeting URL. */
	base_path?: string;
	/** Identifier of the domain owning the meeting. */
	domain_id?: string;
	/** Expiration time in seconds from the moment of creation. */
	expire_sec?: string;
	/** Title or topic of the meeting. */
	title?: string;
	/** Custom metadata or configuration variables. */
	variables?: WebMeetingBackendCreateMeetingRequestVariables;
}
