/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WfmLookupEntity } from './wfmLookupEntity';

export interface WfmAgentScheduleShiftPause {
	cause?: WfmLookupEntity;
	created_at?: string;
	created_by?: WfmLookupEntity;
	domain_id?: string;
	end?: string;
	id?: string;
	start?: string;
	updated_at?: string;
	updated_by?: WfmLookupEntity;
}
