/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WfmAgentScheduleShiftPause } from './wfmAgentScheduleShiftPause';
import type { WfmAgentScheduleShiftSkill } from './wfmAgentScheduleShiftSkill';
import type { WfmLookupEntity } from './wfmLookupEntity';

export interface WfmAgentScheduleShift {
	created_at?: string;
	created_by?: WfmLookupEntity;
	domain_id?: string;
	end?: string;
	id?: string;
	pauses?: WfmAgentScheduleShiftPause[];
	skills?: WfmAgentScheduleShiftSkill[];
	start?: string;
	updated_at?: string;
	updated_by?: WfmLookupEntity;
}
