/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WfmAbsenceType } from './wfmAbsenceType';
import type { WfmLookupEntity } from './wfmLookupEntity';

export interface WfmAbsence {
	absent_at?: string;
	created_at?: string;
	created_by?: WfmLookupEntity;
	domain_id?: string;
	id?: string;
	type_id?: WfmAbsenceType;
	updated_at?: string;
	updated_by?: WfmLookupEntity;
}
