/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WfmReadWorkingScheduleForecastResponseItems } from './wfmReadWorkingScheduleForecastResponseItems';

export interface WfmReadWorkingScheduleForecastResponse {
	items?: WfmReadWorkingScheduleForecastResponseItems;
}
