/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WfmAgentAbsences } from './wfmAgentAbsences.zod';

export interface WfmSearchAgentsAbsencesResponse {
	items?: WfmAgentAbsences[];
	next?: boolean;
}
