/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WfmLookupEntity } from './wfmLookupEntity.zod';
import type { WfmWorkingScheduleState } from './wfmWorkingScheduleState.zod';

export interface WfmWorkingSchedule {
	agents?: WfmLookupEntity[];
	block_outside_activity?: boolean;
	calendar?: WfmLookupEntity;
	created_at?: string;
	created_by?: WfmLookupEntity;
	domain_id?: string;
	end_date_at?: string;
	end_time_at?: string;
	extra_skills?: WfmLookupEntity[];
	id?: string;
	name?: string;
	start_date_at?: string;
	start_time_at?: string;
	state?: WfmWorkingScheduleState;
	team?: WfmLookupEntity;
	total_agents?: string;
	updated_at?: string;
	updated_by?: WfmLookupEntity;
}
