/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { WfmLookupEntity } from './wfmLookupEntity.zod';

export interface WfmWorkingCondition {
	created_at?: string;
	created_by?: WfmLookupEntity;
	days_off?: number;
	description?: string;
	domain_id?: string;
	id?: string;
	name?: string;
	pause_duration?: number;
	pause_template?: WfmLookupEntity;
	shift_template?: WfmLookupEntity;
	sick_leaves?: number;
	updated_at?: string;
	updated_by?: WfmLookupEntity;
	vacation?: number;
	workday_hours?: number;
	workdays_per_month?: number;
}
