/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

export const SearchQueryParams = zod.object({
	page: zod.int().optional(),
	size: zod.int().optional(),
	q: zod.string().optional(),
	sort: zod.string().optional(),
	fields: zod.array(zod.string()).optional(),
	object_name: zod.array(zod.string()).optional(),
});

export const SearchResponse = zod.object({
	items: zod
		.array(
			zod.object({
				id: zod.string().optional(),
				object_name: zod.string().optional(),
				text: zod.string().optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});
