/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

/**
 * @summary List of FilePolicy
 */
export const SearchFilePoliciesQueryParams = zod.object({
	page: zod.int().optional(),
	size: zod.int().optional(),
	q: zod.string().optional(),
	sort: zod.string().optional(),
	fields: zod.array(zod.string()).optional(),
	id: zod.array(zod.int()).optional(),
});

export const searchFilePoliciesResponseItemsItemChannelsItemDefault = `UnknownChannel`;

export const SearchFilePoliciesResponse = zod.object({
	items: zod
		.array(
			zod.object({
				channels: zod
					.array(
						zod
							.enum([
								'UnknownChannel',
								'ChatChannel',
								'MailChannel',
								'CallChannel',
								'LogChannel',
								'MediaChannel',
								'KnowledgebaseChannel',
								'CasesChannel',
								'ScreenRecordingChannel',
							])
							.default(searchFilePoliciesResponseItemsItemChannelsItemDefault),
					)
					.optional(),
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				description: zod.string().optional(),
				enabled: zod.boolean().optional(),
				encrypt: zod.boolean().optional(),
				id: zod.int().optional(),
				max_upload_size: zod.string().optional(),
				mime_types: zod.array(zod.string()).optional(),
				name: zod.string().optional(),
				position: zod.int().optional(),
				retention_days: zod.int().optional(),
				speed_download: zod.string().optional(),
				speed_upload: zod.string().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});

/**
 * @summary Create FilePolicy
 */
export const createFilePolicyBodyChannelsItemDefault = `UnknownChannel`;

export const CreateFilePolicyBody = zod.object({
	channels: zod
		.array(
			zod
				.enum([
					'UnknownChannel',
					'ChatChannel',
					'MailChannel',
					'CallChannel',
					'LogChannel',
					'MediaChannel',
					'KnowledgebaseChannel',
					'CasesChannel',
					'ScreenRecordingChannel',
				])
				.default(createFilePolicyBodyChannelsItemDefault),
		)
		.optional(),
	description: zod.string().optional(),
	enabled: zod.boolean().optional(),
	encrypt: zod.boolean().optional(),
	max_upload_size: zod.string().optional(),
	mime_types: zod.array(zod.string()).optional(),
	name: zod.string().optional(),
	retention_days: zod.int().optional(),
	speed_download: zod.string().optional(),
	speed_upload: zod.string().optional(),
});

export const createFilePolicyResponseChannelsItemDefault = `UnknownChannel`;

export const CreateFilePolicyResponse = zod.object({
	channels: zod
		.array(
			zod
				.enum([
					'UnknownChannel',
					'ChatChannel',
					'MailChannel',
					'CallChannel',
					'LogChannel',
					'MediaChannel',
					'KnowledgebaseChannel',
					'CasesChannel',
					'ScreenRecordingChannel',
				])
				.default(createFilePolicyResponseChannelsItemDefault),
		)
		.optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	enabled: zod.boolean().optional(),
	encrypt: zod.boolean().optional(),
	id: zod.int().optional(),
	max_upload_size: zod.string().optional(),
	mime_types: zod.array(zod.string()).optional(),
	name: zod.string().optional(),
	position: zod.int().optional(),
	retention_days: zod.int().optional(),
	speed_download: zod.string().optional(),
	speed_upload: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const MovePositionFilePolicyParams = zod.object({
	from_id: zod.int(),
	to_id: zod.int(),
});

export const MovePositionFilePolicyBody = zod.looseObject({});

export const MovePositionFilePolicyResponse = zod.object({
	success: zod.boolean().optional(),
});

/**
 * @summary Remove FilePolicy
 */
export const DeleteFilePolicyParams = zod.object({
	id: zod.int(),
});

export const deleteFilePolicyResponseChannelsItemDefault = `UnknownChannel`;

export const DeleteFilePolicyResponse = zod.object({
	channels: zod
		.array(
			zod
				.enum([
					'UnknownChannel',
					'ChatChannel',
					'MailChannel',
					'CallChannel',
					'LogChannel',
					'MediaChannel',
					'KnowledgebaseChannel',
					'CasesChannel',
					'ScreenRecordingChannel',
				])
				.default(deleteFilePolicyResponseChannelsItemDefault),
		)
		.optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	enabled: zod.boolean().optional(),
	encrypt: zod.boolean().optional(),
	id: zod.int().optional(),
	max_upload_size: zod.string().optional(),
	mime_types: zod.array(zod.string()).optional(),
	name: zod.string().optional(),
	position: zod.int().optional(),
	retention_days: zod.int().optional(),
	speed_download: zod.string().optional(),
	speed_upload: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary FilePolicy item
 */
export const ReadFilePolicyParams = zod.object({
	id: zod.int(),
});

export const readFilePolicyResponseChannelsItemDefault = `UnknownChannel`;

export const ReadFilePolicyResponse = zod.object({
	channels: zod
		.array(
			zod
				.enum([
					'UnknownChannel',
					'ChatChannel',
					'MailChannel',
					'CallChannel',
					'LogChannel',
					'MediaChannel',
					'KnowledgebaseChannel',
					'CasesChannel',
					'ScreenRecordingChannel',
				])
				.default(readFilePolicyResponseChannelsItemDefault),
		)
		.optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	enabled: zod.boolean().optional(),
	encrypt: zod.boolean().optional(),
	id: zod.int().optional(),
	max_upload_size: zod.string().optional(),
	mime_types: zod.array(zod.string()).optional(),
	name: zod.string().optional(),
	position: zod.int().optional(),
	retention_days: zod.int().optional(),
	speed_download: zod.string().optional(),
	speed_upload: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary Patch FilePolicy
 */
export const PatchFilePolicyParams = zod.object({
	id: zod.int(),
});

export const patchFilePolicyBodyChannelsItemDefault = `UnknownChannel`;

export const PatchFilePolicyBody = zod.object({
	channels: zod
		.array(
			zod
				.enum([
					'UnknownChannel',
					'ChatChannel',
					'MailChannel',
					'CallChannel',
					'LogChannel',
					'MediaChannel',
					'KnowledgebaseChannel',
					'CasesChannel',
					'ScreenRecordingChannel',
				])
				.default(patchFilePolicyBodyChannelsItemDefault),
		)
		.optional(),
	description: zod.string().optional(),
	enabled: zod.boolean().optional(),
	encrypt: zod.boolean().optional(),
	fields: zod.array(zod.string()).optional(),
	max_upload_size: zod.string().optional(),
	mime_types: zod.array(zod.string()).optional(),
	name: zod.string().optional(),
	retention_days: zod.int().optional(),
	speed_download: zod.string().optional(),
	speed_upload: zod.string().optional(),
});

export const patchFilePolicyResponseChannelsItemDefault = `UnknownChannel`;

export const PatchFilePolicyResponse = zod.object({
	channels: zod
		.array(
			zod
				.enum([
					'UnknownChannel',
					'ChatChannel',
					'MailChannel',
					'CallChannel',
					'LogChannel',
					'MediaChannel',
					'KnowledgebaseChannel',
					'CasesChannel',
					'ScreenRecordingChannel',
				])
				.default(patchFilePolicyResponseChannelsItemDefault),
		)
		.optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	enabled: zod.boolean().optional(),
	encrypt: zod.boolean().optional(),
	id: zod.int().optional(),
	max_upload_size: zod.string().optional(),
	mime_types: zod.array(zod.string()).optional(),
	name: zod.string().optional(),
	position: zod.int().optional(),
	retention_days: zod.int().optional(),
	speed_download: zod.string().optional(),
	speed_upload: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

/**
 * @summary Update FilePolicy
 */
export const UpdateFilePolicyParams = zod.object({
	id: zod.int(),
});

export const updateFilePolicyBodyChannelsItemDefault = `UnknownChannel`;

export const UpdateFilePolicyBody = zod.object({
	channels: zod
		.array(
			zod
				.enum([
					'UnknownChannel',
					'ChatChannel',
					'MailChannel',
					'CallChannel',
					'LogChannel',
					'MediaChannel',
					'KnowledgebaseChannel',
					'CasesChannel',
					'ScreenRecordingChannel',
				])
				.default(updateFilePolicyBodyChannelsItemDefault),
		)
		.optional(),
	description: zod.string().optional(),
	enabled: zod.boolean().optional(),
	encrypt: zod.boolean().optional(),
	max_upload_size: zod.string().optional(),
	mime_types: zod.array(zod.string()).optional(),
	name: zod.string().optional(),
	retention_days: zod.int().optional(),
	speed_download: zod.string().optional(),
	speed_upload: zod.string().optional(),
});

export const updateFilePolicyResponseChannelsItemDefault = `UnknownChannel`;

export const UpdateFilePolicyResponse = zod.object({
	channels: zod
		.array(
			zod
				.enum([
					'UnknownChannel',
					'ChatChannel',
					'MailChannel',
					'CallChannel',
					'LogChannel',
					'MediaChannel',
					'KnowledgebaseChannel',
					'CasesChannel',
					'ScreenRecordingChannel',
				])
				.default(updateFilePolicyResponseChannelsItemDefault),
		)
		.optional(),
	created_at: zod.string().optional(),
	created_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
	description: zod.string().optional(),
	enabled: zod.boolean().optional(),
	encrypt: zod.boolean().optional(),
	id: zod.int().optional(),
	max_upload_size: zod.string().optional(),
	mime_types: zod.array(zod.string()).optional(),
	name: zod.string().optional(),
	position: zod.int().optional(),
	retention_days: zod.int().optional(),
	speed_download: zod.string().optional(),
	speed_upload: zod.string().optional(),
	updated_at: zod.string().optional(),
	updated_by: zod
		.object({
			id: zod.string().optional(),
			name: zod.string().optional(),
		})
		.optional(),
});

export const FilePolicyApplyParams = zod.object({
	id: zod.int(),
});

export const FilePolicyApplyBody = zod.object({
	apply_to_null_channel: zod.boolean().optional(),
});

export const FilePolicyApplyResponse = zod.object({
	count: zod.string().optional(),
});
