/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

/**
 * @summary / ListViberBm returns the Viber BM gateways configured for the caller's domain.
 */
export const ViberBmServiceListViberBmQueryParams = zod.object({
	page: zod.int().optional(),
	size: zod.int().optional(),
	q: zod.string().optional(),
});

export const viberBmServiceListViberBmResponseItemsItemStatusDefault = `PROVIDER_STATUS_UNSPECIFIED`;

export const ViberBmServiceListViberBmResponse = zod
	.object({
		items: zod
			.array(
				zod
					.object({
						base_url: zod.string().optional(),
						created_at: zod.string().optional(),
						enabled: zod.boolean().optional(),
						id: zod.string().optional(),
						name: zod.string().optional(),
						sender_name: zod.string().optional(),
						status: zod
							.enum([
								'PROVIDER_STATUS_UNSPECIFIED',
								'PROVIDER_STATUS_ACTIVE',
								'PROVIDER_STATUS_INACTIVE',
								'PROVIDER_STATUS_ERROR',
							])
							.default(viberBmServiceListViberBmResponseItemsItemStatusDefault)
							.describe(
								'/ ProviderStatus represents the operational state of a provider gateway.\n\n - PROVIDER_STATUS_ACTIVE: Provider is healthy and processing messages\n - PROVIDER_STATUS_INACTIVE: Manually disabled by user\n - PROVIDER_STATUS_ERROR: Connection or authentication failed',
							),
						updated_at: zod.string().optional(),
						webhook_url: zod.string().optional(),
					})
					.describe(
						'/ ProviderViberBmGate is a configured InfoBip Viber BM gateway.',
					),
			)
			.optional(),
		next: zod.boolean().optional(),
	})
	.describe(
		'/ ProviderListViberBmGatesResponse returns the configured gateways.',
	);

/**
 * @summary / CreateViberBm registers an InfoBip Viber BM account as a messaging gateway.
 */
export const ViberBmServiceCreateViberBmBody = zod
	.object({
		api_key: zod.string().optional(),
		base_url: zod.string().optional(),
		enabled: zod.boolean().optional(),
		name: zod.string().optional(),
		peer: zod
			.object({
				iss: zod.string().optional(),
				sub: zod.string().optional(),
			})
			.optional(),
		sender_name: zod.string().optional(),
		webhook_secret: zod.string().optional(),
	})
	.describe(
		'/ ProviderCreateViberBmGateRequest registers an InfoBip Viber BM account.',
	);

export const viberBmServiceCreateViberBmResponseItemStatusDefault = `PROVIDER_STATUS_UNSPECIFIED`;

export const ViberBmServiceCreateViberBmResponse = zod
	.object({
		item: zod
			.object({
				base_url: zod.string().optional(),
				created_at: zod.string().optional(),
				enabled: zod.boolean().optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				sender_name: zod.string().optional(),
				status: zod
					.enum([
						'PROVIDER_STATUS_UNSPECIFIED',
						'PROVIDER_STATUS_ACTIVE',
						'PROVIDER_STATUS_INACTIVE',
						'PROVIDER_STATUS_ERROR',
					])
					.default(viberBmServiceCreateViberBmResponseItemStatusDefault)
					.describe(
						'/ ProviderStatus represents the operational state of a provider gateway.\n\n - PROVIDER_STATUS_ACTIVE: Provider is healthy and processing messages\n - PROVIDER_STATUS_INACTIVE: Manually disabled by user\n - PROVIDER_STATUS_ERROR: Connection or authentication failed',
					),
				updated_at: zod.string().optional(),
				webhook_url: zod.string().optional(),
			})
			.optional()
			.describe(
				'/ ProviderViberBmGate is a configured InfoBip Viber BM gateway.',
			),
	})
	.describe(
		'/ ProviderCreateViberBmGateResponse returns the newly activated gateway.',
	);

/**
 * @summary / SendViberBmTemplate sends an approved, business-initiated template message
/ for cold-start outreach (no open 24h session). templateId must reference a
/ registered, Viber-approved transactional template.
 */
export const ViberBmServiceSendViberBmTemplateParams = zod.object({
	gate_id_1: zod.string(),
});

export const ViberBmServiceSendViberBmTemplateBody = zod
	.object({
		parameters: zod.record(zod.string(), zod.string()).optional(),
		language: zod.string().optional(),
		template_id: zod.string().optional(),
		to: zod.string().optional(),
	})
	.describe(
		'/ SendViberBmTemplateRequest sends an approved cold-start template.',
	);

export const ViberBmServiceSendViberBmTemplateResponse = zod
	.object({
		bulk_id: zod.string().optional(),
		message_id: zod.string().optional(),
	})
	.describe('/ SendViberBmTemplateResponse confirms the template dispatch.');

/**
 * @summary / DeleteViberBm removes the Viber BM gateway integration.
 */
export const ViberBmServiceDeleteViberBmParams = zod.object({
	id_1: zod.string(),
});

export const viberBmServiceDeleteViberBmResponseItemStatusDefault = `PROVIDER_STATUS_UNSPECIFIED`;

export const ViberBmServiceDeleteViberBmResponse = zod.object({
	item: zod
		.object({
			base_url: zod.string().optional(),
			created_at: zod.string().optional(),
			enabled: zod.boolean().optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			sender_name: zod.string().optional(),
			status: zod
				.enum([
					'PROVIDER_STATUS_UNSPECIFIED',
					'PROVIDER_STATUS_ACTIVE',
					'PROVIDER_STATUS_INACTIVE',
					'PROVIDER_STATUS_ERROR',
				])
				.default(viberBmServiceDeleteViberBmResponseItemStatusDefault)
				.describe(
					'/ ProviderStatus represents the operational state of a provider gateway.\n\n - PROVIDER_STATUS_ACTIVE: Provider is healthy and processing messages\n - PROVIDER_STATUS_INACTIVE: Manually disabled by user\n - PROVIDER_STATUS_ERROR: Connection or authentication failed',
				),
			updated_at: zod.string().optional(),
			webhook_url: zod.string().optional(),
		})
		.optional()
		.describe(
			'/ ProviderViberBmGate is a configured InfoBip Viber BM gateway.',
		),
});

/**
 * @summary / GetViberBm retrieves configuration and status for a Viber BM gateway.
 */
export const ViberBmServiceGetViberBmParams = zod.object({
	id_1: zod.string(),
});

export const viberBmServiceGetViberBmResponseItemStatusDefault = `PROVIDER_STATUS_UNSPECIFIED`;

export const ViberBmServiceGetViberBmResponse = zod.object({
	item: zod
		.object({
			base_url: zod.string().optional(),
			created_at: zod.string().optional(),
			enabled: zod.boolean().optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			sender_name: zod.string().optional(),
			status: zod
				.enum([
					'PROVIDER_STATUS_UNSPECIFIED',
					'PROVIDER_STATUS_ACTIVE',
					'PROVIDER_STATUS_INACTIVE',
					'PROVIDER_STATUS_ERROR',
				])
				.default(viberBmServiceGetViberBmResponseItemStatusDefault)
				.describe(
					'/ ProviderStatus represents the operational state of a provider gateway.\n\n - PROVIDER_STATUS_ACTIVE: Provider is healthy and processing messages\n - PROVIDER_STATUS_INACTIVE: Manually disabled by user\n - PROVIDER_STATUS_ERROR: Connection or authentication failed',
				),
			updated_at: zod.string().optional(),
			webhook_url: zod.string().optional(),
		})
		.optional()
		.describe(
			'/ ProviderViberBmGate is a configured InfoBip Viber BM gateway.',
		),
});

/**
 * @summary / UpdateViberBm updates Viber BM gateway settings.
 */
export const ViberBmServiceUpdateViberBmParams = zod.object({
	id_1: zod.string(),
});

export const ViberBmServiceUpdateViberBmBody = zod
	.object({
		api_key: zod.string().optional(),
		base_url: zod.string().optional(),
		enabled: zod.boolean().optional(),
		name: zod.string().optional(),
		peer: zod
			.object({
				iss: zod.string().optional(),
				sub: zod.string().optional(),
			})
			.optional(),
		sender_name: zod.string().optional(),
		webhook_secret: zod.string().optional(),
	})
	.describe(
		'/ ProviderUpdateViberBmGateRequest updates settings. A non-empty api_key rotates the key.',
	);

export const viberBmServiceUpdateViberBmResponseItemStatusDefault = `PROVIDER_STATUS_UNSPECIFIED`;

export const ViberBmServiceUpdateViberBmResponse = zod
	.object({
		item: zod
			.object({
				base_url: zod.string().optional(),
				created_at: zod.string().optional(),
				enabled: zod.boolean().optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				sender_name: zod.string().optional(),
				status: zod
					.enum([
						'PROVIDER_STATUS_UNSPECIFIED',
						'PROVIDER_STATUS_ACTIVE',
						'PROVIDER_STATUS_INACTIVE',
						'PROVIDER_STATUS_ERROR',
					])
					.default(viberBmServiceUpdateViberBmResponseItemStatusDefault)
					.describe(
						'/ ProviderStatus represents the operational state of a provider gateway.\n\n - PROVIDER_STATUS_ACTIVE: Provider is healthy and processing messages\n - PROVIDER_STATUS_INACTIVE: Manually disabled by user\n - PROVIDER_STATUS_ERROR: Connection or authentication failed',
					),
				updated_at: zod.string().optional(),
				webhook_url: zod.string().optional(),
			})
			.optional()
			.describe(
				'/ ProviderViberBmGate is a configured InfoBip Viber BM gateway.',
			),
	})
	.describe('/ ProviderUpdateViberBmGateResponse returns the updated gateway.');
