/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

export const AgentWorkingScheduleServiceSearchAgentsWorkingScheduleParams =
	zod.object({
		working_schedule_id: zod.string(),
	});

export const AgentWorkingScheduleServiceSearchAgentsWorkingScheduleQueryParams =
	zod.object({
		'date.from': zod.string().optional(),
		'date.to': zod.string().optional(),
		supervisor_id: zod.array(zod.string()).optional(),
		team_id: zod.array(zod.string()).optional(),
		skill_id: zod.array(zod.string()).optional(),
		q: zod.string().optional(),
	});

export const agentWorkingScheduleServiceSearchAgentsWorkingScheduleResponseItemsItemScheduleItemAbsenceDefault = `ABSENCE_TYPE_UNSPECIFIED`;

export const AgentWorkingScheduleServiceSearchAgentsWorkingScheduleResponse =
	zod.object({
		holidays: zod
			.array(
				zod.object({
					date: zod.string().optional(),
					name: zod.string().optional(),
				}),
			)
			.optional(),
		items: zod
			.array(
				zod.object({
					agent: zod
						.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						})
						.optional(),
					schedule: zod
						.array(
							zod.object({
								absence: zod
									.enum([
										'ABSENCE_TYPE_UNSPECIFIED',
										'ABSENCE_TYPE_DAYOFF',
										'ABSENCE_TYPE_VACATION',
										'ABSENCE_TYPE_SICKDAY',
									])
									.default(
										agentWorkingScheduleServiceSearchAgentsWorkingScheduleResponseItemsItemScheduleItemAbsenceDefault,
									),
								date: zod.string().optional(),
								locked: zod.boolean().optional(),
								shift: zod
									.object({
										created_at: zod.string().optional(),
										created_by: zod
											.object({
												id: zod.string().optional(),
												name: zod.string().optional(),
											})
											.optional(),
										domain_id: zod.string().optional(),
										end: zod.string().optional(),
										id: zod.string().optional(),
										pauses: zod
											.array(
												zod.object({
													cause: zod
														.object({
															id: zod.string().optional(),
															name: zod.string().optional(),
														})
														.optional(),
													created_at: zod.string().optional(),
													created_by: zod
														.object({
															id: zod.string().optional(),
															name: zod.string().optional(),
														})
														.optional(),
													domain_id: zod.string().optional(),
													end: zod.string().optional(),
													id: zod.string().optional(),
													start: zod.string().optional(),
													updated_at: zod.string().optional(),
													updated_by: zod
														.object({
															id: zod.string().optional(),
															name: zod.string().optional(),
														})
														.optional(),
												}),
											)
											.optional(),
										skills: zod
											.array(
												zod.object({
													capacity: zod.string().optional(),
													enabled: zod.boolean().optional(),
													skill: zod
														.object({
															id: zod.string().optional(),
															name: zod.string().optional(),
														})
														.optional(),
												}),
											)
											.optional(),
										start: zod.string().optional(),
										updated_at: zod.string().optional(),
										updated_by: zod
											.object({
												id: zod.string().optional(),
												name: zod.string().optional(),
											})
											.optional(),
									})
									.optional(),
							}),
						)
						.optional(),
				}),
			)
			.optional(),
		total: zod.string().optional(),
	});

export const AgentWorkingScheduleServiceCreateAgentsWorkingScheduleShiftsParams =
	zod.object({
		working_schedule_id: zod.string(),
	});

export const AgentWorkingScheduleServiceCreateAgentsWorkingScheduleShiftsBody =
	zod.object({
		agents: zod
			.array(
				zod.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				}),
			)
			.optional(),
		date: zod
			.object({
				from: zod.string().optional(),
				to: zod.string().optional(),
			})
			.optional(),
		items: zod
			.record(
				zod.string(),
				zod.object({
					created_at: zod.string().optional(),
					created_by: zod
						.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						})
						.optional(),
					domain_id: zod.string().optional(),
					end: zod.string().optional(),
					id: zod.string().optional(),
					pauses: zod
						.array(
							zod.object({
								cause: zod
									.object({
										id: zod.string().optional(),
										name: zod.string().optional(),
									})
									.optional(),
								created_at: zod.string().optional(),
								created_by: zod
									.object({
										id: zod.string().optional(),
										name: zod.string().optional(),
									})
									.optional(),
								domain_id: zod.string().optional(),
								end: zod.string().optional(),
								id: zod.string().optional(),
								start: zod.string().optional(),
								updated_at: zod.string().optional(),
								updated_by: zod
									.object({
										id: zod.string().optional(),
										name: zod.string().optional(),
									})
									.optional(),
							}),
						)
						.optional(),
					skills: zod
						.array(
							zod.object({
								capacity: zod.string().optional(),
								enabled: zod.boolean().optional(),
								skill: zod
									.object({
										id: zod.string().optional(),
										name: zod.string().optional(),
									})
									.optional(),
							}),
						)
						.optional(),
					start: zod.string().optional(),
					updated_at: zod.string().optional(),
					updated_by: zod
						.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						})
						.optional(),
				}),
			)
			.optional()
			.describe('Map key is a day of week: 0 - Sunday, ..., 6 - Saturday.'),
	});

export const agentWorkingScheduleServiceCreateAgentsWorkingScheduleShiftsResponseItemsItemScheduleItemAbsenceDefault = `ABSENCE_TYPE_UNSPECIFIED`;

export const AgentWorkingScheduleServiceCreateAgentsWorkingScheduleShiftsResponse =
	zod.object({
		items: zod
			.array(
				zod.object({
					agent: zod
						.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						})
						.optional(),
					schedule: zod
						.array(
							zod.object({
								absence: zod
									.enum([
										'ABSENCE_TYPE_UNSPECIFIED',
										'ABSENCE_TYPE_DAYOFF',
										'ABSENCE_TYPE_VACATION',
										'ABSENCE_TYPE_SICKDAY',
									])
									.default(
										agentWorkingScheduleServiceCreateAgentsWorkingScheduleShiftsResponseItemsItemScheduleItemAbsenceDefault,
									),
								date: zod.string().optional(),
								locked: zod.boolean().optional(),
								shift: zod
									.object({
										created_at: zod.string().optional(),
										created_by: zod
											.object({
												id: zod.string().optional(),
												name: zod.string().optional(),
											})
											.optional(),
										domain_id: zod.string().optional(),
										end: zod.string().optional(),
										id: zod.string().optional(),
										pauses: zod
											.array(
												zod.object({
													cause: zod
														.object({
															id: zod.string().optional(),
															name: zod.string().optional(),
														})
														.optional(),
													created_at: zod.string().optional(),
													created_by: zod
														.object({
															id: zod.string().optional(),
															name: zod.string().optional(),
														})
														.optional(),
													domain_id: zod.string().optional(),
													end: zod.string().optional(),
													id: zod.string().optional(),
													start: zod.string().optional(),
													updated_at: zod.string().optional(),
													updated_by: zod
														.object({
															id: zod.string().optional(),
															name: zod.string().optional(),
														})
														.optional(),
												}),
											)
											.optional(),
										skills: zod
											.array(
												zod.object({
													capacity: zod.string().optional(),
													enabled: zod.boolean().optional(),
													skill: zod
														.object({
															id: zod.string().optional(),
															name: zod.string().optional(),
														})
														.optional(),
												}),
											)
											.optional(),
										start: zod.string().optional(),
										updated_at: zod.string().optional(),
										updated_by: zod
											.object({
												id: zod.string().optional(),
												name: zod.string().optional(),
											})
											.optional(),
									})
									.optional(),
							}),
						)
						.optional(),
				}),
			)
			.optional(),
	});
