<template>
  <section class="module docs-content-wrapper">
    <h2>Audit Form Module</h2>
    <pre><code class="language-markup">
      &lt;div&gt;
        &lt;audit-form
          v-model:questions="auditQuestions"
          mode="create"
          &gt;&lt;/audit-form&gt;
        &lt;audit-form
          :questions="auditQuestions"
          v-model:result="auditResult"
          mode="fill"
          &gt;&lt;/audit-form&gt;
      &lt;/div&gt;
    </code></pre>
    <pre><code class="language-javascript">
import AuditForm from '@webitel/ui-sdk/src/modules/AuditForm/components/audit-form.vue';
    </code></pre>
    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
      <div>
        <audit-form
          v-model:questions="auditQuestions"
          mode="create"
        ></audit-form>
        <article>
          <h3>Questions</h3>
          <pre><code class="language-javascript">
        {{ auditQuestions }}
        </code></pre>
        </article>
      </div>
      <div>
        <audit-form
          :questions="auditQuestions"
          v-model:result="auditResult"
          mode="fill"
        ></audit-form>
        <article>
          <h3>Result</h3>
          <pre><code class="language-javascript">
        {{ auditResult }}
        </code></pre>
        </article>
      </div>
    </div>

    <component-props
      :properties="properties"
    ></component-props>

    <component-events
      :events="events"
    ></component-events>
  </section>
</template>

<script setup>
import Prism from 'prismjs';
import { onMounted, ref } from 'vue';
import AuditForm from '@webitel/ui-sdk/src/modules/AuditForm/components/audit-form.vue';
import { EngineAuditQuestionType } from 'webitel-sdk';
import ComponentProps from '../../../../shared/component-props.vue';

const auditQuestions = ref([
  {
    required: true,
    question: 'My Anketa number 1',
    type: EngineAuditQuestionType.Option,
    options: [
      {
        name: 'My first var!',
        score: 5,
      },
      {
        name: 'My lorem ipsum var!',
        score: 10,
      },
    ],
  },
  {
    required: true,
    question: 'My anketa number two!',
    type: EngineAuditQuestionType.Score,
    min: 1,
    max: 5,
  },
]);

const auditResult = ref([]);

const properties = [
  {
    value: 'mode',
    type: 'String',
    required: true,
    options: ['create', 'fill'],
    description: '"Fill" mode is for form filling, "create" -- for form creation'
  },
  {
    value: 'questions',
    type: 'Array',
    required: true,
    description: 'For questions format, see "Questions" above'
  },
  {
    value: 'result',
    type: 'Array',
    description: 'Result is autogenerated'
  },
  {
    value: 'readonly',
    type: 'Boolean',
    default: false,
    description: 'Shows form in readonly mode'
  },
];

const events = [
  {
    value: 'update:questions',
    params: 'questions',
    description: 'Updated questions array',
  },
  {
    value: 'update:result',
    params: 'result',
    description: 'Updated result array',
  },
  {
    value: 'update:validation',
    params: '{ invalid: Boolean, v$: object from Vuelidate }',
  },
];

onMounted(() => {
  Prism.highlightAll();
});
</script>

<style lang="scss" scoped>

</style>
