export const FilterOption = {
	Agent: 'agent',
	AmdResult: 'amdResult',
	Contact: 'contact',
	CallDirection: 'direction',
	Rated: 'rated',
	Gateway: 'gateway',
	Grantee: 'grantee',
	HangupCause: 'cause',
	Queue: 'queue',
	RatedBy: 'ratedBy',
	HasFile: 'hasFile',
	Score: 'score',
	Tag: 'tag',
	QueueTags: 'tags',
	TalkDuration: 'talkDuration',
	Team: 'team',
	TotalDuration: 'totalDuration',
	AttemptDuration: 'duration',
	HasTranscription: 'hasTranscription',
	User: 'user',
	Variable: 'variable',
	CreatedAt: 'createdAt',
	CaseStatus: 'status',
	CaseSource: 'source',
	CaseService: 'service',
	CaseAuthor: 'author',
	CaseReporter: 'reporter',
	CaseImpacted: 'impacted',
	CaseAssignee: 'assignee',
	ContactGroup: 'contactGroup',
	ContactLabel: 'contactLabel',
	ContactOwner: 'contactOwner',
	CasePriority: 'priority',
	CaseCloseReasonGroups: 'closeReasonGroups',
	Rating: 'rating',
	CaseSla: 'sla',
	CaseSlaCondition: 'slaCondition',
	CaseReactionTime: 'reactionTime',
	CaseResolutionTime: 'resolutionTime',
	CaseActualReactionTime: 'actualReactionTime',
	CaseActualResolutionTime: 'actualResolutionTime',
	HasAttachment: 'hasAttachment',
	HasUser: 'hasUser',
	QueueType: 'queueType',
	QueuePeriod: 'queuePeriod',
	AgentStatus: 'agentStatus',
	Skill: 'skill',
	Supervisor: 'supervisor',
	Auditor: 'auditor',
	Region: 'region',
	UtilizationProgress: 'utilizationProgress',
	Bucket: 'bucket',
	JoinedAt: 'joinedAt',
	LeavingAt: 'leavingAt',
	OfferingAt: 'offeringAt',
	StopCause: 'stopCause',
	MemberPriority: 'memberPriority',
	MemberAttempts: 'attempts',
	MemberName: 'name',
	MemberDestination: 'destination',
	/** queue attempt CallReportingStatus. Name/param is backend `result`. */
	CallReportingResult: 'result',
} as const;

/**
 *
 * @description
 * any custom lookup fields or type extensions
 */
export type CustomFilterOption = string;

export type FilterOption =
	| (typeof FilterOption)[keyof typeof FilterOption]
	| CustomFilterOption;
