/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import * as zod from 'zod';

export const WorkingScheduleServiceSearchWorkingScheduleQueryParams =
	zod.object({
		q: zod.string().optional(),
		page: zod.int().optional(),
		size: zod.int().optional(),
		sort: zod.string().optional(),
		fields: zod.array(zod.string()).optional(),
	});

export const workingScheduleServiceSearchWorkingScheduleResponseItemsItemStateDefault = `WORKING_SCHEDULE_STATE_UNSPECIFIED`;

export const WorkingScheduleServiceSearchWorkingScheduleResponse = zod.object({
	items: zod
		.array(
			zod.object({
				agents: zod
					.array(
						zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
					)
					.optional(),
				block_outside_activity: zod.boolean().optional(),
				calendar: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				created_at: zod.string().optional(),
				created_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				domain_id: zod.string().optional(),
				end_date_at: zod.string().optional(),
				end_time_at: zod.string().optional(),
				extra_skills: zod
					.array(
						zod.object({
							id: zod.string().optional(),
							name: zod.string().optional(),
						}),
					)
					.optional(),
				id: zod.string().optional(),
				name: zod.string().optional(),
				start_date_at: zod.string().optional(),
				start_time_at: zod.string().optional(),
				state: zod
					.enum([
						'WORKING_SCHEDULE_STATE_UNSPECIFIED',
						'WORKING_SCHEDULE_STATE_ACTIVE',
						'WORKING_SCHEDULE_STATE_PENDING',
						'WORKING_SCHEDULE_STATE_DRAFT',
						'WORKING_SCHEDULE_STATE_ARCHIVED',
					])
					.default(
						workingScheduleServiceSearchWorkingScheduleResponseItemsItemStateDefault,
					),
				team: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
				total_agents: zod.string().optional(),
				updated_at: zod.string().optional(),
				updated_by: zod
					.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					})
					.optional(),
			}),
		)
		.optional(),
	next: zod.boolean().optional(),
});

export const workingScheduleServiceCreateWorkingScheduleBodyItemStateDefault = `WORKING_SCHEDULE_STATE_UNSPECIFIED`;

export const WorkingScheduleServiceCreateWorkingScheduleBody = zod.object({
	item: zod
		.object({
			agents: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			block_outside_activity: zod.boolean().optional(),
			calendar: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			domain_id: zod.string().optional(),
			end_date_at: zod.string().optional(),
			end_time_at: zod.string().optional(),
			extra_skills: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			start_date_at: zod.string().optional(),
			start_time_at: zod.string().optional(),
			state: zod
				.enum([
					'WORKING_SCHEDULE_STATE_UNSPECIFIED',
					'WORKING_SCHEDULE_STATE_ACTIVE',
					'WORKING_SCHEDULE_STATE_PENDING',
					'WORKING_SCHEDULE_STATE_DRAFT',
					'WORKING_SCHEDULE_STATE_ARCHIVED',
				])
				.default(
					workingScheduleServiceCreateWorkingScheduleBodyItemStateDefault,
				),
			team: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			total_agents: zod.string().optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});

export const workingScheduleServiceCreateWorkingScheduleResponseItemStateDefault = `WORKING_SCHEDULE_STATE_UNSPECIFIED`;

export const WorkingScheduleServiceCreateWorkingScheduleResponse = zod.object({
	item: zod
		.object({
			agents: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			block_outside_activity: zod.boolean().optional(),
			calendar: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			domain_id: zod.string().optional(),
			end_date_at: zod.string().optional(),
			end_time_at: zod.string().optional(),
			extra_skills: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			start_date_at: zod.string().optional(),
			start_time_at: zod.string().optional(),
			state: zod
				.enum([
					'WORKING_SCHEDULE_STATE_UNSPECIFIED',
					'WORKING_SCHEDULE_STATE_ACTIVE',
					'WORKING_SCHEDULE_STATE_PENDING',
					'WORKING_SCHEDULE_STATE_DRAFT',
					'WORKING_SCHEDULE_STATE_ARCHIVED',
				])
				.default(
					workingScheduleServiceCreateWorkingScheduleResponseItemStateDefault,
				),
			team: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			total_agents: zod.string().optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});

export const WorkingScheduleServiceDeleteWorkingScheduleParams = zod.object({
	id: zod.string(),
});

export const WorkingScheduleServiceDeleteWorkingScheduleResponse = zod.object({
	id: zod.string().optional(),
});

export const WorkingScheduleServiceReadWorkingScheduleParams = zod.object({
	id: zod.string(),
});

export const WorkingScheduleServiceReadWorkingScheduleQueryParams = zod.object({
	fields: zod.array(zod.string()).optional(),
});

export const workingScheduleServiceReadWorkingScheduleResponseItemStateDefault = `WORKING_SCHEDULE_STATE_UNSPECIFIED`;

export const WorkingScheduleServiceReadWorkingScheduleResponse = zod.object({
	item: zod
		.object({
			agents: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			block_outside_activity: zod.boolean().optional(),
			calendar: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			domain_id: zod.string().optional(),
			end_date_at: zod.string().optional(),
			end_time_at: zod.string().optional(),
			extra_skills: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			start_date_at: zod.string().optional(),
			start_time_at: zod.string().optional(),
			state: zod
				.enum([
					'WORKING_SCHEDULE_STATE_UNSPECIFIED',
					'WORKING_SCHEDULE_STATE_ACTIVE',
					'WORKING_SCHEDULE_STATE_PENDING',
					'WORKING_SCHEDULE_STATE_DRAFT',
					'WORKING_SCHEDULE_STATE_ARCHIVED',
				])
				.default(
					workingScheduleServiceReadWorkingScheduleResponseItemStateDefault,
				),
			team: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			total_agents: zod.string().optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});

export const WorkingScheduleServiceUpdateWorkingScheduleAddAgentsParams =
	zod.object({
		id: zod.string(),
	});

export const WorkingScheduleServiceUpdateWorkingScheduleAddAgentsBody =
	zod.object({
		agents: zod
			.array(
				zod.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				}),
			)
			.optional(),
	});

export const WorkingScheduleServiceUpdateWorkingScheduleAddAgentsResponse =
	zod.object({
		agents: zod
			.array(
				zod.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				}),
			)
			.optional(),
	});

export const WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentParams =
	zod.object({
		id: zod.string(),
		agent_id: zod.string(),
	});

export const WorkingScheduleServiceUpdateWorkingScheduleRemoveAgentResponse =
	zod.object({
		id: zod.string().optional(),
	});

export const WorkingScheduleServiceReadWorkingScheduleForecastParams =
	zod.object({
		id: zod.string(),
	});

export const WorkingScheduleServiceReadWorkingScheduleForecastQueryParams =
	zod.object({
		'date.from': zod.string().optional(),
		'date.to': zod.string().optional(),
	});

export const WorkingScheduleServiceReadWorkingScheduleForecastResponse =
	zod.object({
		items: zod
			.record(
				zod.string(),
				zod.object({
					forecast: zod
						.array(
							zod.object({
								agents: zod.string().optional(),
								hour: zod.string().optional(),
							}),
						)
						.optional(),
				}),
			)
			.optional(),
	});

export const WorkingScheduleServiceUpdateWorkingScheduleParams = zod.object({
	'item.id': zod.string(),
});

export const workingScheduleServiceUpdateWorkingScheduleBodyItemStateDefault = `WORKING_SCHEDULE_STATE_UNSPECIFIED`;

export const WorkingScheduleServiceUpdateWorkingScheduleBody = zod.object({
	item: zod
		.object({
			agents: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			block_outside_activity: zod.boolean().optional(),
			calendar: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			domain_id: zod.string().optional(),
			end_date_at: zod.string().optional(),
			end_time_at: zod.string().optional(),
			extra_skills: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			name: zod.string().optional(),
			start_date_at: zod.string().optional(),
			start_time_at: zod.string().optional(),
			state: zod
				.enum([
					'WORKING_SCHEDULE_STATE_UNSPECIFIED',
					'WORKING_SCHEDULE_STATE_ACTIVE',
					'WORKING_SCHEDULE_STATE_PENDING',
					'WORKING_SCHEDULE_STATE_DRAFT',
					'WORKING_SCHEDULE_STATE_ARCHIVED',
				])
				.default(
					workingScheduleServiceUpdateWorkingScheduleBodyItemStateDefault,
				),
			team: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			total_agents: zod.string().optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});

export const workingScheduleServiceUpdateWorkingScheduleResponseItemStateDefault = `WORKING_SCHEDULE_STATE_UNSPECIFIED`;

export const WorkingScheduleServiceUpdateWorkingScheduleResponse = zod.object({
	item: zod
		.object({
			agents: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			block_outside_activity: zod.boolean().optional(),
			calendar: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			created_at: zod.string().optional(),
			created_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			domain_id: zod.string().optional(),
			end_date_at: zod.string().optional(),
			end_time_at: zod.string().optional(),
			extra_skills: zod
				.array(
					zod.object({
						id: zod.string().optional(),
						name: zod.string().optional(),
					}),
				)
				.optional(),
			id: zod.string().optional(),
			name: zod.string().optional(),
			start_date_at: zod.string().optional(),
			start_time_at: zod.string().optional(),
			state: zod
				.enum([
					'WORKING_SCHEDULE_STATE_UNSPECIFIED',
					'WORKING_SCHEDULE_STATE_ACTIVE',
					'WORKING_SCHEDULE_STATE_PENDING',
					'WORKING_SCHEDULE_STATE_DRAFT',
					'WORKING_SCHEDULE_STATE_ARCHIVED',
				])
				.default(
					workingScheduleServiceUpdateWorkingScheduleResponseItemStateDefault,
				),
			team: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
			total_agents: zod.string().optional(),
			updated_at: zod.string().optional(),
			updated_by: zod
				.object({
					id: zod.string().optional(),
					name: zod.string().optional(),
				})
				.optional(),
		})
		.optional(),
});
