/**
 * Represents existing Webitel entities
 */
export declare const WtObject: {
	readonly Agent: 'agent';
	readonly Queue: 'queue';
	readonly Contact: 'contact';
	readonly Region: 'region';
	readonly User: 'user';
	readonly Resource: 'resource';
	readonly Device: 'device';
	readonly License: 'license';
	readonly Flow: 'flow';
	readonly Dialplan: 'dialplan';
	readonly Gateway: 'gateway';
	readonly Chatplan: 'chatplan';
	readonly ChatGateway: 'chatGateway';
	readonly Blacklist: 'blacklist';
	readonly Calendar: 'calendar';
	readonly Communication: 'communication';
	readonly PauseCause: 'pauseCause';
	readonly Media: 'media';
	readonly ShiftTemplate: 'shiftTemplate';
	readonly PauseTemplate: 'pauseTemplate';
	readonly WorkingCondition: 'workingCondition';
	readonly Skill: 'skill';
	readonly Bucket: 'bucket';
	readonly Member: 'member';
	readonly ResourceGroup: 'resourceGroup';
	readonly Team: 'team';
	readonly Storage: 'storage';
	readonly CognitiveProfile: 'cognitiveProfile';
	readonly EmailProfile: 'emailProfile';
	readonly SingleSignOn: 'singleSignOn';
	readonly ImportCsv: 'importCsv';
	readonly Trigger: 'trigger';
	readonly Role: 'role';
	readonly Object: 'object';
	readonly ChangeLog: 'changelog';
	readonly Configuration: 'configuration';
	readonly GlobalVariable: 'globalVariable';
	readonly Call: 'call';
	readonly RecordFile: 'recordFile';
	readonly ContactGroup: 'contactGroup';
	readonly Case: 'case';
	readonly CaseComment: 'caseComment';
	readonly Slas: 'slas';
	readonly ServiceCatalog: 'serviceCatalog';
	readonly CaseSource: 'caseSource';
	readonly CloseReasonGroup: 'closeReasonGroup';
	readonly Priorities: 'priorities';
	readonly Status: 'status';
	readonly Source: 'source';
	readonly CustomLookup: 'customLookup';
	readonly AuditForm: 'auditForm';
	readonly AuditRating: 'auditRating';
	readonly QuickReply: 'quickReply';
	readonly ListNumber: 'listNumber';
	readonly AgentWorkingCondition: 'agentWorkingCondition';
	readonly FilePolicy: 'filePolicy';
	readonly PortalUser: 'portalUser';
};
export type WtObject = (typeof WtObject)[keyof typeof WtObject];
