/**
 * Represents existing Webitel entities
 */
export const WtObject = {
  Agent: 'agent',
  Queue: 'queue',
  Contact: 'contact',
  Region: 'region',
  User: 'user',
  Resource: 'resource',
  Device: 'device',
  License: 'license',
  Flow: 'flow',
  Dialplan: 'dialplan',
  Gateway: 'gateway',
  Chatplan: 'chatplan',
  ChatGateway: 'chat-gateway',
  Blacklist: 'blacklist',
  Calendar: 'calendar',
  Communication: 'communication',
  PauseCause: 'pause-cause',
  Media: 'media',
  ShiftTemplate: 'shift-template',
  PauseTemplate: 'pause-template',
  WorkingCondition: 'working-condition',
  Skill: 'skill',
  Bucket: 'bucket',
  Member: 'member',
  ResourceGroup: 'resource-group',
  Team: 'team',
  Storage: 'storage',
  CognitiveProfile: 'cognitive-profile',
  EmailProfile: 'email-profile',
  SingleSignOn: 'single-sign-on',
  ImportCsv: 'import-csv',
  Trigger: 'trigger',
  Role: 'role',
  Object: 'object',
  ChangeLog: 'changelog',
  Configuration: 'configuration',
  GlobalVariable: 'global-variable',
  ActiveCall: 'active-call',
  Scorecard: 'scorecard',
} as const;

export type WtObject = (typeof WtObject)[keyof typeof WtObject];
