/**
 * Represents existing Webitel entities
 */
export const WtObject = {
  Agent: 'agent',
  Queue: 'queue',
  Contact: 'contact',
  Region: 'region',
  User: 'user',
  Resource: 'resource',
  Device: 'device',
  License: 'license',
  Flow: 'flow',
  Dialplan: 'dialplan',
  Gateway: 'gateway',
  Chatplan: 'chatplan',
  ChatGateway: 'chatGateway',
  Blacklist: 'blacklist',
  Calendar: 'calendar',
  Communication: 'communication',
  PauseCause: 'pauseCause',
  Media: 'media',
  ShiftTemplate: 'shiftTemplate',
  PauseTemplate: 'pauseTemplate',
  WorkingCondition: 'workingCondition',
  Skill: 'skill',
  Bucket: 'bucket',
  Member: 'member',
  ResourceGroup: 'resourceGroup',
  Team: 'team',
  Storage: 'storage',
  CognitiveProfile: 'cognitiveProfile',
  EmailProfile: 'emailProfile',
  SingleSignOn: 'singleSignOn',
  ImportCsv: 'importCsv',
  Trigger: 'trigger',
  Role: 'role',
  Object: 'object',
  ChangeLog: 'changelog',
  Configuration: 'configuration',
  GlobalVariable: 'globalVariable',
  ActiveCall: 'activeCall',
  Scorecard: 'scorecard',
  Logger: 'logger',
  Call: 'call',
  RecordFile: 'recordFile',
  ContactGroup: 'contactGroup',
  ChatBot: 'chatBot',
  Case: 'case',
  CaseComment: 'caseComment',
  Slas: 'slas',
  ServiceCatalog: 'serviceCatalog',
  CaseSource: 'caseSource',
  CloseReasonGroup: 'closeReasonGroup',
  Priorities: 'priorities',
  Status: 'status',
  Source: 'source',
  CustomLookup: 'customLookup',
} as const;

export type WtObject = (typeof WtObject)[keyof typeof WtObject];
