name: webitel api-services pkg publish

on:
#  https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

#  ATTENTION! deps install is currently not needed because package is publishing as is, without build

#  install_deps:
#    runs-on: ubuntu-latest
#    steps:
jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
          registry-url: https://registry.npmjs.org

      - name: Publish release
        id: publish_release

        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          cd packages/api-services
          npm ci
          npm run make-all
