name: webitel api-services generate api

on:
#  https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true

      - name: Generate API
        id: generate_api

        run: |
          cd packages/api-services
          npm ci
          npm run gen:api

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
