name: webitel api-services pkg publish

on:
#  https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Publish release
        id: publish_release

        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          cd packages/api-services
          npm ci
          npm version patch && (npm run build:types || true) && (npm run format:all || true) && npm run publish-lib

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
