name: Webitel UI run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@latest
      with:
        node-version: lts/*
    - run: npm ci
    - run: npm run test:unit
