name: webitel ui-datalist pkg publish

on:
#  https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
          registry-url: https://registry.npmjs.org

      - name: Publish release
        id: publish_release
        # if: ${{ steps.check_publish.outputs.exists == '0' }}

        run: |
          echo "Publishing release, ${{ steps.check_publish.outputs.exists }}"
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          cd packages/ui-datalist
          npm ci
          npm run make-all

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
