name: webitel ui-datalist pckg publish

on:
#  https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
#  ATTENTION! deps install is currently not needed because package is publishing as is, without build

#  install_deps:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - run: cd packages/ui-datalist #!
#
#      - name: Cache node_modules
#        uses: actions/cache@v4
#        id: cache_node_modules
#        with:
#          path: node_modules
#          key: node_modules-${{ hashFiles('**/package-lock.json') }}
#
#      - name: Use Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: lts/*
#          check-latest: true
#
#      - name: Install dependencies
#        if: steps.cache_node_modules.outputs.cache-hit != 'true'
#        run: npm ci

  publish:
#    needs: [install_deps]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - run: cd packages/ui-datalist #!

#      - uses: actions/cache@v3
#        with:
#          path: node_modules
#          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
          registry-url: https://registry.npmjs.org

      # - name: Check publish status
      #   id: check_publish
      #   uses: tehpsalmist/npm-publish-status-action@v1 #works ONLY FOR ROOT-lvl package

      - name: Publish release
        id: publish_release
        # if: ${{ steps.check_publish.outputs.exists == '0' }}

        run: |
          cd packages/ui-datalist
          echo "Publishing release, ${{ steps.check_publish.outputs.exists }}"
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish --access public

      # - name: Report publish status
      #   if: ${{ steps.check_publish.outputs.exists == '1' }}
      #   run: echo "Package already published"
