name: Make Release (Auto-merge)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version, next_version - major.minor only (e.g., "26.4, 26.6")'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=22"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set version variables
        id: version
        run: |
          INPUT="${{ inputs.version }}"
          VERSION=$(echo $INPUT | cut -d',' -f1 | tr -d ' ') #splits versions from input by separator
          NEXT_VERSION=$(echo $INPUT | cut -d',' -f2 | tr -d ' ') #splits versions from input by separator
          
          # Add .0 patch version for package.json
          echo "version=$VERSION"
          echo "next_full_version=${NEXT_VERSION}.0"
          echo "version_tag=v${VERSION}"
          echo "version_git_tag=v${VERSION}-tagged"

      - name: Create release branch
        run: |
          git checkout -b ${{ steps.version.outputs.version_tag }}
          git push -u origin "${{ steps.version.outputs.version_tag }}"

      - name: Bump version in main to next version
        run: |
          git checkout ${{ github.event.repository.default_branch }}
          npm version "${{ steps.version.outputs.next_full_version }}" --no-git-tag-version --allow-same-version
          
          git add package.json
          git commit -m "chore: bump version to ${{ steps.version.outputs.full_version }}"
          git push origin ${{ github.event.repository.default_branch }}

      - name: Create and push tag (after merge)
        run: |
          git checkout "${{ steps.version.outputs.version_tag }}"
          git tag ${{ steps.version.outputs.version_tag }}
          git push --tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version_tag }}
          name: Release ${{ steps.version.outputs.version_tag }}
          generate_release_notes: true
