/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Webitel API
 * OpenAPI spec version: 24.04.0
 */
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

import axios from '../../api/axios/genClient';

import type {
	EngineSearchSchemaVersionResponse,
	SearchSchemaVersionParams,
} from '../_models';

// --- header start
//

export const // --- title start
	getSchemaVersionService =
		// --- title end
		(axiosInstance: AxiosInstance = axios) => {
			// --- header end
			const searchSchemaVersion = (
				schemaId: string,
				params?: SearchSchemaVersionParams,
				options?: AxiosRequestConfig,
			): Promise<AxiosResponse<EngineSearchSchemaVersionResponse>> => {
				return axiosInstance.get(`/routing/schema/${schemaId}/versions`, {
					...options,
					params: {
						...params,
						...options?.params,
					},
				});
			};

			// --- footer start
			return {
				searchSchemaVersion,
			};
		};
export type SearchSchemaVersionResult =
	AxiosResponse<EngineSearchSchemaVersionResponse>;

// --- footer end
